ANXIETY = [
    "My heart races when I think about going to work tomorrow",
    "I can't stop worrying about things that haven't happened yet",
    "I feel a constant sense of dread that won't go away",
    "I had a panic attack in the grocery store yesterday",
    "I overthink every conversation I have and replay it for hours",
    "My hands shake when I'm in social situations",
    "I avoid crowded places because they make me panic",
    "I can't sleep because my mind won't stop racing",
    "I'm terrified of making mistakes at work",
    "I check the door lock five times before I can leave the house",
    "My stomach is always in knots when I have to meet new people",
    "I feel like something terrible is about to happen at any moment",
    "I've been having shortness of breath even when I'm not exercising",
    "I can't make decisions because I'm scared of choosing wrong",
    "I rehearse phone calls in my head before I make them",
    "I feel on edge all the time like I'm waiting for disaster",
    "My mind catastrophizes every situation automatically",
    "I got so anxious about a presentation that I called in sick",
    "I avoid driving on the highway because I fear losing control",
    "I feel dizzy and lightheaded when anxiety hits",
    "I wash my hands repeatedly because I'm afraid of germs",
    "Small uncertainties send me into a spiral of worry",
    "I'm afraid of embarrassing myself in front of others",
    "I've turned down job opportunities because they made me too nervous",
    "My anxiety makes it hard to eat in public",
    "I feel like I'm constantly bracing for something bad",
    "I tense up my whole body and don't even realize I'm doing it",
    "I can't enjoy social events because I'm too busy worrying",
    "My anxiety makes me cancel plans at the last minute",
    "I feel overwhelmed by noise and busy environments",
    "I worry about my health constantly even when tests come back normal",
    "I need constant reassurance that I haven't offended someone",
    "I have racing thoughts that feel completely out of control",
    "I avoid elevators because I'm scared of being trapped",
    "My anxiety spikes when I receive unexpected messages",
    "I struggle to be present because I'm always worrying about the future",
    "My chest tightens every Sunday night because of Monday",
    "I set multiple alarms because I'm terrified of oversleeping",
    "I've been grinding my teeth from tension",
    "Even good news triggers a sense of waiting for the other shoe to drop",
    "Crowds make me feel claustrophobic and panicky",
    "I startle very easily at sudden noises",
    "I worry that I have a serious illness even when doctors reassure me",
    "My anxiety is exhausting because it never fully stops",
    "I feel paralyzed by anticipatory anxiety",
    "My palms get sweaty before any kind of performance",
    "I overthink texts before sending them",
    "I feel nervous around authority figures even when I've done nothing wrong",
    "My anxiety surfaces as irritability and snapping at loved ones",
    "I can't delegate because I'm afraid things won't be done correctly",
    "My heart pounds when the phone rings unexpectedly",
    "i get physically sick before social events throwing up from nerves",
    "my anxiety is so bad i havent left my apartment in days",
    "i keep checking if the stove is off even though i already checked",
    "every time someone looks at me i think they are judging me",
    "i feel like everyone is watching me and waiting for me to fail",
    "my chest feels tight all the time and its hard to breathe",
    "i have intrusive thoughts about terrible things happening to my family",
    "i cant eat before important events because my stomach is in knots",
    "i stay up all night worrying about things i said during the day",
    "i feel unsafe everywhere even at home with the doors locked",
    "social media gives me anxiety because i compare myself constantly",
    "i feel like im always on high alert waiting for danger",
    "i have to plan every detail or i spiral into panic",
    "i feel trapped when i cant see the exit in a room",
    "my heart races so fast during panic attacks i think im dying",
    "i avoid answering the door because i dont know who it might be",
    "i get anxious about being anxious which makes it even worse",
    "i worry that people secretly dislike me and just pretend",
    "the physical symptoms of anxiety are ruining my daily life",
    "i feel restless and unable to sit still because of constant worry",
    "i have to arrive early everywhere because being late gives me panic",
    "i pick at my skin when im anxious and cant stop",
    "my anxiety makes my vision blur and my ears ring",
    "i feel terror for no identifiable reason just pure dread",
    "i avoid speaking up in meetings because my voice shakes",
    "i lie awake imagining every possible worst case scenario",
    "i feel like my throat is closing when im in crowded spaces",
    "i worry obsessively that i left the car unlocked",
    "i get anxious about future events weeks before they happen",
    "i feel a constant tightness in my shoulders from being so tense",
    "i avoid eye contact because it makes me extremely uncomfortable",
    "panic attacks come out of nowhere and leave me shaking for hours",
    "i feel like i need to control everything or something bad will happen",
    "i second guess every decision i make even tiny ones",
    "i have a constant buzzing anxious energy that wont calm down",
    "my anxiety has made me agoraphobic i cant go outside comfortably",
    "i feel waves of nausea whenever i have to talk to strangers",
    "i check my phone obsessively afraid i missed something important",
    "i worry about having a heart attack even though im young and healthy",
    "i rehearse conversations over and over before having them",
    "i feel like everyone can see how nervous i am and its humiliating",
    "my hands tremble so badly i cant write in front of others",
    "i avoid public restrooms because of contamination fears",
    "the anxiety makes me feel detached from reality like nothing is real",
    "i get anxious reading the news and have to stop myself",
    "i feel like im walking on eggshells around everyone",
    "i have nightmares about embarrassing social situations",
    "my worry about the future prevents me from enjoying the present",
    "i feel jittery and on edge from the moment i wake up",
    "i have developed a stutter from anxiety that i never had before",
    "i hold my breath without realizing it when im stressed",
    "i feel like every minor symptom is a sign of a deadly disease",
    "i avoid driving because i fear causing an accident",
    "my anxiety manifests as constant headaches and muscle tension",
    "i feel like i need permission to do normal everyday things",
    "i cant relax even on vacation my mind is always racing",
    "i feel a lump in my throat constantly from anxiety",
    "i obsess over whether i locked the door for hours after leaving",
    "i get panic attacks in the shower because i feel trapped",
    "i avoid making phone calls and let everything go to voicemail",
    "my anxiety makes me feel like im losing my mind",
    "i feel dizzy and faint in situations where i cant escape easily",
    "i keep replaying awkward moments from years ago",
    "i feel paralyzed when faced with too many choices",
    "my heart skips beats when im anxious and it terrifies me more",
    "i feel like i need to prepare for every possible disaster",
    "i cancel doctors appointments because going there makes me anxious",
    "i feel constant dread that something terrible will happen to loved ones",
    "i avoid flying because being trapped in a plane panics me",
    "i feel like my anxiety controls my entire life",
    "i get physically exhausted from worrying all day long",
    "i feel like i cant trust my own mind because it always lies about danger",
    "i wake up in the middle of the night with my heart pounding from worry",
    "i feel like i am on a treadmill of worry that never stops",
    "i am afraid to try new things because the unknown terrifies me",
    "i feel anxious about feeling calm because it wont last",
    "i have trouble swallowing when anxiety hits like my throat closes up",
    "i feel a sense of impending doom every single morning",
    "i avoid conflict at all costs because confrontation sends me spiraling",
    "i feel like i am constantly one step away from a breakdown",
    "i freeze up completely when put on the spot",
    "my anxiety has isolated me from people i care about",
    "i feel like the walls are closing in when im in small spaces",
    "i get chest pain from anxiety that mimics a heart attack",
    "i feel like every social interaction is a test i am failing",
    "i worry about running out of money even when my finances are fine",
    "i feel nervous energy coursing through my body all day long",
    "i check behind the shower curtain before using the bathroom",
    "i am terrified of being the center of attention",
    "my anxiety makes me feel like throwing up before every meeting",
    "i feel like i need to be perfect or everything will fall apart",
    "i get lightheaded and feel like im going to pass out in stores",
    "i avoid restaurants because eating around strangers makes me panic",
    "i feel overwhelmed just thinking about tomorrow",
    "bro my heart is literally beating out of my chest right now",
    "i overthought that text for like an hour before sending it",
    "the fomo is real but the social anxiety is stronger",
    "literally hyperventilating over this exam right now",
    "the thought of making a phone call makes me want to throw up",
    "im shaking so bad i can barely type this",
    "my brain will not shut up and it's making me panic",
    "i just had the worst panic attack in the bathroom stall",
    "social interactions are so draining i feel physically sick",
    "why am i always anticipating the absolute worst case scenario",
    "the impending doom feeling is hitting so hard today",
    "i cant go out tonight my social anxiety is acting up bad",
    "constantly feeling like everyone is staring at me and judging me",
    "my mind is just racing 100 miles an hour and i cant stop it",
    "i checked my locks like six times and im still anxious",
    "im so terrified of embarrassing myself i just stay home",
    "my chest is so tight it feels like an elephant is sitting on it",
    "i literally rehearse my order five times before getting to the counter",
    "the intrusive thoughts are so loud today i cant focus",
    "i keep imagining myself tripping and falling in public",
    "just got a 'we need to talk' text and i am spiraling",
    "the anxiety nausea is so real i cant even look at food",
    "i feel like a deer in headlights constantly",
    "my fight or flight is constantly triggered over nothing",
    "the sensory overload right now is pushing me to the edge",
    "i just want my brain to be quiet for like five minutes",
    "im sweating profusely just thinking about the meeting tomorrow",
    "i always assume people hate me secretly and it ruins my mood",
    "my palms are so sweaty i cant grip anything",
    "i am literally vibrating with anxiety right now",
    "I feel like I’m constantly waiting for a phone call with bad news",
    "My legs feel like jelly whenever I have to walk into a crowded room",
    "I’ve started avoiding the breakroom at work just to avoid small talk",
    "I over-analyze the tone of every email I receive until I’m convinced I’m being fired",
    "The sound of my own heartbeat in my ears at night makes me panic",
    "I feel like a fraud and I’m terrified someone is going to realize it today",
    "I constantly check my rearview mirror to make sure no one is following me",
    "I get anxious when things are going too well because it feels suspicious",
    "I’ve stopped wearing certain clothes because I’m afraid they draw too much attention",
    "My brain feels like it's itching when I'm in a situation I can't control",
    "I get a cold sweat just thinking about having to return an item at a store",
    "I avoid checking my bank account because the 'not knowing' feels safer than the truth",
    "I feel like the air in the room is getting thinner when people start arguing",
    "I have to sit near the exit in theaters or I start to feel claustrophobic",
    "I’ve memorized the 'safe' routes home to avoid driving through heavy traffic",
    "I feel like I’m constantly performing a version of myself that isn’t anxious",
    "The sight of a missed call from an unknown number sends me into a tailspin",
    "I keep a 'worry list' but seeing it all written down just makes the panic worse",
    "I feel physically exhausted from the sheer effort of trying to look 'normal'",
    "I’m terrified that my anxiety is actually a premonition of something real",
    "I avoid making eye contact with the cashier so I don't have to speak",
    "My skin feels hypersensitive and tingly when my stress levels spike",
    "I worry that I’m breathing too loudly in quiet spaces like libraries",
    "I’ve declined promotions because I’m scared of the increased social pressure",
    "I feel a surge of panic whenever I hear a siren, even if it’s blocks away",
    "I overthink my posture in public because I don’t want to look 'weird'",
    "I spend hours Googling symptoms that I know are just caused by my anxiety",
    "I feel like I’m trapped behind a glass wall where I can see life but can't join it",
    "I’m constantly scanning faces in a crowd for signs of disapproval",
    "My jaw is so tight from clenching it all day that it hurts to eat",
    "I feel like a burden to my friends when I tell them how scared I am",
    "I get anxious about being 'too quiet' and then get anxious about 'talking too much'",
    "I’ve missed out on so many memories because I was too busy worrying in my head",
    "The physical sensation of anxiety feels like a constant low-voltage shock",
    "I’m terrified that one day the panic attack won't actually stop",
    "My throat tightens up every time I walk past a group of teenagers laughing",
    "I feel a jolt of electricity in my chest whenever my boss mentions my name",
    "I avoid going to the gym because I think everyone is critiquing my form",
    "I worry that I’m going to accidentally say something offensive and ruin my life",
    "The feeling of a tight collar makes me feel like I’m suffocating from stress",
    "I spend my entire Sunday grieving for the free time I'll lose on Monday",
    "I can’t leave a party without worrying if I said goodbye to the right people",
    "I feel like a ticking time bomb of nerves ready to explode at any second",
    "I check my car’s tire pressure daily because I’m afraid of a blowout on the highway",
    "I rehearse how I’m going to walk across the room before I actually do it",
    "I feel a sense of dread when the weather is too cloudy, like a storm is coming",
    "I avoid the front of the bus because I’m scared the driver will talk to me",
    "My hands are constantly cold and clammy even in warm weather",
    "I worry that I’m going to have a stroke even though I have low blood pressure",
    "I can’t focus on a movie because I’m replaying a mistake I made five years ago",
    "I feel like I need to hold my breath when I’m around sick people",
    "I avoid checking the mail because I’m afraid of bills I can’t pay",
    "My anxiety makes me feel like I’m perpetually three minutes late for something",
    "I get a panic attack when I can’t find my keys immediately",
    "I worry that I’m going to lose my mind and never get it back",
    "I feel like I’m constantly on the verge of crying for no specific reason",
    "I avoid dark rooms because I imagine things lurking in the corners",
    "I get anxious when the phone battery drops below 50 percent",
    "I feel a knot of tension in my stomach that has been there for months",
    "I worry that my friends only tolerate me out of pity",
    "I avoid new restaurants because the menu options are too overwhelming",
    "I feel like I’m being watched through my webcam even when it’s covered",
    "I get a surge of adrenaline when someone knocks on my apartment door",
    "I worry that I’m going to faint in the middle of a speech",
    "I avoid crowded aisles in the store even if I need something from them",
    "I feel a constant need to check if my fly is zipped in public",
    "I worry that I’m going to accidentally send a private text to a group chat",
    "I avoid walking over bridges because I fear they will collapse",
    "I feel a sense of panic when I can’t see a clock",
    "I worry that I’m going to choke on my food while eating alone",
    "I avoid public transportation during rush hour because of the sensory overload",
    "I feel like I’m always waiting for a disaster that never arrives",
    "I get a panic attack when I’m in a car and someone else is driving",
    "I worry that I’m going to drop my phone into a storm drain",
    "I avoid using public Wi-Fi because I’m terrified of being hacked",
    "I feel a lump of lead in my stomach whenever I have to make a choice",
    "I worry that I’m going to have an allergic reaction to a new food",
    "I avoid eye contact with dogs because I’m afraid they’ll bark at me",
    "I feel a sense of dread when the weekend is over",
    "I worry that I’m going to get a flat tire in a bad neighborhood",
    "I avoid taking the stairs because I’m afraid of falling",
    "I feel a surge of panic when I hear my name called in a waiting room",
    "I worry that I’m going to spill a drink on myself in public",
    "I avoid going to the movies because the loud sounds trigger my anxiety",
    "I feel a constant need to check my pulse",
    "I worry that I’m going to accidentally insult a stranger",
    "I avoid walking in the grass because I’m afraid of bugs",
    "I feel a sense of panic when the power goes out",
    "I worry that I’m going to lose my wallet",
    "I avoid wearing bright colors because I don’t want to be noticed",
    "I feel a surge of adrenaline when I see a police car",
    "I worry that I’m going to get sick on a plane",
    "I avoid going to the dentist because the vibration of the drill scares me",
    "I feel a constant sense of unease in my own home",
    "I worry that I’m going to accidentally say something stupid",
    "I avoid looking at myself in the mirror when I’m anxious",
    "I feel a sense of panic when I’m in a room with no windows",
    "I worry that I’m going to get lost in a new city",
    "I avoid talking to my neighbors because I don’t want to be trapped in a conversation",
    "I feel a constant need to check the weather forecast",
    "I worry that I’m going to forget something important",
    "I avoid going to the beach because the vastness of the ocean scares me",
    "I feel a surge of panic when I can’t find my phone",
    "I worry that I’m going to have a panic attack in front of my boss",
    "I avoid taking medication because I’m afraid of the side effects",
    "I feel a constant sense of pressure to be perfect",
    "I worry that I’m going to get a disease from touching a door handle",
    "I avoid going to the mall because it’s too loud and bright",
    "I feel a surge of adrenaline when I hear a loud bang",
    "I worry that I’m going to get into a car accident",
    "I avoid talking about my anxiety because I don’t want to be judged",
    "I feel a constant need to check my email",
    "I worry that I’m going to fail at everything I do",
    "I avoid going to parties because I don’t know what to say",
    "I feel a sense of panic when I’m in a crowded elevator",
    "I worry that I’m going to be late for an appointment",
    "I avoid taking the subway because it’s too dark and cramped",
    "I feel a constant sense of nervousness in my chest",
    "I worry that I’m going to lose my job",
    "I avoid going to new places because I’m afraid of the unknown",
    "I feel a surge of adrenaline when I hear a phone ring",
    "I worry that I’m going to be judged by my coworkers",
    "I avoid talking on the phone because it makes me nervous",
    "I feel a constant sense of worry about the future",
    "I worry that I’m going to make a mistake",
    "I avoid going to sleep because I’m afraid of having a nightmare",
    "I feel a sense of panic when I’m in a large crowd",
    "I worry that I’dot'm not good enough",
    "I avoid talking to strangers because it’s too stressful",
    "I feel a constant sense of anxiety about my health",
    "I worry that I’m going to be a burden to others",
    "I avoid going to the doctor because I’m afraid of what they’ll find",
    "I feel a surge of adrenaline when I see an ambulance",
    "I worry that I’m going to have a heart attack",
    "I avoid taking risks because I’m afraid of failing",
    "I feel a constant sense of unease in social situations",
    "I worry that I’m going to be laughed at",
    "I avoid going to work when I’m feeling anxious",
    "I feel a sense of panic when I’m in a small room",
    "I worry that I’m going to lose someone I love",
    "I avoid talking to my family about my anxiety",
    "I feel a constant sense of dread about the world",
    "I worry that I’m going to be alone forever",
    "I avoid going to school because it’s too stressful",
    "I feel a surge of adrenaline when I hear a loud noise",
    "I worry that I’m going to be a failure",
    "I avoid taking on new responsibilities because I’m afraid of failing",
    "I feel a constant sense of tension in my body",
    "I worry that I’m going to be criticized",
    "I avoid going out in public when it’s busy",
    "I feel a sense of panic when I’m in a situation I can’t control",
    "I worry that I’m going to be rejected",
    "I avoid talking to my friends about my anxiety",
    "I feel a constant sense of worry about my finances",
    "I worry that I’m going to be a disappointment",
    "I avoid taking the bus because it’s too crowded",
    "I feel a surge of adrenaline when I see a fire truck",
    "I worry that I’m going to be in a fire",
    "I avoid going to the store when it’s crowded",
    "I feel a constant sense of anxiety about my relationships",
    "I worry that I’m going to be judged by my friends",
    "I avoid talking to my boss about my anxiety",
    "I feel a sense of panic when I’m in a dark place",
    "I worry that I’m going to be in an earthquake",
    "I avoid taking the train because it’s too crowded",
    "I feel a constant sense of dread about the future",
    "I worry that I’m going to be in a flood",
    "I avoid going to the park when it’s crowded",
    "I feel a surge of adrenaline when I see a storm",
    "I worry that I’m going to be in a tornado",
    "I avoid taking the plane because it’s too high",
    "I feel a constant sense of worry about the past",
    "I worry that I’m going to be in a hurricane",
    "I avoid going to the museum when it’s crowded",
    "I feel a sense of panic when I’m in a place I don’t know",
    "I worry that I’m going to be in a tsunami",
    "I avoid taking the boat because it’s too deep",
    "I feel a constant sense of anxiety about the environment",
    "I worry that I’m going to be in a mudslide",
    "I avoid going to the library when it’s crowded",
    "I feel a surge of adrenaline when I see a forest fire",
    "I worry that I’m going to be in a volcanic eruption",
    "I avoid taking the helicopter because it’s too noisy",
    "I feel a constant sense of dread about the economy",
    "I worry that I’m going to be in a war",
    "I avoid going to the zoo when it’s crowded",
    "I feel a sense of panic when I’m in a place with no exit",
    "I worry that I’m going to be in a terrorist attack",
    "I avoid taking the car because it’s too dangerous",
    "I feel a constant sense of worry about politics",
    "I worry that I’m going to be in a protest",
    "I avoid going to the concert when it’s crowded",
    "I feel a surge of adrenaline when I see a crowd",
    "I worry that I’m going to be in a stampede",
    "I avoid taking the elevator because it’s too small",
    "I feel a constant sense of anxiety about the world’s end",
    "I worry that I’m going to be in a plague",
    "I avoid going to the hospital when it’s crowded",
    "I feel a sense of panic when I’m in a place with no air",
    "I worry that I’m going to be in a famine",
    "I avoid taking the stairs because it’s too high",
    "I feel a constant sense of dread about the afterlife",
    "I worry that I’m going to be in a void",
    "I avoid going to the cemetery because it’s too quiet",
    "I feel a surge of adrenaline when I see a ghost",
    "I worry that I’m going to be in a haunting",
    "I avoid taking the dark alley because it’s too dark",
    "I feel a constant sense of worry about death",
    "I worry that I’m going to be forgotten",
    "I avoid going to the funeral because it’s too sad",
    "I feel a sense of panic when I’m in a place with no light",
    "I worry that I’m going to be in a nightmare",
    "I avoid taking the medication because I’m afraid of the side effects",
    "I feel a constant sense of anxiety about my mind",
    "I worry that I’m going to lose my memory",
    "I avoid going to the psychiatrist because I’m afraid of what they’ll say",
    "I feel a surge of adrenaline when I hear a siren",
    "I worry that I’m going to be arrested",
    "I avoid taking the risk because I’m afraid of the consequences",
    "I feel a constant sense of unease in my own body",
    "I worry that I’m going to be exposed",
    "I avoid going to the meeting because I’m afraid of being called on",
    "I feel a sense of panic when I’m in a place I can’t leave",
    "I worry that I’m going to be trapped",
    "I avoid talking to my partner about my anxiety",
    "I feel a constant sense of dread about my life",
    "I worry that I’m going to be a burden",
    "I avoid going to the gym because I’m afraid of being judged",
    "I feel a surge of adrenaline when I see a needle",
    "I worry that I’m going to have a panic attack",
    "I avoid taking the lead because I’m afraid of making a mistake",
    "I feel a constant sense of tension in my neck",
    "I worry that I’m going to be misunderstood",
    "I avoid going out at night because I’m afraid of what might happen",
    "I feel a sense of panic when I’m in a situation I can’t escape",
    "I worry that I’m going to be a disappointment to my parents",
    "I avoid talking about my feelings because I’m afraid of being vulnerable",
    "I feel a constant sense of worry about my future career",
    "I worry that I’m going to be a failure in life",
    "I avoid taking the initiative because I’m afraid of being rejected",
    "I feel a surge of adrenaline when I see a social media notification",
    "I worry that I’m going to be canceled",
    "I avoid going to the party because I don’t know anyone there",
    "I feel a constant sense of anxiety about my appearance",
    "I worry that I’m going to be judged by my looks",
    "I avoid talking to new people because it’s too exhausting",
    "I feel a sense of panic when I’m in a place that is too loud",
    "I worry that I’m going to be overwhelmed",
    "I avoid taking on too much because I’m afraid of burning out",
    "I feel a constant sense of dread about my daily tasks",
    "I worry that I’m not going to be able to finish my work",
    "I avoid going to the grocery store when it’s busy because of the lines",
    "I feel a surge of adrenaline when I hear someone shout",
    "I worry that I’m going to be in an argument",
    "I avoid talking about my problems because I don’t want to be a bother",
    "I feel a constant sense of worry about my health insurance",
    "I worry that I’m going to get a medical bill I can’t pay",
    "I avoid going to the dentist because I’m afraid of the pain",
    "I feel a sense of panic when I’m in a place that is too bright",
    "I worry that I’m going to have a migraine",
    "I avoid taking the highway because it’s too fast for me",
    "I feel a constant sense of unease in public places",
    "I worry that I’m going to be in the middle of a scene",
    "I avoid talking to my coworkers because I don’t want to be distracted",
    "I feel a surge of adrenaline when I see a person in a uniform",
    "I worry that I’m going to be in trouble",
    "I avoid going to the mall because I’m afraid of being lost",
    "I feel a constant sense of anxiety about the security of my home",
    "I worry that I’m going to be robbed",
    "I avoid talking to my neighbors because I don’t want to be judged by them",
    "I feel a sense of panic when I’m in a place that is too quiet",
    "I worry that I’m going to be bored",
    "I avoid taking the stairs because I’m afraid of getting tired",
    "I feel a constant sense of dread about the aging process",
    "I worry that I’m going to be old and alone",
    "I avoid going to the theater because I’m afraid of the dark",
    "I feel a surge of adrenaline when I see a snake",
    "I worry that I’m going to be bitten",
    "I avoid taking the path in the woods because I’m afraid of getting lost",
    "I feel a constant sense of worry about the climate",
    "I worry that I’m going to be in a natural disaster",
    "I avoid going to the beach because I’m afraid of getting a sunburn",
    "I feel a sense of panic when I’m in a place that is too crowded",
    "I worry that I’m going to be crushed",
    "I avoid taking the bridge because I’m afraid of heights",
    "I feel a constant sense of unease in the dark",
    "I worry that I’m going to be in a car crash",
    "I avoid talking to people I don’t know because I don’t know what to say",
    "I feel a surge of adrenaline when I hear a dog bark",
    "I worry that I’m going to be attacked",
    "I avoid going to the city because it’s too loud and busy",
    "I feel a constant sense of anxiety about my ability to provide",
    "I worry that I’m going to be poor",
    "I avoid talking to my landlord because I’m afraid of being evicted",
    "I feel a sense of panic when I’m in a place with no window",
    "I worry that I’m going to be stuck in an elevator",
    "I avoid taking the bus at night because I’m afraid of being alone",
    "I feel a constant sense of dread about my mortality",
    "I worry that I’m going to die and no one will care",
    "I avoid going to the hospital because I’m afraid of being sick",
    "I feel a surge of adrenaline when I see a person I don’t like",
    "I worry that I’m going to be in a confrontation",
    "I avoid talking about politics because I don’t want to be in an argument",
    "I feel a constant sense of worry about the world my kids will live in",
    "I worry that I’m going to be a bad parent",
    "I avoid going to school meetings because I’m afraid of being judged by other parents",
    "I feel a sense of panic when I’m in a place that is too open",
    "I worry that I’m going to be exposed to the elements",
    "I avoid taking the plane because I’m afraid of it crashing",
    "I feel a constant sense of unease when I’m in a new environment",
    "I worry that I’m going to make a fool of myself",
    "I avoid talking to my friends about my anxiety because I don’t want them to worry",
    "I feel a surge of adrenaline when I see a bill in the mail",
    "I worry that I’m going to run out of money",
    "I avoid going to the store because I’m afraid of overspending",
    "I feel a constant sense of anxiety about my performance at work",
    "I worry that I’m going to be fired for being too anxious",
    "I avoid talking to my boss about my anxiety because I don’t want them to think I’m weak",
    "I feel a sense of panic when I’m in a place that is too silent",
    "I worry that I’m going to be left with my own thoughts",
    "I avoid taking the train because I’m afraid of being stuck between stations",
    "I feel a constant sense of dread about the next panic attack",
    "I worry that I’m never going to feel normal again",
    "I can not stop worrying about things that have not happened yet and may never happen",
    "my mind is constantly racing with worst case scenarios about the future",
    "I worry obsessively about bad things happening to people I love all day long",
    "the anticipatory anxiety about future events keeps me awake every single night",
    "I am always expecting something terrible to happen even when everything is calm",
    "I can not stop my brain from catastrophizing every single situation I encounter",
    "the constant worrying is exhausting me but I can not turn it off no matter what",
    "I feel a persistent sense of dread about the future that never goes away",
    "I worry about everything all the time even things that are completely out of my control",
    "my anxiety makes me imagine the absolute worst outcome for every single situation",
    "I am paralyzed by worry about things that probably will never actually happen",
    "the fear of something going wrong keeps me from enjoying anything in the present",
    "I can not relax because my brain is always scanning for potential threats and dangers",
    "I worry that something bad is going to happen to my family every time they leave",
    "the constant state of worry and fear is making it impossible to function normally",
    "I overthink every single interaction and replay conversations for hours afterward",
    "I am consumed by worry about my health even though all my tests come back normal",
    "I feel like I am always waiting for disaster to strike and I can never let my guard down",
    "the anxiety about future events makes me physically sick with nausea and trembling",
    "I can not enjoy good moments because I am too busy worrying about what comes next",
    "I have racing anxious thoughts about potential dangers that keep me frozen in fear",
    "my constant worry about everything is not a mood swing it is a permanent state of fear",
    "I feel terrified of the unknown and I avoid new situations because of the anxiety",
    "the worry is like a broken record in my head playing the same fears over and over",
    "I can not make decisions because I am too afraid of choosing the wrong thing",
    "I feel a constant knot of anxiety in my stomach that has been there for months",
    "my worrying is not about mood changes it is about constant unrelenting fear of danger",
    "I am exhausted from the non stop cycle of worry and fear that dominates my thoughts",
    "I feel like my anxiety controls every aspect of my life and I can not escape it",
    "the physical symptoms of my constant worrying are ruining my quality of life",
    "my heart races uncontrollably before every single meeting at work",
    "I get heart palpitations and sweaty palms before every work presentation",
    "my heart starts pounding the moment I see a meeting invite in my calendar",
    "I feel my pulse racing and my hands trembling before every team meeting",
    "my heart beats so fast before meetings that I feel like I might pass out",
    "every time I have to speak in a meeting my heart rate goes through the roof",
    "I get such intense heart racing before presentations that I feel dizzy",
    "my heart pounds and my voice shakes whenever I have to speak up at work",
    "the physical anxiety symptoms before meetings are ruining my work life",
    "I feel my heart hammering in my chest every time my boss calls a meeting",
    "my anxiety causes my heart to race so fast before interviews I can barely talk",
    "I get intense palpitations and shortness of breath before every social event",
    "my heart races and my stomach drops every time I get a notification at work",
    "the physical anxiety I feel before any social interaction is debilitating",
    "my heart pounds so hard during presentations that I can hear it in my ears",
    "I feel my heart racing every morning before work because of anticipatory anxiety",
    "my anxiety makes my heart race even when I am just thinking about future events",
    "I get chest tightness and rapid heartbeat every time I have to meet new people",
    "the heart racing and sweating before every social event makes me avoid them",
    "my heart starts pounding the second I walk into a crowded room full of people",
    "I can not stop worrying about bad things that have not even happened yet",
    "I worry constantly about future disasters that will probably never occur",
    "my mind keeps worrying about what if scenarios that have not happened",
    "I can not stop my brain from worrying about things that might go wrong",
    "the worrying about future problems that do not exist yet is exhausting me",
    "I spend all day worrying about hypothetical bad outcomes that never come true",
    "I can not stop obsessing over things that have not happened and may never happen",
    "my anxiety makes me worry nonstop about potential future catastrophes",
    "I keep worrying about worst case scenarios that are extremely unlikely",
    "the constant worrying about things that have not occurred is paralyzing me",
    "I worry about things going wrong in the future even when everything is fine now",
    "my brain will not stop worrying about dangers and threats that do not exist yet",
    "I am consumed by worry about future events that have not taken place",
    "I can not control my worrying about things that probably will never happen",
    "the anticipatory worry about future problems keeps me trapped in fear all day"
]