BIPOLAR = [
    "I cycle between feeling invincible and then completely worthless",
    "I spent thousands of dollars in a weekend and now regret it",
    "I barely slept for three days and felt amazing until I crashed",
    "My energy swings wildly from too much to barely any",
    "I feel euphoric and untouchable then suddenly suicidal",
    "During my highs I make reckless decisions I later regret",
    "I've had periods where I barely needed sleep and felt superhuman",
    "My moods shift so fast it confuses everyone around me",
    "I started five projects during my manic phase and finished none",
    "I was extremely irritable and snappy for no obvious reason",
    "I went on a shopping spree during my high and maxed out my credit card",
    "I feel grandiose sometimes like I have special abilities",
    "My lows are devastating and my highs scare me",
    "I talk so fast during my highs that people can't follow me",
    "I've been hospitalized twice for manic episodes",
    "My thoughts race so fast I can't catch them during a high",
    "I feel like two different people depending on which phase I'm in",
    "I engaged in risky sexual behavior during my last manic episode",
    "The highs feel incredible but the crashes are catastrophic",
    "I was diagnosed with bipolar disorder and I'm struggling to accept it",
    "I drive dangerously fast when I'm manic",
    "I feel like I can conquer the world and then hit rock bottom",
    "My relationships suffer because my behavior is so unpredictable",
    "My manic phases leave me with regrets and my depressive phases with despair",
    "I go from laughing hysterically to crying in the space of an hour",
    "I've quit my job impulsively during a manic phase before",
    "I feel a false sense of confidence during highs that leads to bad choices",
    "My energy level fluctuates so dramatically it's hard to plan anything",
    "During depressive phases I can't get out of bed and during highs I can't sit still",
    "I've been told I become a different person when I'm manic",
    "I have extreme mood swings that disrupt my daily life",
    "I was irritable and agitated for days then suddenly crashed into depression",
    "I feel elated and powerful then the crash hits and I want to die",
    "My spending habits during manic phases have caused major problems",
    "I can't maintain friendships because of how unpredictable my moods are",
    "I have trouble sleeping during mania which makes the phase worse",
    "I feel all-powerful during highs and utterly useless during lows",
    "My mood episodes have caused me to lose jobs and relationships",
    "I've been impulsive with alcohol during elevated moods",
    "The mixed states are the worst when I'm energized but miserable",
    "I feel my mood cycling and I can't control it",
    "My thoughts during mania are so loud and fast it feels like chaos",
    "I was on a high for two weeks and then fell into deep depression",
    "I have rapid cycling episodes that make me exhausted",
    "I feel like I'm on a rollercoaster I can't get off",
    "I made a major life decision impulsively during a manic phase",
    "During a manic phase I feel like I don't need food or rest",
    "My partner says they never know which version of me they'll get",
    "I have grandiose ideas when I'm manic that seem delusional in retrospect",
    "The depression after a manic high is like falling off a cliff",
    "I feel like my brain is broken because it swings so violently",
    "I took out a loan impulsively during my last high",
    "My moods are extreme and I struggle to regulate them",
    "I feel superhuman during my manic phase until it collapses",
    "I was irritable and combative for days which isn't my baseline",
    "My mania makes me feel creative and brilliant but leads to chaos",
    "I go from not sleeping to sleeping 15 hours a day cyclically",
    "I've hurt people I love when manic and I regret it deeply",
    "My mood disorder makes it hard to live a stable life",
    "one week i feel like a genius the next i cant get off the couch",
    "i maxed out three credit cards during my last manic episode",
    "my mood swings from extreme happiness to wanting to die within hours",
    "i stayed awake for four days straight during a high and felt incredible",
    "i signed up for a marathon bought a guitar and quit my job all in one week",
    "the mania convinces me i dont need my medication then i crash hard",
    "i feel like i have superpowers during highs and then reality crashes in",
    "my psychiatrist adjusted my lithium again because the cycling wont stop",
    "i oscillate between grandiosity and complete self loathing",
    "during manic phases i become hypersexual and make terrible decisions",
    "my family walks on eggshells because they never know my mood",
    "i spent my entire savings on a business idea during a manic high",
    "the depressive episodes after mania feel ten times worse than regular depression",
    "i go from writing a novel in three days to being unable to form sentences",
    "i picked fights with everyone during my last irritable manic episode",
    "my mood shifts are so extreme they feel like different mental illnesses",
    "i feel wired and electric during highs but it always ends in a crash",
    "i made promises during mania that i couldnt keep during depression",
    "my bipolar cycling has destroyed every long term relationship ive had",
    "i feel invincible and then the depression reminds me im not",
    "during my highs i talk nonstop and cant slow my brain down",
    "i have been through multiple medication changes for bipolar disorder",
    "one minute i am planning world domination the next i cant shower",
    "my impulsive spending during mania put me into serious debt",
    "i get paranoid and suspicious during mixed episodes",
    "the rapid cycling between euphoria and despair is exhausting",
    "i started a business during mania and abandoned it during depression",
    "my energy goes from limitless to completely depleted in a matter of days",
    "i feel like two completely different people living in one body",
    "during my last manic episode i believed i could communicate with god",
    "the mood swings make it impossible to hold down a steady job",
    "i alternate between sleeping two hours and sleeping sixteen hours",
    "my racing thoughts during mania keep me from sitting still for even a minute",
    "i drank heavily during a manic phase and woke up in a hospital",
    "i feel brilliant and unstoppable then absolutely crushed by reality",
    "i bipolar disorder makes me unreliable and it ruins everything",
    "i swung from euphoria to suicidal despair in the same afternoon",
    "i cant trust my own judgment because mania distorts my thinking",
    "i booked a spontaneous trip across the country during a high and regretted it",
    "the depressive lows after manic highs feel like emotional whiplash",
    "i feel like my emotions have no middle ground its always extremes",
    "during mania i feel so creative but nothing i create makes sense later",
    "i got into a physical altercation during an irritable manic state",
    "my sleep patterns are wildly inconsistent because of cycling moods",
    "i feel trapped between two poles of my disorder with no stability",
    "during highs i give away money and possessions recklessly",
    "i have been committed involuntarily during a severe manic episode",
    "my mood chart looks like a seismograph with constant wild swings",
    "i feel like mania lies to me telling me everything is perfect when its not",
    "the contrast between my highs and lows is staggering and frightening",
    "i alienated my closest friends during a prolonged manic phase",
    "my bipolar makes me feel like i am living multiple lives at once",
    "i went from being the life of the party to being bedridden in two days",
    "i feel electrically charged during mania but it burns me out completely",
    "my medication barely controls the cycling and i still swing violently",
    "i feel the mania building and i know the crash is coming but i cant stop it",
    "during mixed episodes i feel energized and suicidal at the same time",
    "i have cycled between highs and lows my entire adult life",
    "i feel like my brain is a pendulum that never finds center",
    "my hypomanic episodes trick me into thinking i am cured then depression hits",
    "i cant plan anything because i never know what state i will be in",
    "i feel like i am at war with my own brain constantly",
    "my mood cycles have gotten shorter and more intense over the years",
    "i went on a gambling binge during mania and lost everything",
    "i feel like a different species during mania compared to depression",
    "the instability of my moods makes me feel fundamentally broken",
    "i wish i could just be stable for one month without cycling",
    "i feel terrified of my own manic episodes because of what i might do",
    "during depression i forget how mania felt and during mania i forget the lows",
    "my bipolar disorder is the hardest thing i have ever had to manage",
    "my mood changes so much it feels like im a different person",
    "sometimes my mood is so good and other times its so sour",
    "bro i was literally planning to start a company yesterday and today i cant shower",
    "the mania hit so hard i spent half my rent on clothes i dont need",
    "went from god complex to literally wanting to die in less than 48 hours",
    "my brain is going 1000 miles an hour and i havent slept since tuesday",
    "i swear im two completely different people and neither of them is stable",
    "the hyperfixation during mania is insane i literally started painting my room at 3am",
    "the crash after the high is actually the worst feeling in the world",
    "my mood swings give me actual whiplash im so exhausted",
    "i texted literally everyone in my contacts last night and now im so embarrassed",
    "i feel like im vibrating on a different frequency when the mania hits",
    "went from feeling literally untouchable to sobbing on the floor",
    "the rapid cycling is ruining my life i cant keep a routine",
    "i convinced myself i could cure my own illness during a manic episode",
    "i literally ghosted my entire friend group because the depression hit so fast",
    "my energy levels go from 0 to 100 back to 0 with zero warning",
    "the grandiosity is so real i actually thought i was the smartest person alive",
    "i feel like i have superpowers until the depression kicks in",
    "i made so many plans while manic and now i have to cancel all of them",
    "the mixed episodes are the worst because im exhausted but i cant sleep",
    "my meds make me feel stable but i lowkey miss the manic highs sometimes",
    "i talk so fast when im up that nobody can even understand me",
    "i literally maxed out my credit card on a hyperfixation hobby i already abandoned",
    "my partner is so tired of the mood swings and honestly so am i",
    "i feel like a pendulum just swinging wildly between two extremes",
    "i go from needing zero sleep to sleeping 14 hours a day",
    "i literally picked fights with everyone yesterday for no reason",
    "i got so manic i reorganized my entire apartment in the middle of the night",
    "im so paranoid during the highs i think everyone is watching me",
    "my brain is so loud during mania i just want it to stop",
    "the emotional rollercoaster is actually making me physically sick",
    "I was employee of the month during my high and got fired for absenteeism during my low",
    "I signed up for four extra courses and had to withdraw from all of them",
    "I feel like a genius at work for a week and then I can't even process a simple email",
    "My resume is a graveyard of short-lived jobs because of my cycling moods",
    "I'm terrified of my boss finding out why my productivity swings so violently",
    "I pitched a massive project during mania that I have no idea how to execute now",
    "I stay at the office until midnight when I'm up, then I don't show up for three days",
    "I feel like I'm constantly doing damage control for my manic self at work",
    "I've quit more jobs impulsively than I've actually completed",
    "My coworkers think I'm eccentric but I'm actually just struggling to stay stable",
    "The lithium tremor makes it hard to write but at least the cycling has slowed down",
    "I hate how the meds make me feel like a zombie but the highs were too dangerous",
    "I stopped taking my mood stabilizers because I thought I finally beat the disorder",
    "Every time I feel a little bit happy, I panic and think a manic episode is starting",
    "My blood work came back with high lithium levels and now I have to adjust everything",
    "I've tried six different antipsychotics and none of them seem to stick",
    "The weight gain from my meds makes me depressed, which triggers my cycling",
    "I feel like a science experiment with all these different pill combinations",
    "My psychiatrist says I'm rapid cycling and we need to change my entire protocol",
    "I miss the color of the world during mania, but I know the gray of the meds is safer",
    "I don't get manic in the way people think; I just get incredibly sharp and irritable",
    "My hypomania feels like a superpower until I realize I haven't eaten in two days",
    "I spent all night researching a niche historical topic and now I'm an expert",
    "People think I'm just a high-achiever, but I'm actually in a hypomanic state",
    "I'm not crazy, I'm just vibrating at a frequency nobody else can hear",
    "I cleaned the entire house with a toothbrush at 4 AM and felt totally normal",
    "I have these bright periods where I feel like I finally figured out the secret to life",
    "Hypomania is deceptive because it feels like I'm finally fixed until the floor drops out",
    "I get so creative that I can't sleep because the ideas are literally keeping me awake",
    "My hypomanic episodes are mostly just 48 hours of intense, productive rage",
    "My kids are scared when I'm too happy because they know the angry phase is next",
    "I apologized to my partner for the tenth time this week for my erratic behavior",
    "I've burned bridges with every friend I had in my 20s during various episodes",
    "My family has a plan for when I start talking too fast, and I hate it",
    "I'm the fun friend until I'm the scary friend or the sad friend",
    "I can't tell if my personality is actually me or just a symptom of my disorder",
    "I feel like I'm constantly apologizing for things I don't even remember doing",
    "My parents still manage my finances because they don't trust me after the last spree",
    "I ghosted my siblings for six months and now I don't know how to go back",
    "Relationships feel impossible when you're a different person every three months",
    "The silence of depression is only broken by the roar of the next high",
    "I feel like I'm living my life on a 2x speed setting",
    "My credit score is a direct reflection of my mental health history",
    "I have three different wardrobes for the three different people I become",
    "I feel like I'm walking on a tightrope over a canyon of despair",
    "The irritability of a mixed state feels like having bees under my skin",
    "I started a garden, a podcast, and a fitness regime today. Send help.",
    "I'm so tired of the up and down—I just want middle",
    "My brain is a high-speed train with no brakes and the tracks are ending",
    "I go from feeling like a god to feeling like a parasite in 24 hours",
    "The grandiosity tells me I'm the only one who sees the truth",
    "I haven't slept in 40 hours and I feel like I could run a marathon",
    "My bank account is empty but my heart is racing with possibility",
    "I feel like I'm trapped in a cycle that I'm doomed to repeat forever",
    "The mixed episode is the most dangerous because I have the energy to act on my sadness",
    "I feel like my life is just a series of before and after episodes",
    "I'm so hyper-focused on this new hobby that I've forgotten to go to work",
    "The crash isn't just sadness; it's a physical weight that prevents movement",
    "I've been up for a week and I can feel the darkness creeping in at the edges",
    "I spent my rent money on a flight to a city where I don't know anyone",
    "I feel like a firework—bright and exciting until I'm just ash on the ground",
    "My thoughts are overlapping like too many browser tabs open at once",
    "I am currently in the unfathomable sadness phase of the program",
    "I feel like I am made of electricity during the manic peaks",
    "I have had to block my own access to Amazon so I don't buy a boat again",
    "My mood episodes are like seasons, but they change without warning",
    "I'm so talkative that I'm literally exhausting the people around me",
    "The impulsivity is like a voice in my head that I can't say no to",
    "I feel like I'm finally awake when I'm manic, and asleep when I'm stable",
    "My bipolar disorder is a full-time job that I never applied for",
    "I went from I love everyone to I hate everyone in six seconds",
    "The racing thoughts make it impossible to watch a whole YouTube video",
    "I feel like I am vibrating out of my own skin today",
    "I have lost the ability to tell what a normal emotion even looks like",
    "My manic self made a lot of promises that my depressed self has to break",
    "I am in a mixed state: I want to die, but I have the energy to clean the house",
    "I feel like a puppet and my moods are the ones pulling the strings",
    "The euphoric high is the most addictive drug I've ever tasted",
    "I have spent the last three days staring at the ceiling after a month of winning",
    "I am terrified of my own brain and what it is capable of doing to me",
    "My bipolar makes me feel like I am a passenger in my own body",
    "I feel like a genius when I am high and a moron when I am low",
    "The instability is the only thing that is consistent in my life",
    "I go from being the life of the party to the person hiding in the bathroom",
    "I have destroyed my credit, my career, and my marriage in one single year",
    "The mood swings are so fast I feel like I have multiple personalities",
    "I am so tired of the medication carousel—none of it works perfectly",
    "I feel like my life is a series of catastrophic errors punctuated by magic",
    "The depressive phase feels like being buried alive in slow motion",
    "I am currently low and I don't think I will ever be up again",
    "My brain feels like it is being over-clocked and it is about to burn out",
    "I have started ten new hobbies this month and I will finish zero of them",
    "The irritability makes me want to scream at everyone who looks at me",
    "I am so grandiose right now that I think I should be the CEO",
    "I feel like the world is moving too slow for my brain today",
    "The crash after a two-week high is a physical pain in my chest",
    "I have alienated everyone who ever cared about me with my outbursts",
    "My bipolar is a rollercoaster and I am ready to get off now",
    "I feel like I am walking through a dream when I am manic",
    "The darkness of the low is so thick I can not breathe",
    "I am so impulsive I bought a motorcycle without having a license",
    "My moods are like the weather in a place where it is never 70 degrees",
    "I feel like I am a different species than the stable people",
    "The rapid cycling is giving me actual physical vertigo",
    "I am so tired of the check-ins from people who think I am going to snap",
    "I feel like my brain is a radio that is stuck between two stations",
    "The hypersexuality during mania makes me feel like a stranger to myself",
    "I have lost my house, my car, and my pride to this disorder",
    "I am currently in the god complex phase and it feels amazing and scary",
    "The depression is the price I pay for the manic high",
    "I am so tired of being the person everyone has to worry about",
    "I feel like my life is a movie that is being played at the wrong speed",
    "The racing thoughts are so fast they are actually painful",
    "I have made so many mistakes that I don't think I can ever fix them",
    "I am so unstable that I can not even trust my own memories",
    "I feel like I am drowning in the highs and the lows simultaneously",
    "The mood stabilizers make me feel like I am living in a fog",
    "I am so impulsive I quit my job because I didn't like the coffee",
    "My brain is a playground for demons and angels and they are at war",
    "I am currently high and I feel like I am made of pure light",
    "The mania is a liar and the depression is a thief",
    "I feel like I am just a collection of symptoms in a trench coat",
    "The instability is ruining my life and I can not stop it",
    "I am so tired of the cycle—I just want to be boring for once",
    "My bipolar disorder is a curse and a gift and a death sentence",
    "I feel like I am vibrating at a frequency that is breaking my bones",
    "The racing thoughts are like a thousand voices all screaming at once",
    "I have spent my life trying to find the middle and failing",
    "I am currently low and I have forgotten what the sun feels like",
    "The crash is coming and I am already grieving the person I am right now",
    "My moods are so extreme they don't even feel like human emotions",
    "I am so tired of being the person who can not be counted on",
    "I feel like my brain is a puzzle with pieces that don't fit",
    "The mania makes me feel like I can see the future",
    "The depression makes me feel like there is no future",
    "I am so impulsive I tattooed my own arm at 2 AM",
    "My bipolar disorder is a secret I have to keep from everyone I meet",
    "I feel like I am just a ghost haunting the person I used to be",
    "The mood swings are so violent they leave me physically bruised",
    "I am so tired of the how are you feeling questions",
    "I feel like my brain is a storm and I am just the umbrella",
    "The grandiosity is so thick I could choke on it",
    "The depression is so heavy I can not lift my own arms",
    "I am so impulsive I spent my kids college fund on a sure thing",
    "My bipolar disorder is a thief that stole my entire life",
    "I feel like I am just a passenger on a plane that is crashing",
    "The racing thoughts are so loud I can not hear my own voice",
    "I am currently up and I feel like I am the smartest person on earth",
    "The crash is going to kill me one of these days, I know it",
    "My moods are like a tide that never stays out or comes in",
    "I am so tired of the lithium fog but I am more tired of the madness",
    "I feel like my brain is a war zone and I am the only civilian",
    "The mania is a drug and I am the biggest addict",
    "The depression is a prison and I am the only inmate",
    "I am so impulsive I moved to a new country without a plan",
    "My bipolar disorder is the only thing I can rely on to stay the same",
    "I feel like I am just a collection of bad decisions and chemicals",
    "The racing thoughts are like a swarm of bees in my skull",
    "The mania makes me feel like I am the protagonist of the world",
    "The depression makes me feel like I am a background extra in a tragedy",
    "I am so tired of the cycle—I just want to be fine",
    "My brain is a broken record that only plays two songs",
    "I feel like I am made of glass in a world made of hammers",
    "The grandiosity is the only thing that keeps me alive sometimes",
    "The depression is the only thing that is truly honest with me",
    "I am so impulsive I told my boss what I really think of him",
    "My bipolar disorder is a ghost that won't leave me alone",
    "I feel like I am just a shadow of the person I was supposed to be",
    "The mood swings are so fast they are giving me emotional vertigo",
    "I am so tired of the bipolar label—I am just a person who is tired",
    "I feel like my brain is a kaleidoscope that has been smashed",
    "The racing thoughts are like a neon sign that won't stop flickering",
    "I am currently up and I feel like I am finally living",
    "The crash is coming and I am already saying my goodbyes",
    "My moods are like a broken compass—they never point North",
    "I am so tired of the meds—they have taken my soul and left the symptoms",
    "I feel like my brain is a house that is always on fire",
    "The mania is a miracle and the depression is a crime",
    "I am so impulsive I bought a purebred dog I can't afford to feed",
    "My bipolar disorder is a riddle I will never be able to solve",
    "I feel like I am just a ghost in a machine that is malfunctioning",
    "The racing thoughts are like a waterfall of static",
    "I am currently low and I have lost the ability to speak",
    "The mania makes me feel like I am the only one who is actually awake",
    "The depression makes me feel like I am already in the grave",
    "I am so tired of the ups and downs—I just want the flats",
    "My brain is a map where all the roads lead to the same two places",
    "I feel like I am made of lead when the low hits",
    "The grandiosity is like a fever that won't break",
    "The depression is like a winter that never ends",
    "I am so impulsive I proposed to a person I have known for three weeks",
    "My bipolar disorder is a shadow that is bigger than I am",
    "I feel like I am just a memory of a person who used to be happy",
    "The mood swings are like a storm that never runs out of rain",
    "I am so tired of being brave—I just want to be stable",
    "I feel like my brain is a library where all the books are on fire",
    "The racing thoughts are like a thousand TV channels on at once",
    "I am currently high and I feel like I am dancing on the edge of the world",
    "The crash is going to be the end of me, I can feel it in my bones",
    "My moods are like a pendulum that is swinging too far in both directions",
    "I am so tired of the lithium—it makes me feel like I am made of plastic",
    "I feel like my brain is a computer that has caught a virus",
    "The mania is a beautiful lie and the depression is an ugly truth",
    "I am so impulsive I spent my life savings on a vision I had at 3 AM",
    "My bipolar disorder is a cage and the door is only open when I am manic",
    "I feel like I am just a passenger on a bus with no driver",
    "The racing thoughts are like a swarm of locusts in my mind",
    "I am currently low and I can not even remember what happy feels like",
    "The mania makes me feel like I am the king of the world",
    "The depression makes me feel like I am the dirt under the king’s feet",
    "I am so tired of the cycle—I just want to be boring",
    "My brain is a broken clock that is right twice a day",
    "I feel like I am made of mercury—impossible to catch or hold",
    "The grandiosity is like a drug that I can not stop taking",
    "The depression is like a poison that I can not stop drinking",
    "I am so impulsive I quit my life and moved to a farm",
    "My bipolar disorder is a haunting that never stops",
    "I feel like I am just a shadow of a shadow",
    "The mood swings are like a roller coaster with no seatbelts",
    "I am so tired of the medication—it is just a bandage on a bullet wound",
    "I feel like my brain is a storm that never runs out of lightning",
    "The racing thoughts are like a million sparks in a dark room",
    "I am currently up and I feel like I am finally myself",
    "The crash is coming and I am already mourning my life",
    "My moods are like a sea that is always in a state of gale force",
    "I am so tired of the bipolar label—it is a life sentence",
    "I feel like my brain is a puzzle that is missing half the pieces",
    "The mania is a vision and the depression is a blindness",
    "I am so impulsive I married my first manic love",
    "My bipolar disorder is a ghost that has lived in my house for years",
    "I feel like I am just a memory of a person who used to have potential",
    "The mood swings are like a fire that won't go out",
    "I am so tired of being strong—I just want to be okay",
    "I feel like my brain is a radio that only has two volumes: off and 11",
    "The racing thoughts are like a waterfall of fire",
    "I am currently high and I feel like I am made of stars",
    "The crash is going to be the death of me, I know it",
    "My moods are like a pendulum that is trying to break its own chain",
    "I am so tired of the lithium—it has made me into a statue",
    "I feel like my brain is a city that is always under siege",
    "The mania is a heaven that leads to a hell",
    "I am so impulsive I gave away my car to a worthy cause",
    "My bipolar disorder is a secret that is eating me alive",
    "I feel like I am just a ghost in a world that has moved on",
    "The racing thoughts are like a million screaming birds",
    "I am currently low and I don't think I will ever speak again",
    "The mania makes me feel like I am the only one who is real",
    "The depression makes me feel like I am the only one who is fake",
    "I am so tired of the ups—the downs are too expensive",
    "My brain is a map where all the destinations are the same two hells",
    "I feel like I am made of stone when the depression hits",
    "The grandiosity is like a crown that is made of thorns",
    "The depression is like a grave that is still being dug",
    "I am so impulsive I burned all my bridges because they looked pretty",
    "My bipolar disorder is a story that only has two chapters",
    "I feel like I am just a shadow of a person who once had a life",
    "The mood swings are like a tide that is always too high or too low",
    "I am so tired of managing—I just want to live",
    "I feel like my brain is a house where the lights are always flickering",
    "The racing thoughts are like a swarm of bees that never sleep",
    "I am currently up and I feel like I am finally on",
    "The crash is coming and I am already hiding from it",
    "My moods are like a rollercoaster that is missing a track",
    "I am so tired of the meds—they have replaced my soul with stability",
    "I feel like my brain is a war that nobody is winning",
    "The mania is a miracle that I don't deserve",
    "The depression is a punishment for a crime I didn't commit",
    "I am so impulsive I started a cult and then forgot about it",
    "My bipolar disorder is a haunting that I can not exorcise",
    "I feel like I am just a memory of a person who used to be me",
    "The mood swings are like a fire that is always out of control",
    "I am so tired of the label—it is a brand that won't fade",
    "I feel like my brain is a computer that is always crashing",
    "The racing thoughts are like a million sparks in a forest",
    "I am currently low and I have lost my voice",
    "The mania makes me feel like I am the only one who can see",
    "The depression makes me feel like I am the only one who can feel",
    "I am so tired of the cycle—it is a wheel that won't stop turning",
    "My brain is a broken record that is stuck on the loudest songs",
    "I feel like I am made of air and lead at the same time",
    "The grandiosity is a fever that I never want to break",
    "The depression is a winter that I will never survive",
    "I am so impulsive I gave away my life to a stranger",
    "My bipolar disorder is a shadow that is always behind me",
    "I feel like I am just a ghost of a person who used to have dreams",
    "The mood swings are like a storm that is always about to break",
    "I am so tired of the fight—I just want the peace",
    "I feel like my brain is a library that has been looted",
    "The racing thoughts are like a thousand neon signs",
    "I am currently up and I feel like I am the sun",
    "The crash is coming and I am already preparing for the dark",
    "My moods are like a pendulum that is swinging into the abyss",
    "I am so tired of the lithium—it made my world into black and white",
    "I feel like my brain is a city that has been abandoned",
    "The mania is a high that is always followed by a fall",
    "I am so impulsive I ruined my life in a weekend",
    "My bipolar disorder is a secret that everyone knows anyway",
    "I feel like I am just a memory of a person who used to be bright",
    "The mood swings are like a fire that is burning down my house",
    "I am so tired of being bipolar—I just want to be normal",
    "I feel like my brain is a puzzle that can not be solved",
    "The racing thoughts are like a swarm of static and fire",
    "I am currently low and I don't think I will ever be up again",
    "The mania is a drug that is killing me",
    "The depression is a cell that is trapping me",
    "I am so impulsive I gave up everything for nothing",
    "My bipolar disorder is a haunting that is always there",
    "I feel like I am just a ghost of a person who used to have a soul",
    "My psychiatrist says I have Type 1 but it feels like a life sentence",
    "The pharmacist knows me by name because of how often my cocktail changes",
    "I have to carry a medical ID card because my mania looks like an overdose",
    "I was misdiagnosed with depression for years before the first manic snap",
    "The black box warning on my meds is the only thing that stops me",
    "I have a safety contract with my therapist that I sign every time I crash",
    "The lithium toxicity scare last year made me want to quit all treatment",
    "I spend half my income on therapy and the other half on manic sprees",
    "My medical records are three inches thick with mood charting logs",
    "I am exhausted but my brain is screaming to run a marathon at 3 AM",
    "The mixed episode is hell: I am suicidal but have the energy to act",
    "I feel an itchy, restless energy in my bones while my mind is dark",
    "I am pacing the floor crying because I am too energized to sit still",
    "Mixed states make me feel like a live wire dropped into a pool",
    "I am snapping at everyone because my skin feels three sizes too small",
    "I have the manic speed but the depressive content in my thoughts",
    "I feel like I am exploding from the inside out with nervous energy",
    "My brain is a beehive and every single bee is angry and depressed",
    "I want to sleep for a thousand years but my heart is racing",
    "I have a permanent no-contact order because of a manic outburst",
    "I have had to explain my erratic behavior to a judge many times",
    "I lost my house because I thought I could live off the grid while high",
    "My family has power of attorney because they don't trust my spending",
    "I woke up in a different state with no memory of how I got there",
    "I have been banned from my local casino because of how I act when up",
    "The police were called for a wellness check and I ended up in the ward",
    "I have lost custody of my kids twice because of the instability",
    "I have a trail of broken leases and abandoned apartments in my wake",
    "I am the person in the neighborhood everyone whispers about during highs",
    "I don't know where the bipolar ends and I begin anymore",
    "I am terrified of my own happiness because I am waiting for the glitch",
    "I have not felt a normal emotion in so long I have forgotten the feeling",
    "My personality feels like a costume that I change without consent",
    "I am a passenger in a car driven by a lunatic changing speeds",
    "I have stopped telling people my diagnosis because they see a ticking bomb",
    "I am constantly cleaning up the wreckage left by the other version of me",
    "My life is a series of apology tours for things I did when not in my mind",
    "I am so tired of being resilient—I just want to be stable and boring",
    "I look at my bank account and see fingerprints of a person I don't know",
    "The sky is too blue and the lights are too bright and I hear the sun",
    "I wrote a fifty-page manifesto last night and today I can't read it",
    "I feel like the only person who understands how the universe works",
    "The depression after the genius phase makes me feel hollow",
    "I am vibrating so hard with energy that I might actually disappear",
    "I told my parents I was the reincarnation of a famous poet",
    "The hypersexuality makes me act like a person with no boundaries",
    "I am so irritable that the sound of breathing makes me want to scream",
    "I feel like I have been plugged into a wall socket with no off switch",
    "My life is a pendulum and it is currently swinging into the dark",
    "I am so high right now that I think I can fly and that is scary",
    "The darkness is not just a mood; it is a physical weight crushing me",
    "I spent four hours staring at a wall because the up finally ran out",
    "I am the life of the party until I am sobbing in the driveway",
    "I feel like my brain is a radio stuck on pure white noise",
    "I have burned every bridge I ever built and now I am on an island",
    "The manic version of me is a stranger I am forced to live with",
    "I feel like I am made of lead and drowning in a pool of my own making",
    "The racing thoughts are like a deck of cards being shuffled by a giant",
    "I am currently up and I am never coming back down—I solved it all",
    "The crash is a physical pain that starts in my head and ends in my feet",
    "I have lost my job and my dignity but at least I was creative for a week",
    "I feel like my brain is a house that has been hit by a hurricane",
    "The lithium fog is the only thing between me and the abyss",
    "I am so tired of the ups—the downs are too expensive to pay for",
    "I feel like a ghost in my own life watching the cycles happen to others",
    "The grandiosity is a liar but the depression is a thief of time",
    "I am so impulsive I bought a plane ticket to a country I can not name",
    "My bipolar disorder is a haunting even when I am stable",
    "I feel like a collection of symptoms pretending to be a human",
    "The racing thoughts are a carousel I can not jump off without injury",
    "I am currently in a mixed episode: energized and truly dangerous",
    "My bipolar is a storm and I am the only one without a shelter",
    "I have spent a lifetime building things just to tear them down",
    "I feel like the world is too loud, too bright, and too fast today",
    "The stability of the medication feels like a slow death of my soul",
    "I am trapped between the sky and the ground with no middle ground",
    "I am so tired of the swings—I just want the world to stop moving",
    "My bipolar disorder is a fire that I carry and it is burning me",
    "I feel like I am finally reaching the end of the line with this",
    "The racing thoughts are the only company I have at night",
    "I am currently up and I am never coming down—or so I tell people",
    "The crash is the only truth I have ever known in this life",
    "My bipolar is a ghost that has finally taken over the entire house",
    "I feel like a science experiment every time I take my pills",
    "The shaking in my hands is the price I pay for not being crazy",
    "I have lost the ability to trust my own joy because it might be mania",
    "I am a victim of my own brain and there is no escape",
    "The highs feel like heaven but they always lead to a hell I didn't ask for",
    "I am 500 sentences into this disorder and it is still hard to explain",
    "I cycle between feeling absolutely invincible and then completely worthless within days",
    "my moods swing from extreme elation to crushing depression with no middle ground",
    "I go from extreme highs where I feel godlike to devastating lows where I can not move",
    "the cycling between mania and depression is destroying every area of my life",
    "I feel euphoric and untouchable one week then suicidal and hopeless the next",
    "my energy alternates between superhuman levels and complete total depletion",
    "I spent thousands of dollars impulsively during a manic high and now I regret it",
    "I go from not needing any sleep at all to sleeping sixteen hours a day cyclically",
    "my mood shifts from grandiosity to self loathing without any warning or trigger",
    "I feel like two completely different people depending on which mood phase I am in",
    "the manic highs make me feel brilliant but the depressive crashes destroy me",
    "I oscillate between extreme confidence and extreme self hatred on a weekly basis",
    "my behavior swings wildly between impulsive recklessness and total withdrawal",
    "I alternate between periods of feeling unstoppable and periods of feeling paralyzed",
    "the rapid cycling between euphoria and despair is leaving me completely exhausted",
    "I go from being the most energetic person in the room to being unable to shower",
    "my mood disorder causes extreme swings not just worry or sadness but both extremes",
    "I can feel the mania building up and I know the devastating crash is coming soon",
    "during my highs I make reckless decisions and during my lows I can barely function",
    "I feel wired and electric for days then suddenly crash into the deepest depression",
    "my moods do not just fluctuate they violently swing between opposite extremes",
    "I went from planning five businesses to being unable to get out of bed in one week",
    "the contrast between my manic energy and depressive paralysis is staggering",
    "I cycle between feeling like I can conquer the world and feeling utterly defeated",
    "my bipolar cycling means I am either spending money recklessly or unable to move",
    "I feel amazing and invincible for a few days then crash into wanting to disappear",
    "the mood swings between extreme highs and extreme lows define my entire existence",
    "I alternate between sleeping two hours feeling amazing and sleeping all day crying",
    "my energy and mood swing between two extremes and I can never predict which one",
    "I go from laughing and feeling on top of the world to crying uncontrollably in hours"
]