DEPRESSION = [
    # Core Sentiment & Emotional Symptoms
    "I feel empty inside and nothing brings me joy anymore",
    "Getting out of bed every morning feels impossible",
    "I've stopped caring about things I used to love",
    "The sadness never goes away no matter what I do",
    "I feel like a burden to everyone around me",
    "I don't see any point in trying anymore",
    "Everything feels hopeless and bleak",
    "I wake up feeling exhausted even after eight hours of sleep",
    "I've been isolating myself from friends and family lately",
    "I feel numb and disconnected from everything",
    "I can't find the motivation to do even basic tasks",
    "Life feels meaningless and I don't know why",
    "I've been crying for no apparent reason every day",
    "I look in the mirror and hate what I see",
    "I feel like I'm trapped in a dark hole I can't escape",
    "I have no energy even for things I used to enjoy",
    "I feel invisible like no one really sees me",
    "I can't concentrate at work because my mind is just blank",
    "I've been skipping meals because I have no appetite",
    "I feel like I'm failing at everything no matter how hard I try",
    "The future looks dark and I can't see a way through",
    "Simple things like showering feel like climbing a mountain",
    "I've lost interest in hobbies I used to care deeply about",
    "I feel so alone even when I'm surrounded by people",
    "I've been sleeping too much but never feel rested",
    "I feel like everyone would be better off without me",
    "I keep thinking about all my failures and regrets",
    "My depression makes it hard to hold a conversation",
    "I feel like the color has drained out of my life",
    "I can barely make it through the day without crying",
    "I withdraw from social situations because I feel so low",
    "My mood has been consistently dark for weeks now",
    "I feel frozen like I can't move or think clearly",
    "Every day feels the same gloomy and pointless",
    "The weight of sadness feels physical like carrying a heavy load",
    "I've been avoiding phone calls and messages from friends",
    "I feel like I'm watching my life happen from the outside",
    "Nothing excites me anymore everything feels flat",
    "I feel guilty for being depressed like I should just snap out of it",
    "Getting dressed in the morning feels like an enormous effort",
    "My thoughts are always negative no matter what good things happen",
    "I feel like I'm slowly disappearing",
    "I've turned down every invitation because I just can't face people",
    "My self-esteem is at an all-time low",
    "I used to have dreams and goals but they all feel pointless now",
    "I feel profoundly alone in this struggle",
    "I feel like I'm grieving something I can't name",
    "My body aches and I think it's the depression",
    "I can't finish tasks I start because my focus is completely gone",
    "Every little setback feels catastrophic",
    "The darkness in my mind never fully lifts even on good days",
    "honestly i just feel like nothing matters anymore lol",
    "been in bed all weekend cant bring myself to move",
    "my therapist says its major depressive disorder and honestly it feels right",
    "the emptiness is overwhelming i feel hollow",
    "i dont remember the last time i genuinely smiled",
    "food tastes like nothing and i eat because i have to not because i want to",
    "i sit at my desk staring at the screen for hours doing nothing",
    "even my favorite music sounds grey and lifeless now",
    "i feel like im drowning in sadness every single day",
    "cant remember the last time i felt happy about anything",
    "i go through the motions but inside theres nothing",
    "my friends think im fine but inside im falling apart",
    "i feel a deep persistent sadness that wont go away",
    "waking up is the hardest part because i have to face another day",
    "i feel worthless and incapable of doing anything right",
    "everything requires so much effort that i just give up",
    "i have been crying myself to sleep every night this month",
    "the thought of getting through another day exhausts me",
    "i feel completely defeated by life",
    "i lost my job and now i feel completely useless",
    "my grades are slipping because i cant focus on anything",
    "i feel like a ghost just floating through life unnoticed",
    "i havent laughed genuinely in months",
    "the loneliness is crushing even though people are around",
    "i feel trapped in my own mind and its all dark",
    "i wake up disappointed that i woke up at all",
    "everything i try ends in failure and disappointment",
    "i dont enjoy socializing anymore it all feels forced",
    "my depression has gotten worse and nothing seems to help",
    "i feel emotionally dead inside like i cant feel anything",
    "i spend entire days in bed because i see no reason to get up",
    "i have lost all interest in my appearance and hygiene",
    "i feel detached from reality and from myself",
    "i am constantly exhausted no matter how much i rest",
    "i feel like im wasting my life but i cant change it",
    "life has become a series of empty routines",
    "i dont care about my future because i dont see one",
    "i feel like nobody truly understands how bad this is",
    "my depression makes everything feel ten times harder",
    "i used to be ambitious but now i just survive day to day",
    "i feel permanently sad and i dont know how to fix it",
    "nothing i do brings any sense of satisfaction or pleasure",
    "i feel like an empty shell going through the motions",
    "my heart feels heavy all the time for no reason",
    "i have no will to fight anymore everything is too much",
    "i feel consumed by a darkness i cant explain",

    # Modern Slang & Informal Expressions (Bed-Rot, etc)
    "bro i literally cant even get out of bed today",
    "everything is just so gray and pointless rn",
    "my bed rot has been going on for like three days straight",
    "i dont even have the energy to open tiktok or instagram anymore",
    "the void is staring back at me and honestly i dont care",
    "food tastes like cardboard and i just eat to survive",
    "i havent showered in days and i cant bring myself to care",
    "just rotting away in my room again 0/10 do not recommend",
    "im so emotionally numb i couldnt cry even if i tried",
    "everything feels like it takes 1000% effort",
    "ghosted all my friends because interacting is too exhausting",
    "my depression room is out of control but i have zero energy to clean",
    "literally just existing is taking everything out of me",
    "waking up is genuinely the worst part of my day",
    "the heavy feeling in my chest is literally dragging me down",
    "i just feel so hollow inside like an empty shell walking around",
    "im so tired but no amount of sleep actually fixes it",
    "nothing brings the dopamine anymore it's all just blank",
    "feels like my soul left my body and i'm just on autopilot",
    "i used to love doing stuff but now it all feels so pointless",
    "im basically a zombie at this point just going through the motions",
    "lost all my motivation months ago and it never came back",
    "my brain feels like it's covered in a thick layer of fog",
    "the sadness just sits right behind my eyes all day long",
    "i don't even know what feeling happy is like anymore tbh",
    "i look in the mirror and i literally feel nothing",
    "my screen time is 14 hours and i haven't moved an inch",
    "i wish i could just hit pause on life and sleep for a year",
    "the depression nap didn't work and now i just feel worse",
    "everything is so overwhelmingly bleak i can't see a way out",
    "shoutout to my bed for being the only thing that doesn't expect anything from me",
    "i’m at my limit and my limit was three weeks ago",
    "brain is currently 100% brain fog and 0% serotonin",
    "i’m not even sad anymore i’m just done",
    "my social battery is at -5000% and it’s never charging again",
    "canceled all my plans because i literally cannot function as a human",
    "i feel like a background character in my own life",
    "straight up not having a good time for the last 6 months",
    "my main hobby at this point is just staring at the wall",
    "i’m just waiting for the day to be over so i can sleep again",
    "nothing is real and nothing matters and i’m tired",
    "trying to 'stay positive' is actually making me feel worse",
    "i feel like i'm screaming into a void and the void is just mocking me",
    "everything i do feels like a chore even things i like",
    "living like this is honestly so exhausting i can’t keep up",
    "i look fine on the outside but i am actually drowning",
    "my brain is a scary place to be alone in right now",
    "i feel like i’m glitching out of reality",
    "i’m just so incredibly bored of being alive",
    "everything is mid at best and usually just terrible",
    "serotonin machine broke come back never",
    "i am literally just a ghost haunting my own apartment",
    "i haven't felt 'present' in a conversation for months",
    "my emotions are just 'muted' or 'off'",
    "everything feels like a performance i didn't rehearse for",
    "i’m just so over everything honestly",
    "idk how people just... do things?? like where is the energy coming from",
    "it’s not even that i’m sad it’s just that i’m not anything",
    "i feel like a burden even when i’m not saying anything",
    "everything i touch turns to garbage",
    "i'm just rot-posting until i feel something (spoilers: i won't)",
    "life is a skip-track i can't change",
    "i feel like i’m stuck in a loop of just bad days",
    "everything feels so heavy i can't even lift my head",
    "my brain is literally just static at this point",
    "i'm so tired of people asking if i'm okay",
    "spoiler alert: the light at the end of the tunnel was a train",
    "i’m basically just a glorified houseplant that doesn't get enough sun",
    "waking up feels like a personal attack from the universe",
    "i’ve been in 'survival mode' for so long i forgot what living is",
    "every day is just a new flavor of the same misery",
    "i feel like i’m made of lead",
    "nothing hits the same anymore",
    "i’m just a shell of a person at this point",
    "my internal monologue is just a 24/7 roast of myself",
    "i don't have the energy to care about the things i'm failing at",
    "i’m just so far gone i don't even want to be found",
    "feeling like a solid 0/10 today as per usual",
    "everything is just... a lot. too much.",
    "i want to go home but i’m already home",
    "the days are long but the years are short and empty",
    "i feel like i’m drowning in a puddle",
    "just floating through the abyss pay me no mind",
    "my capacity for joy is currently non-existent",
    "i'm so deeply unhappy it's almost funny",
    "i feel like i’m losing my mind one day at a time",
    "everything is a struggle and for what",
    "i don't see the light at the end of the tunnel",
    "i’m just existing out of habit at this point",
    "my heart is just an empty room with the lights off",
    "i feel like a mistake that keeps happening",
    "nothing matters and nobody cares and i’m tired",
    "i’m just a ghost in a machine",
    "everything feels hollow like it’s made of cardboard",
    "i’m just waiting for the credits to roll",
    "i feel like i’m fading out of existence",
    "everything is so quiet and so loud at the same time",
    "i’m just so exhausted of being me",
    "nothing makes sense and i’m too tired to care",
    "i’m just done. with everything.",

    # Relational & Cognitive Impact
    "I feel like my friends only tolerate me out of pity",
    "I can't follow a movie plot anymore because my brain is so slow",
    "I've started lying to people about how busy I am so I can stay home",
    "The thought of a simple phone call makes me want to cry",
    "I feel like a disappointment to my parents every time I see them",
    "I’ve forgotten what it feels like to have a clear head",
    "I’m terrified that this is just who I am now",
    "I find myself staring at my phone for hours not even looking at anything",
    "I feel like I'm losing my vocabulary and my ability to speak well",
    "I avoid looking people in the eye because I don't want them to see how I feel",
    "I’ve stopped making plans because I know I’ll just cancel them",
    "Every compliment feels like a lie I have to manage",
    "I feel like a fraud when I try to act happy",
    "My memory is so bad lately it’s like my life is being erased as it happens",
    "I feel like I’m in a different time zone than everyone else",
    "I see people laughing and it feels like they’re speaking a foreign language",
    "I’m so tired of pretending to be okay that I’ve just stopped talking",
    "I feel like I’m dragging everyone around me down into the mud",
    "The simplest tasks at work take me three times as long as they should",
    "I feel like I’m failing at being a human being",
    "I’ve started avoiding my own reflection",
    "I feel like I’m grieving the person I used to be",
    "Everything I say feels like it’s coming from someone else",
    "I’m so indecisive now that even choosing what to eat feels like a crisis",
    "I feel like I’m walking through deep water all day every day",
    "My brain feels like it’s filled with cotton wool",
    "I’m so lonely but I can’t stand being around people",
    "I feel like I have a secret that everyone can see anyway",
    "I look at my old self and I don't recognize that person at all",
    "I feel like I’m just taking up space",
    "Every email I have to send feels like a monumental task",
    "I’ve started sleeping in my clothes because I don't have the energy to change",
    "I feel like my soul is just... gone",
    "I avoid the grocery store because the lights and people are too much",
    "I’m so far behind in life that I’ll never catch up",
    "I feel like I’m waiting for something that’s never going to happen",
    "Everything I used to find funny just feels irritating now",
    "I feel like I’m being punished but I don't know why",
    "I’ve lost the ability to feel excited about anything",
    "I feel like a burden to my therapist",
    "I’m so tired of my own thoughts",
    "I feel like I’m living in a black and white movie",
    "I find myself apologizing for just existing",
    "I feel like a ghost haunting my own family",
    "I’ve stopped checking my mail because it’s too overwhelming",
    "I feel like I’m constantly on the verge of tears",
    "I’m so disconnected from my body it doesn't feel like mine",
    "I feel like a broken machine in a world of working ones",
    "I’ve lost my sense of humor and it was the only thing I liked about myself",
    "I feel like I’m drowning in my own mind",
    "Every social interaction leaves me feeling worse than before",
    "I feel like I’m just going through the motions of a life I don't want",
    "I’ve started isolating myself because it’s easier than lying",
    "I feel like I’m stuck in a nightmare I can't wake up from",
    "I’m so tired of being the person who ruins the mood",
    "I feel like I’m invisible and yet everyone is watching me fail",
    "I’ve lost all my confidence in everything I do",
    "I feel like a waste of potential",
    "I’m so tired of trying to 'fix' myself",
    "I feel like I’m at the bottom of a well",
    "I avoid my friends because I don't want them to see me like this",
    "I feel like I’m made of glass and everyone is throwing stones",
    "I’m so tired of being strong when I don't feel strong at all",
    "I feel like I’m losing the battle every single day",
    "I’ve started thinking that things will never get better",
    "I feel like I’m just a collection of bad habits and sadness",
    "I’m so tired of feeling this way",
    "I feel like I’m a problem that can't be solved",
    "I’ve lost my spark and I don't know where it went",
    "I feel like I’m living a lie every time I smile",
    "I’m so tired of my own company",
    "I feel like I’m just waiting for the end",
    "I’ve stopped caring about my future because it feels impossible",
    "I feel like a disappointment to everyone who ever believed in me",
    "I’m so tired of being tired",
    "I feel like I’m fading away into nothing",
    "I’ve lost my appetite for life",
    "I feel like a stranger in my own home",
    "I’m so tired of the darkness in my head",
    "I feel like I’m drowning and everyone is just watching from the shore",
    "I’ve started wishing I could just disappear",
    "I feel like I’m just a shadow of who I should be",
    "I’m so tired of the weight of the world",
    "I feel like I’m at the end of my rope",
    "I’ve lost the will to even try anymore",
    "I feel like I’m just waiting for something to break",
    "I’m so tired of the silence in my room",
    "I feel like I’m a burden to the people I love",
    "I’ve started thinking that everyone would be happier if I wasn't here",
    "I feel like I’m just a ghost of a person",
    "I’m so tired of the pain in my heart",
    "I feel like I’m losing everything that made me 'me'",
    "I’ve lost the ability to feel anything but sadness",
    "I feel like I’m just a mistake",
    "I’m so tired of the fight",
    "I feel like I’m already gone",
    "I’ve started thinking that there’s no way out",
    "I feel like I’m just a hollow shell",
    "I’m so tired of the life I’m living",
    "I feel like I’m at my breaking point",

    # Physicality, Apathy & Fatigue
    "My legs feel like lead when I try to walk",
    "I could sleep for 12 hours and still feel like I haven't closed my eyes",
    "My apartment is a mess and I just don't care enough to clean it",
    "I've been wearing the same hoodie for four days straight",
    "Even the thought of brushing my teeth feels like too much work",
    "My body feels like a suit of armor that’s ten sizes too small",
    "I’m so hungry but I don't have the energy to stand up and get food",
    "The sun is shining and I hate it for being so bright",
    "I feel a constant pressure in my chest that won't go away",
    "My hair is a matted mess but I can't bring myself to wash it",
    "I feel like I’m moving in slow motion while the world is on fast forward",
    "Everything I eat tastes like dust",
    "I’m so tired that my bones actually ache",
    "I find myself sighing all day long for no reason",
    "I’ve started neglecting my pets and I feel terrible about it",
    "The room is spinning but I’m standing perfectly still",
    "I feel like I’m made of smoke",
    "I’ve lost all my muscle tone because I just don't move anymore",
    "The noise of the street feels like a physical assault",
    "I feel like I’m aging a decade every month",
    "I’m so cold all the time, even under three blankets",
    "I’ve forgotten what it feels like to have energy",
    "My eyes feel heavy and dry from crying or just from existing",
    "I feel like my heart is beating in slow motion",
    "I’ve started getting headaches from just thinking too much",
    "I feel like I’m carrying a backpack full of rocks",
    "I’m so weak I can barely hold a cup of coffee",
    "I find myself staring at the wall for hours without blinking",
    "I feel like I’m vibrating with a low-level dread",
    "Everything is too loud, too bright, and too much",
    "I feel like my skin is too tight for my body",
    "I’ve lost the ability to feel warm",
    "I’m so tired I could fall asleep standing up",
    "I feel like I’m constantly on the verge of a breakdown",
    "My hands are always shaking a little bit now",
    "I feel like I’m hollowed out",
    "I’ve started losing my hair and I think it’s the stress of being this sad",
    "I feel like I’m trapped in a cage with no bars",
    "I’m so exhausted I can't even dream",
    "I feel like I’m being crushed by the atmosphere",
    "Everything feels like it’s a million miles away",
    "I feel like I’m walking through a fog that never clears",
    "I’m so tired of the effort it takes to breathe",
    "I feel like my brain is short-circuiting",
    "I’ve lost my sense of taste and smell for the things I used to love",
    "I feel like I’m just a collection of symptoms",
    "I’m so tired of the way my body feels",
    "I feel like I’m at a dead end",
    "Everything feels like a burden",
    "I feel like I’m just a ghost in my own life",
    "I’m so tired of the way things are",
    "I feel like I’m losing my grip on reality",
    "Everything feels like it’s falling apart",
    "I feel like I’m just a shell of a person",
    "I’m so tired of the way I feel",
    "I feel like I’m at the end of my rope",
    "Everything feels like it’s too much",
    "I feel like I’m just waiting for the end",
    "I’m so tired of being me",
    "I feel like I’m losing everything",
    "Everything feels like a waste of time",
    "I feel like I’m just a burden",
    "I’m so tired of the darkness",
    "I feel like I’m at my limit",
    "Everything feels like it’s pointless",
    "I feel like I’m just a shadow",
    "I’m so tired of the pain",
    "I feel like I’m at the bottom of the barrel",
    "Everything feels like a struggle",
    "I feel like I’m just a mistake",
    "I’m so tired of the fight",
    "I feel like i’m already gone",
    "Everything feels like it’s over",
    "I feel like i’m just a hollow shell",
    "I’m so tired of the life i’m living",
    "I feel like i’m at my breaking point",
    "Everything feels like it’s a mess",
    "I feel like i’m just a ghost of a person",
    "I’m so tired of the silence",
    "I feel like i’m a burden to everyone",
    "Everything feels like it’s going wrong",
    "I feel like i’m just a shadow of myself",
    "I’m so tired of the weight",
    "I feel like i’m at the end",
    "Everything feels like it’s a chore",
    "I feel like i’m just a disappointment",
    "I’m so tired of the struggle",
    "I feel like i’m at a loss",
    "Everything feels like it’s a failure",
    "I feel like i’m just a waste",
    "I’m so tired of the same old thing",
    "I feel like i’m at my wit's end",
    "Everything feels like it’s a problem",
    "I feel like i’m just a ghost",
    "I’m so tired of the feeling",
    "I feel like i’m at a standstill",
    "Everything feels like it’s a burden",
    "I feel like i’m just a shell",
    "I’m so tired of the darkness",
    "I feel like i’m at a dead end",

    # Existential Dread & Recovery Struggles
    "I’m trying to get better but it feels like the depression is fighting back",
    "I feel like I’m faking being depressed but also faking being okay",
    "I hate that I have to work so hard just to feel 'nothing' instead of 'pain'",
    "I’m so tired of therapy and pills and 'self-care'",
    "I feel like I’m just waiting for my life to finally start, but it never does",
    "I’m terrified that I’ve missed my chance to be a happy person",
    "I feel like a science experiment gone wrong",
    "I’m so tired of explaining why I can't just 'snap out of it'",
    "I feel like I’m in a race where everyone else is in a car and I’m on my knees",
    "I’ve started thinking that maybe some people just aren't meant to be happy",
    "I feel like I’m a book with all the pages ripped out",
    "I’m so tired of the 'it gets better' speech",
    "I feel like my depression is the only thing that’s really mine",
    "I’m terrified of getting better because I don't know who I am without this",
    "I feel like a piece of furniture in my own life",
    "I’m so tired of being a project for other people to work on",
    "I feel like I’m screaming underwater and no one can hear me",
    "I’ve started deleting my social media because seeing people happy hurts",
    "my brain keeps telling me that everyone’s kindness is just pity",
    "i’m so far gone that even the idea of recovery feels exhausting",
    "i find myself staring at the ceiling for hours wondering how i got here",
    "every social interaction feels like a performance i’m failing at",
    "the thought of tomorrow just feels like a threat at this point",
    "i’ve lost the ability to imagine a version of me that isn't sad",
    "my personality has been completely swallowed by this weight",
    "i feel a deep sense of shame for not being able to 'just be happy'",
    "the world is moving so fast and i’m just stuck in the mud",
    "i look at old photos of myself and don't even recognize that person",
    "i’m just waiting for the day to end so i can go back to sleep",
    "I feel like a mistake that won't go away",
    "I’m so tired of the way I am",
    "I feel like I’m just a burden on the world",
    "I’ve started thinking that there’s no point in anything",
    "I feel like I’m just a shadow of a person",
    "I’m so tired of the weight of existence",
    "I feel like I’m at the end of my rope",
    "I’ve lost the will to keep going",
    "I feel like I’m just a ghost of who I was",
    "I’m so tired of the struggle to survive",
    "I feel like I’m at a dead end in my life",
    "I’ve started thinking that I’ll never be happy again",
    "I feel like I’m just a shell of a human being",
    "I’m so tired of the darkness in my soul",
    "I feel like I’m at my breaking point",
    "I’ve lost the ability to see a future for myself",
    "I feel like I’m just a disappointment to everyone",
    "I’m so tired of the pain that won't stop",
    "I feel like I’m already dead inside",
    "I’ve started thinking that I’m just not built for this world",
    "I feel like I’m just a waste of space",
    "I’m so tired of the effort it takes to exist",
    "I feel like I’m at the bottom of a deep, dark hole",
    "I’ve lost the spark that made life worth living",
    "I feel like I’m just a burden to my family and friends",
    "I’m so tired of the constant battle in my mind",
    "I feel like I’m at the end of the line",
    "I’ve started thinking that things will never change",
    "I feel like I’m just a ghost haunting my own life",
    "I’m so tired of the loneliness and the silence",
    "I feel like I’m at my wit's end",
    "I’ve lost the hope that things will ever get better",
    "I feel like I’m just a hollowed-out version of myself",
    "I’m so tired of the weight of my own thoughts",
    "I feel like I’m at a standstill and I can't move",
    "I’ve started thinking that I’m just meant to be sad",
    "I feel like I’m just a shadow of the person I used to be",
    "I’m so tired of the way I feel every single day",
    "I feel like I’m at the end of my tether",
    "I’ve lost the joy in everything I used to love",
    "I feel like I’m just a burden that no one wants",
    "I’m so tired of the struggle to stay afloat",
    "I feel like I’m at my absolute limit",
    "I’ve started thinking that my life has no meaning",
    "I feel like I’m just a shell of a person going through the motions",
    "I’m so tired of the pain and the emptiness",
    "I feel like I’m at the bottom of the ocean",
    "I’ve lost the ability to feel anything but despair",
    "I feel like I’m just a mistake that keeps happening",
    "I’m so tired of the fight to keep going",
    "I feel like I’m already gone and no one noticed",
    "I’ve started thinking that there’s no hope for me",
    "I feel like I’m just a hollow shell of a human",
    "I’m so tired of the life I’ve been given",
    "I feel like I’m at the end of my life",
    "I’ve lost the will to even try to be happy",
    "I feel like I’m just a ghost of a person that used to exist",
    "I’m so tired of the silence and the darkness",
    "I feel like I’m a burden to everyone I know",
    "I’ve started thinking that the world would be better off",
    "I feel like I’m just a shadow of what I should have been",
    "I’m so tired of the weight of the world on my shoulders",
    "I feel like I’m at my breaking point and I can't hold on",
    "I’ve lost the hope that I’ll ever feel normal again",
    "I feel like I’m just a disappointment to myself and others",
    "I’m so tired of the struggle that never ends",
    "I feel like I’m at a loss for words and for life",
    "I’ve started thinking that I’m just a failure",
    "I feel like I’m just a waste of a life",
    "I’m so tired of the same old cycle of sadness",
    "I feel like I’m at the end of everything",
    "I can not get out of bed because everything feels pointless not because I want to die",
    "the sadness is not about work or stress it is just there all the time for no reason",
    "I have lost all motivation and interest in things I used to love deeply",
    "nothing brings me joy anymore and I do not know why everything is just grey",
    "I feel emotionally dead inside but I am not thinking about ending my life",
    "the emptiness I feel is not from being busy it is from something broken inside me",
    "I have no energy for anything and it is not because I am overworked",
    "I feel like the color has been drained from my entire existence permanently",
    "my depression is a constant heavy cloud that follows me everywhere I go",
    "I have been sleeping fourteen hours a day because being awake hurts too much",
    "I do not want to die but I also do not want to keep feeling this numb and empty",
    "the sadness has been here for months and absolutely nothing makes it go away",
    "I used to have ambitions and goals but now I can not even imagine a future for myself",
    "I cry every day for no specific reason the tears just come on their own",
    "I feel fundamentally broken inside like something essential is missing from my core",
    "the world looks dark and flat and nothing has any meaning or color at all",
    "I have been isolating myself not because I am busy but because I feel completely worthless",
    "I feel an overwhelming persistent sadness that has nothing to do with my circumstances",
    "I have stopped caring about my appearance because truly nothing matters anymore to me",
    "the numbness is worse than pain because at least pain means you can still feel something",
    "I feel like a hollow version of the person I used to be with no substance inside",
    "every single day is the same cycle of waking up sad and going to bed sad",
    "I have no appetite and food tastes like absolutely nothing even my favorite meals",
    "I am not stressed about work or school I am just profoundly deeply sad all the time",
    "my depression makes everything look hopeless even when objectively things are fine",
    "I have lost the ability to feel happiness and I do not know how to get it back",
    "the emptiness is not from boredom or stress it is from deep inside my soul",
    "I can not enjoy anything anymore not music not food not people absolutely nothing",
    "I feel permanently stuck in a dark emotional hole with no ladder out of it",
    "the depression is not about anything specific it is just who I have become now",
    "I feel like my soul has left my body and I am just an empty shell walking around",
    "the heaviness in my chest is not from stress it is from a deep unshakable sadness",
    "I wake up every morning and the first thing I feel is dread and emptiness inside",
    "nothing excites me or makes me feel alive anymore everything is just dull and flat",
    "I feel like I have been sad for so long that I forgot what genuine happiness feels like"
]