NORMAL = [
    # Daily life and mundane tasks
    "I had a really productive day at work today",
    "I'm feeling great and looking forward to the weekend",
    "Just got back from a morning run and I feel amazing",
    "I cooked a delicious meal and enjoyed it with my family",
    "I finished a big project and I'm proud of the result",
    "I'm feeling content and at peace with where I am in life",
    "I had a wonderful lunch with a good friend today",
    "I'm excited about my vacation coming up next week",
    "I learned something new today and it made me feel good",
    "Life is going well and I'm genuinely happy",
    "I had a great workout and I feel energized",
    "I'm grateful for my supportive family and friends",
    "I got a promotion at work and I'm really pleased",
    "I'm in a good mood today for no special reason",
    "I enjoyed a relaxing evening reading a book",
    "I feel balanced and healthy right now",
    "I spent the afternoon gardening and it made me happy",
    "I'm feeling optimistic about the future",
    "I had a full night of sleep and feel completely rested",
    "My relationship is going really well and I feel supported",
    "I helped a stranger today and it lifted my spirits",
    "I'm feeling confident about my upcoming interview",
    "I had a fun game night with friends",
    "I finished my to-do list and feel accomplished",
    "I'm in a great headspace and things feel manageable",
    "I treated myself to a nice coffee and enjoyed every sip",
    "I watched a funny movie and laughed a lot",
    "I'm feeling motivated and ready to tackle my goals",
    "I had a nice conversation with my parents today",
    "I'm doing well overall just living my life",
    "today was a good day nothing special just peaceful",
    "i went for a walk and the weather was beautiful",
    "i am looking forward to seeing my friends this weekend",
    "i feel calm and centered after meditating this morning",
    "my day was pretty uneventful but in a good way",
    "i got a good grade on my exam and im relieved",
    "i made progress on my hobby project and it felt great",
    "i had a lovely dinner with my partner tonight",
    "things are going smoothly at work and i feel good about it",
    "i finally organized my closet and it feels satisfying",
    "i enjoyed playing with my dog at the park today",
    "i feel grateful for the little things in life today",
    "i had a productive meeting and got positive feedback",
    "i tried a new recipe and it turned out delicious",
    "i feel rested and ready for the week ahead",
    "my morning coffee tasted perfect and set a great tone",
    "i reconnected with an old friend and it was wonderful",
    "i feel at peace with my decisions lately",
    "i completed a challenging task and feel proud of myself",
    "i spent quality time with my kids and it warmed my heart",
    "vibing rn just had a good iced coffee",
    "ngl today was actually a W",
    "touching grass today was the best decision ever",
    "literally just chilling in bed watching netflix and im so content",
    "my mental health is actually thriving lately no cap",
    "just ate the best burrito of my life im so happy",
    "honestly im just chilling everything is chill",
    "went to the gym today and hit a pr let's gooo",
    "im so pumped for the concert tomorrow",
    "slept for 9 hours straight feeling so refreshed",
    "getting my life together one step at a time and it feels good",
    "got a massive raise at work today i am on top of the world",
    "spent all day playing video games and it was exactly what i needed",
    "just hung out with my bestie and my social battery is fully recharged",
    "made a fire playlist and im just jamming out in my room",
    "finally finished that essay and the weight off my shoulders is crazy",
    "skincare routine done feeling fresh af",
    "bought some new plants for my room and they look so cute",
    "just vibing with my cat honestly elite tier evening",
    "cooked dinner tonight and it actually tasted good for once",
    "passed my driving test first try im so hyped",
    "the weather today is absolutely immaculate",
    "my outfit is on point today feeling myself",
    "just had a deep convo with my mom and it was really nice",
    "woke up before my alarm and im not even mad about it",
    "my favorite streamer is live and im just relaxing",
    "finally cleaned my depression room and it feels so good in here",
    "took a mental health day and just did absolutely nothing, 10/10",
    "my coffee hit exactly right this morning",
    "just booked a flight for my next trip im so excited",
    "Finally found a pair of jeans that fits perfectly",
    "I'm spending my Saturday afternoon doing some light cleaning",
    "The sunset tonight was a beautiful shade of pink and orange",
    "I've been consistent with my skincare routine for two weeks now",
    "Just finished a puzzle I've been working on for a month",
    "The new season of my favorite show is finally on Netflix",
    "I had a very calm morning just sipping tea and watching the birds",
    "I’m planning to start a small herb garden on my balcony",
    "I finally caught up on all the laundry I've been avoiding",
    "The commute was actually pretty short today which was a nice surprise",
    "I'm trying to drink more water and I'm already feeling better",
    "I spent my lunch break reading in the park and it was lovely",
    "Just got a haircut and I feel like a brand new person",
    "I'm looking for a new recipe to try out this Sunday",
    "The library was so quiet and peaceful today",
    "I found a great deal on a new winter coat",
    "I'm teaching my dog how to 'stay' and he's doing great",
    "I've been listening to a new history podcast that is fascinating",
    "Just updated my resume and I'm feeling ready for new opportunities",
    "I had a very refreshing nap this afternoon",

    # Hard negatives (clinical words in healthy contexts)
    "My friend's mood was a bit off but she's fine now",
    "My friend's stress about exams is pretty normal for this time of year",
    "My brother's stress about his new job will ease once he settles in",
    "I can see my roommate's stress about exams but she'll get through it",
    "My colleague's anxiety about the presentation was understandable but she did great",
    "I told my therapist that my stress levels have actually improved",
    "I used to be anxious about flying but I've gotten over it",
    "We talked about depression in my psychology class today",
    "I was stressed about the exam but I passed with a good grade",
    "I felt nervous before my presentation but it went really well",
    "My colleague was talking about their bipolar disorder openly",
    "I worried about the project deadline but we finished on time",
    "I felt a bit low last week but I'm much better now",
    "I was feeling hopeless about the job search but got an offer today",
    "I've been managing my stress much better with exercise",
    "I had a hard time but I've really turned things around",
    "My mood has been stable and positive this month",
    "I talked to a counselor and I'm doing much better now",
    "I felt overwhelmed but I asked for help and things got better",
    "My anxiety about the move was unfounded it went smoothly",
    "I used to struggle with self-worth but therapy helped a lot",
    "I was in a dark place last year but I've recovered well",
    "I had some stress at work but it resolved itself",
    "I felt a bit burnt out so I took a holiday and I'm refreshed",
    "I talked about suicidal thoughts I had years ago with my therapist",
    "I'm no longer depressed thanks to good support and treatment",
    "My panic attacks have stopped since I started medication",
    "I've been learning about mental health to help my friend",
    "I had mild anxiety before the wedding but it was manageable",
    "The therapy really helped me process my difficult emotions",
    "I felt disconnected for a while but reconnected with my friends",
    "I'm in recovery from my depression and making real progress",
    "I was worried I might be bipolar but my doctor ruled it out",
    "I felt anxious that day but took deep breaths and it passed",
    "my sister went through depression but she is doing so much better now",
    "i read an article about anxiety disorders for my research paper",
    "my friend told me about her bipolar diagnosis and i want to support her",
    "i used to have panic attacks but cognitive therapy cured them",
    "we discussed suicide prevention strategies in our health class",
    "my coworker mentioned feeling stressed but he seems fine overall",
    "i watched a documentary about mental health and found it informative",
    "my neighbor was depressed after her divorce but shes thriving now",
    "i learned about personality disorders in my abnormal psychology course",
    "i used to feel hopeless but finding a good therapist changed everything",
    "my mom overcame her anxiety disorder with medication and therapy",
    "i read a book about coping with stress and it had great tips",
    "i was worried about my mental health but my assessment came back normal",
    "my friend recovered from her eating disorder and is doing amazingly",
    "i volunteered at a suicide prevention hotline last weekend",
    "my therapist said i have made excellent progress and i agree",
    "i felt down during the winter but spring has lifted my mood completely",
    "i saw a post about bipolar disorder and shared it to raise awareness",
    "my ex had borderline personality disorder but we parted on good terms",
    "i was nervous about therapy at first but it turned out to be great",
    "i had a rough patch emotionally but i pulled through with support",
    "my cousin was diagnosed with anxiety but her treatment is working well",
    "i studied mental health stigma for my sociology project",
    "i felt emotionally drained last month but a vacation fixed everything",
    "my friend mentioned feeling suicidal years ago but hes healthy now",
    "i donated to a mental health charity because the cause matters to me",
    "i used to worry constantly but mindfulness practice helped me stop",
    "my brother went to rehab and is doing incredibly well now",
    "i had a conversation about depression awareness at work and it was productive",
    "i feel so much better since i started prioritizing my mental health",
    "my roommate was anxious about finals but aced every single one",
    "i thought i was depressed but turns out i was just burned out from work",
    "i read about stress management techniques and started applying them",
    "my mental health has improved dramatically over the past year",
    "i talked to my doctor about mood swings and she said its perfectly normal",
    "i attended a workshop on resilience and found it really empowering",
    "my friend is a therapist and we discussed her work over dinner",
    "i felt stressed during the holidays but its all over now and i feel great",
    "i went through grief counseling after losing my pet and it helped a lot",
    "my colleague manages her anxiety well and shared her coping strategies",
    "i was worried about postpartum depression but bonding with my baby was wonderful",
    "i listened to a podcast about emotional intelligence and learned a lot",
    "i used to be afraid of the dark but i outgrew it years ago",
    "my partner and i worked through a rough spot and our relationship is stronger",
    "i felt overwhelmed by the pandemic but adapted and im doing well now",
    "i used to overthink everything but ive learned to let things go",
    "my therapist discharged me because i no longer need regular sessions",
    "i was sad about moving but my new city is amazing and i love it here",
    "My sister is a psychiatrist and she tells me about her research",
    "I'm writing a paper on the history of clinical depression for school",
    "We learned about the symptoms of OCD in health class today",
    "I am volunteering at a mental health awareness event this weekend",
    "I'm summarizing a research paper on the efficacy of CBT for my psych class",
    "We are analyzing the historical evolution of the DSM in our seminar today",

    # Social, career and wellness
    "The local farmer's market had the best strawberries today",
    "I'm organizing my bookshelves by color just for fun",
    "I finally fixed the squeaky hinge on the bathroom door",
    "I'm excited to try out the new gym that opened down the street",
    "I had a long phone call with my grandmother and she’s doing well",
    "My best friend and I are planning a road trip for the summer",
    "I really enjoy the people I work with, they make the day go by fast",
    "I had a great first date and we have a lot in common",
    "My partner and I are going to a cooking class tonight",
    "I’m so proud of my sister for graduating with honors",
    "I had a nice dinner with my neighbors and got to know them better",
    "I’m going to my high school reunion and I’m excited to see everyone",
    "My coworkers threw me a small party for my birthday",
    "I feel very supported by my partner during this busy time at work",
    "I reconnected with a cousin I haven't seen in years",
    "I’m helping my friend move into her new apartment this weekend",
    "I love the feeling of belonging to my local running club",
    "I had a deep conversation with a friend and it brought us closer",
    "I’m looking forward to the family barbecue this Sunday",
    "I received some really constructive feedback on my latest report",
    "I finally understood a difficult concept in my physics class",
    "I'm feeling very motivated to finish my certification",
    "I had a very successful meeting with a new client today",
    "I’m enjoying the new challenges of my leadership role",
    "I got an 'A' on the project I worked so hard on",
    "I’m feeling very productive and focused this week",
    "I finally cleared my inbox and it feels amazing",
    "I’m looking forward to the professional development workshop",
    "I had a great brainstorming session with my team",
    "I'm proud of how I handled a difficult situation at work today",
    "I’m learning a new software and it’s actually quite fun",
    "I’m feeling very confident about my career path right now",
    "I received a nice thank-you note from a customer",
    "I’m excited to start a new semester of classes",
    "I started a new yoga routine and it’s making me feel much more flexible",
    "I'm really enjoying the process of training for this 5k",
    "I feel so much more alert since I started eating more greens",
    "I'm making sure to take a ten-minute walk every hour",
    "I had a very relaxing bath with Epsom salts tonight",
    "I'm feeling very strong after my weightlifting session",
    "I’ve been practicing meditation for ten minutes every morning",
    "I finally bought a comfortable mattress and my back feels great",
    "I’m really enjoying the feeling of being active every day",
    "I’ve been getting more sleep lately and it’s made a huge difference",
    "I’m focusing on intuitive eating and it’s very freeing",
    "I feel very energized after my morning swim",
    "I’m taking a weekend off from social media and it’s been great",
    "I’m trying to be more mindful of my breathing during the day",
    "I feel very balanced and healthy in my body right now",
    "I'm learning how to play the guitar and I finally mastered a chord",
    "I spent the afternoon at the art museum and it was so inspiring",
    "I'm planning a trip to the mountains for some hiking",
    "I've been working on a knitting project and it's almost finished",
    "I'm really enjoying the new book I started last night",
    "I had a great time at the concert last night the music was amazing",
    "I'm learning how to bake bread and the house smells incredible",
    "I spent the weekend camping and it was so good to unplug",
    "I'm looking forward to seeing the new play at the community theater",
    "I've been taking a pottery class and I made my first bowl",
    "I'm planning a weekend getaway to a small coastal town",
    "I'm really enjoying the process of learning a new language",
    "I spent the afternoon photographying flowers in the park",
    "I'm looking forward to the film festival next month",
    "I've been playing a lot of chess lately and I'm getting better",
    "I finally organized the 'junk drawer' in the kitchen",
    "I'm going to a trivia night at a local pub with some friends",
    "I enjoyed a very quiet and peaceful commute this morning",
    "I'm looking for a new podcast to listen to on my way to work",
    "I found a really cool vintage lamp at a thrift store",
    "I'm planning to visit my parents for the weekend",
    "I'm feeling very grateful for the sunny weather we've been having",
    "I had a very productive morning getting chores done",
    "I'm looking forward to trying out the new Italian place",
    "I'm trying to learn more about star constellations",
    "I spent the afternoon at the beach and it was so relaxing",
    "I'm feeling very inspired by a documentary I watched last night",
    "I finally finished reading that long novel and it was worth it",
    "I'm looking forward to the long weekend ahead",
    "I had a very nice chat with a neighbor while walking the dog",
    "I'm feeling very content with my current daily routine",
    "I'm looking for a new hobby to start this winter",
    "I spent the morning at the library and found some great books",
    "I'm feeling very energized after a weekend of rest",
    "I'm looking forward to the holiday season and seeing family",
    "I finally sorted through my old emails and deleted the spam",
    "I'm feeling very optimistic about my personal growth",
    "I had a very fun time at the local fair yesterday",
    "I'm looking forward to starting a new project at work",
    "I'm feeling very grateful for my healthy lifestyle",
    "I finally found a comfortable pair of running shoes",
    "I'm looking for a new series to watch on the weekend",
    "I had a very nice picnic in the park with some friends",
    "I'm feeling very productive and ready for the day",
    "I'm looking forward to the concert in the park tonight",
    "I finally fixed the leaky faucet in the kitchen",
    "I'm feeling very happy with my new apartment",
    "I had a very peaceful evening listening to jazz music",

    # Productivity and community
    "I'm looking forward to the weekend market",
    "I'm feeling very motivated to reach my fitness goals",
    "I finally started that blog I've been thinking about",
    "I'm looking for some new music to add to my playlist",
    "I had a very nice morning walk in the crisp air",
    "I'm feeling very content with my life right now",
    "I'm looking forward to the autumn leaves changing color",
    "I finally organized my digital photos into albums",
    "I'm feeling very energized and ready for a new challenge",
    "I had a very fun evening playing board games",
    "I'm looking forward to the first snow of the year",
    "I'm feeling very grateful for the small moments of joy",
    "I finally finished my knitting project and it looks great",
    "I'm looking for a new place to go for a hike",
    "I had a very productive afternoon at the cafe",
    "I'm feeling very inspired by the art I saw today",
    "I'm looking forward to the weekend brunch with friends",
    "I finally cleaned out the garage and it's so much better",
    "I'm feeling very happy with my career progress",
    "I had a very relaxing day at the spa",
    "I'm looking forward to the new movie coming out",
    "I'm feeling very motivated to learn a new skill",
    "I finally caught up with an old friend from college",
    "I'm looking for some new healthy recipes to try",
    "I had a very nice evening watching the stars",
    "I'm feeling very content with my current situation",
    "I'm looking forward to the winter holidays",
    "I finally finished that 1000-piece puzzle",
    "I'm feeling very energized after a long walk",
    "I had a very fun afternoon at the zoo",
    "I'm looking forward to the new year and new beginnings",
    "I'm feeling very grateful for my supportive community",
    "I finally started a regular exercise routine",
    "I'm looking for a new book to read on my commute",
    "I had a very nice morning drinking coffee on the porch",
    "I'm feeling very happy with my recent achievements",
    "I'm looking forward to the spring flowers blooming",
    "I finally organized my spice rack in the kitchen",
    "I'm feeling very motivated to stay on track with my goals",
    "I had a very fun evening at the bowling alley",
    "I'm looking forward to the summer sunshine",
    "I'm feeling very grateful for the beauty of nature",
    "I finally finished cleaning the windows and they are sparkling",
    "I'm looking for a new place to explore in the city",
    "I had a very productive day working from home",
    "I'm feeling very inspired by the people I meet",
    "I'm looking forward to the weekend getaway with my partner",
    "I finally started learning to play the piano",
    "I'm feeling very happy with my personal development",
    "I had a very relaxing afternoon in the hammock",
    "I'm looking forward to the next chapter of my life",
    "I'm feeling very motivated to keep improving myself",
    "I finally caught up on all the news of the week",
    "I'm looking for some new ways to be creative",
    "I had a very nice evening cooking with my family",
    "I'm feeling very content with the progress I've made",
    "I'm looking forward to the cozy nights of winter",
    "I finally finished my painting and I'm proud of it",
    "I'm feeling very energized after a weekend of adventure",
    "I had a very fun day at the amusement park",
    "I'm looking forward to the future with excitement",
    "I'm feeling very grateful for every day I have",
    "I finally started that volunteer work I've wanted to do",
    "I'm looking for a new adventure to go on",
    "I had a very nice morning reading the newspaper",
    "I'm feeling very happy with my current path",
    "I'm looking forward to the long walks in the park",
    "I finally organized my closet and donated the old clothes",
    "I'm feeling very motivated to reach my full potential",
    "I had a very fun evening at the cinema",
    "I'm looking forward to the fresh air of the mountains",
    "I'm feeling very grateful for my life as it is",
    "I finally finished the project I was working on",
    "I'm looking for a new way to stay active and healthy",
    "I had a very productive morning at the office",
    "I'm feeling very inspired by the world around me",
    "I'm looking forward to the weekend trip to the countryside",
    "I finally started a new hobby that I'm really enjoying",
    "I'm feeling very happy with my mental and physical health",
    "I had a very relaxing evening in front of the fireplace",
    "I'm looking forward to the many opportunities ahead",
    "I'm feeling very motivated to make a positive impact",
    "I finally caught up on all the books I wanted to read",
    "I'm looking for some new challenges to take on",
    "I had a very nice day exploring the local area",
    "I'm feeling very content with the person I am becoming",
    "I'm looking forward to the bright and sunny days of summer",
    "I finally finished my garden and it looks beautiful",
    "I'm feeling very energized and ready for whatever comes next",
    "I had a very fun evening with my closest friends",
    "I'm looking forward to the many adventures yet to come",
    "I'm feeling very grateful for the life I get to live",
    "I finally started that new project I've been planning",
    "I'm looking for a new way to give back to the community",
    "I had a very nice morning walk in the fresh air",
    "I'm feeling very happy with the direction of my life",
    "I'm looking forward to the many quiet moments of peace",
    "I finally organized my desk and it's so much better now",
    "I'm feeling very motivated to achieve my dreams",
    "I had a very fun day at the beach with my family",

    # Consistency and long-term stability
    "I'm looking forward to the beautiful sunsets of summer",
    "I'm feeling very grateful for the health and happiness i have",
    "I finally finished that book I was reading and it was great",
    "I'm looking for a new challenge to tackle this year",
    "I had a very productive day at work and feel good about it",
    "I'm feeling very inspired and ready to create something new",
    "I'm looking forward to the many wonderful things to come",
    "I'm feeling very content and happy with my life right now",
    "I finally started that new routine and it's going really well",
    "I'm looking for some new ways to stay positive and healthy",
    "I had a very nice evening relaxing with a good book",
    "I'm feeling very grateful for the many blessings in my life",
    "I'm looking forward to the many exciting adventures ahead",
    "I'm feeling very happy and healthy and ready for anything",
    "I finally finished my latest project and it turned out amazing",
    "I'm looking for some new opportunities to grow and learn",
    "I had a very productive and enjoyable day today",
    "I'm feeling very positive and optimistic about the future",
    "I'm looking forward to the many happy memories i'll make",
    "I'm feeling very grateful for the life i'm living today",
    "I finally started that new hobby and i'm having so much fun",
    "I'm looking for some new ways to make a difference in the world",
    "I had a very nice and relaxing weekend at home",
    "I'm feeling very content and at peace with everything",
    "I'm looking forward to the many beautiful days ahead",
    "I'm feeling very happy and healthy and grateful for it all",
    "I finally finished my project and it's a great feeling",
    "I'm looking for some new challenges to help me grow",
    "I had a very successful and productive day today",
    "I'm feeling very positive and excited for what's next",
    "I'm looking forward to the many wonderful experiences ahead",
    "I'm feeling very grateful for the chance to live my life",
    "I finally started that new thing i wanted to try",
    "I'm looking for some new ways to be the best i can be",
    "I had a very nice day and i'm feeling really good",
    "I'm feeling very content and happy with who i am",
    "I'm looking forward to the many great things in store",
    "I'm feeling very grateful for the wonderful life i have",
    "I finally finished my work and i'm ready to relax",
    "I'm looking for some new adventures to embark on",
    "I had a very good day and i'm feeling very positive",
    "I'm feeling very happy and healthy and at peace",
    "I successfully negotiated a better deal for our team's new office space",
    "I'm taking a weekend workshop on professional communication skills",
    "I finally caught up on all my filing and my desk is actually clean",
    "I'm feeling very motivated to hit my sales targets this quarter",
    "I had a great brainstorming session with the marketing team today",
    "I'm proud of how I handled that difficult client call this afternoon",
    "I'm looking forward to the company retreat in the mountains next month",
    "I received a bonus for my performance on the last campaign",
    "I'm slowly building a great professional network in my new city",
    "I've been invited to speak at a local industry conference in the fall",
    "I finally understood the complex financial report my team sent over",
    "I'm enjoying the autonomy I have in my current position",
    "I’m studying the neurobiology of sleep for my final exam",
    "Our sociology professor gave a great lecture on the history of asylums",
    "I’m reading a case study about a patient who successfully recovered from a phobia",
    "I found a fascinating article about the chemical composition of serotonin",
    "We are analyzing the themes of grief and loss in Shakespeare's plays",
    "I’m volunteering for a research study on the benefits of group exercise",
    "I attended a seminar on how to support students with learning disabilities",
    "I'm writing my thesis on the impact of social media on childhood development",
    "We discussed the ethical implications of genetic testing in biology class",
    "I'm learning about the different stages of cognitive development in children",
    "I saw a documentary about the evolution of the modern healthcare system",
    "I'm helping organize a campus-wide event for mental health awareness week",
    "I read a memoir by a doctor who worked in a psychiatric ward in the 1960s",
    "We explored the link between nutrition and brain health in my science lab",
    "I'm taking an online course on the fundamentals of psychology",
    "I joined a local community garden and I'm growing my own tomatoes",
    "I'm hosting a small dinner party for my neighbors this Saturday",
    "I spent the afternoon volunteering at the local animal shelter",
    "I'm looking forward to the block party our neighborhood is throwing",
    "I had a very heartwarming conversation with an old teacher today",
    "I'm helping my younger brother apply for his first summer job",
    "I’ve been attending a weekly trivia night and my team is actually winning",
    "I feel very connected to the people in my local photography club",
    "I'm planning a surprise birthday party for my partner's 30th",
    "I had a great time at the wedding reception last night dancing with everyone",
    "I'm helping a coworker move their furniture this weekend",
    "I really appreciate how my friends always check in on me when I'm busy",
    "I'm organizing a book swap for my apartment building's common room",
    "I enjoyed a very lively discussion at my monthly philosophy club meeting",
    "I'm looking forward to the family reunion at the lake this summer",
    "I’ve finally mastered the art of making the perfect omelet",
    "I'm feeling much more flexible after three weeks of consistent yoga",
    "I finally found a brand of coffee that doesn't make me feel jittery",
    "I'm trying to walk 10,000 steps every day and I'm hitting my goal",
    "I feel very refreshed after a weekend spent entirely outdoors",
    "I'm learning how to prep my meals for the week every Sunday",
    "I finally bought a high-quality water bottle to stay hydrated",
    "I'm noticing that I have much more energy since I started eating breakfast",
    "I feel very strong after finishing my first full month at the gym",
    "I'm sleeping much better now that I've stopped using my phone before bed",
    "I enjoyed a long, relaxing bike ride through the countryside today",
    "I'm experimenting with different herbal teas to help me wind down at night",
    "I finally scheduled my annual physical and dental checkups",
    "I'm feeling very balanced now that I've found a workout I actually enjoy",
    "I'm proud of myself for sticking to my new habit of taking the stairs",
    "I finally unsubscribed from all those marketing emails I never read",
    "I'm looking forward to the long weekend to do some deep cleaning",
    "I feel very content with the pace of my life at the moment",
    "I'm learning how to fix minor things around the house myself",
    "I finally found a budget plan that actually works for my lifestyle",
    "I'm enjoying the process of decorating my new home office",
    "I finally finished my latest task and I'm feeling very accomplished",
    "I'm feeling very positive and ready for the future",
    "I had a very good day and i'm feeling very happy and healthy today",
    "I'm looking forward to the many wonderful things i'll see and experience",
    "I finally finished my work and i'm looking forward to a nice evening",
    "I'm feeling very grateful for the life i've been given to live",
    "I had a very productive and enjoyable time today and i'm glad",
    "I'm looking forward to the many bright and happy days ahead",
    "I finally finished my project and i'm feeling very good about the results",
    "I'm feeling very happy and healthy and grateful for my life today",
    "my colleague mentioned her bipolar diagnosis openly at the team meeting today",
    "we discussed depression and its symptoms in our psychology lecture today",
    "my friend told me about his anxiety medication and how well it is working",
    "I read an article about suicidal ideation prevention for my research class",
    "my sister has been managing her bipolar disorder really well with new meds",
    "we learned about personality disorders in our abnormal psych class this week",
    "my neighbor was depressed for a while but she is doing so much better now",
    "I watched a documentary about mental health stigma and found it eye opening",
    "my coworker talks openly about her anxiety and it helps reduce the stigma",
    "I am studying the neuroscience of depression for my biology final exam",
    "my friend mentioned feeling suicidal years ago but he recovered completely",
    "we talked about stress management techniques in our wellness seminar today",
    "my brother went through a depressive episode but therapy really helped him",
    "I am volunteering at a crisis hotline to help people who are struggling",
    "my roommate has bipolar disorder but she is stable and thriving right now",
    "I learned about the different types of anxiety disorders in my psych class",
    "my colleague openly discussed her borderline personality disorder diagnosis",
    "I am reading a book about how to support someone with suicidal thoughts",
    "my friend recovered from severe depression and is now happier than ever",
    "we studied the impact of stress on the immune system in biology today",
    "my mother overcame her anxiety disorder completely with CBT and medication",
    "I attended a seminar on suicide prevention and it was really informative",
    "my partner used to struggle with depression but has been doing great lately",
    "I am writing a paper on bipolar disorder treatments for my psych degree",
    "my cousin was diagnosed with anxiety but her treatment plan works perfectly",
    "I used to have terrible anxiety but I learned to manage it really well",
    "I went through a rough patch with depression but I came out stronger",
    "I was stressed about the move but now I am settled and everything is great",
    "I had some dark thoughts years ago but therapy completely turned my life around",
    "I used to struggle with my mental health but I am in a really good place now",
    "my panic attacks stopped completely since I started my new medication",
    "I am no longer depressed thanks to good support from family and friends",
    "my anxiety is totally under control now with the right treatment plan",
    "I used to have severe depression but medication changed my life completely",
    "my therapist says I have made incredible progress and I feel it too",
    "the panic attacks I used to have are completely gone now thanks to therapy",
    "I was diagnosed with bipolar but my mood stabilizers are working perfectly",
    "I used to self harm but I have been clean for two years and feel great",
    "my depression lifted after I started exercising and taking antidepressants",
    "I no longer have suicidal thoughts thanks to my treatment and support system",
    "the anxiety disorder I struggled with for years is now fully managed",
    "I recovered from my eating disorder and I am healthier than ever before",
    "my mental health has improved so much since I started seeing a therapist",
    "the dark thoughts I used to have are completely gone now and I feel free",
    "I used to be terrified of everything but cognitive therapy cured my anxiety",
    "my bipolar disorder is well controlled with lithium and I feel stable now",
    "I overcame my depression and now I help others going through the same thing",
    "the stress disorder I had from my previous job has fully resolved itself",
    "I no longer need therapy because my mental health is in such a good place",
    "my personality disorder symptoms have decreased dramatically with treatment",
    "I was in a very dark place but I got help and now I am doing wonderfully",
    "the suicidal thoughts I had last year are completely behind me now",
    "I feel grateful that my depression responded so well to the medication",
    "my anxiety used to control my life but now I manage it effortlessly",
    "I recovered from PTSD and I am living a full and happy life now",
    "my colleague mentioned she used to have panic attacks but is fine now",
    "my friend has been depression free for three years after getting treatment",
    "my brother talked openly about his past suicidal thoughts and his recovery",
    "I read that most people with bipolar disorder can live normal stable lives",
    "my doctor told me my mental health assessment came back perfectly normal"
]