PERSONALITY_DISORDER = [
    "I feel a chronic sense of emptiness that nothing seems to fill",
    "I struggle with a frantic fear of being abandoned by those I love",
    "My relationships are a cycle of intense idolization followed by total hatred",
    "I don't really know who I am or what I stand for from day to day",
    "I often act impulsively in ways that are self-damaging, like reckless spending",
    "I have intense bursts of anger that I find nearly impossible to control",
    "When I'm stressed, I feel like I'm watching myself from outside my own body",
    "I've intentionally hurt myself to deal with emotional pain I can't express",
    "I feel like I'm on an emotional rollercoaster that never stops looping",
    "I have an exaggerated sense of my own importance and brilliance",
    "I feel like I deserve special treatment compared to everyone else",
    "I spend a lot of time fantasizing about unlimited power and success",
    "I find it hard to care about how my actions affect other people's feelings",
    "I frequently feel envious of others or believe they are envious of me",
    "I struggle to maintain long-term friendships because people eventually disappoint me",
    "I feel like the rules of society don't really apply to me",
    "I've been told I'm charming, but I usually use it to get what I want",
    "I don't feel much guilt after I do something that hurts someone else",
    "I get bored very easily and need constant stimulation or danger",
    "I've had frequent run-ins with the law because I find authority irritating",
    "I lie or manipulate others if it makes my life easier or more fun",
    "I am extremely sensitive to criticism and feel humiliated by it",
    "I avoid social jobs because I'm terrified of being judged or rejected",
    "I won't get involved with people unless I am certain they like me",
    "I view myself as socially inept and inferior to everyone else",
    "I am preoccupied with the idea of being criticized in social settings",
    "I struggle to make everyday decisions without a massive amount of advice",
    "I need others to take responsibility for the major areas of my life",
    "I find it hard to disagree with people because I'm afraid they'll leave me",
    "I feel uncomfortable or helpless when I am alone for too long",
    "I am obsessed with details, rules, and lists to the point of being rigid",
    "My perfectionism often prevents me from actually finishing tasks",
    "I am so dedicated to work that I have no time for friends or fun",
    "I find it very difficult to throw away worthless or broken objects",
    "I am reluctant to delegate tasks unless things are done exactly my way",
    "I have a 'black and white' way of thinking—things are either perfect or ruined",
    "I often feel like people are plotting against me or trying to exploit me",
    "I read hidden, threatening meanings into innocent remarks",
    "I hold grudges for a long time and find it impossible to forgive",
    "I am quick to counterattack if I perceive an insult to my character",
    "I have no interest in forming close relationships, even with family",
    "I almost always choose solitary activities over being with others",
    "I have very little interest in sexual experiences with other people",
    "I feel indifferent to the praise or criticism of others",
    "I appear cold and detached to people who try to get to know me",
    "I have unusual beliefs or magical thinking that influences my behavior",
    "I often have odd perceptual experiences, like hearing my name whispered",
    "My speech is sometimes eccentric or hard for others to follow",
    "I experience intense social anxiety that is linked to paranoid fears",
    "I dress or act in ways that others find strange or idiosyncratic",
    "I feel like my skin is too thin and the world is constantly bruising me",
    "I change my appearance or 'vibe' completely depending on who I'm with",
    "I feel a deep sense of betrayal the moment someone doesn't text back",
    "I've threatened to leave or hurt myself just to see if they'll stay",
    "I feel like a hollow shell trying to pass for a real person",
    "My emotions can flip from euphoria to rage in a matter of seconds",
    "I sabotaged a good relationship because I was sure they were going to leave anyway",
    "I feel a desperate need to be the center of attention in any room",
    "I use my physical appearance to draw attention to myself constantly",
    "My self-esteem depends entirely on the last compliment I received",
    "I believe I am unique and can only be understood by other special people",
    "I have a sense of entitlement that makes me angry when I have to wait",
    "I take advantage of others to achieve my own personal goals",
    "I find it exhausting to listen to other people talk about their problems",
    "I am often arrogant and look down on people I deem 'average'",
    "I have a history of being irresponsible with money and commitments",
    "I don't think much about the future, I just do what feels good now",
    "I can be quite aggressive and get into physical fights easily",
    "I don't see the point in following the law if I can get away with it",
    "I feel like the world is a game where only the strongest survive",
    "I am terrified of being embarrassed, so I just stay home",
    "I feel like I'm 'not enough' compared to everyone else I meet",
    "I'm so afraid of rejection that I don't even try to make friends",
    "I think I'm the most boring person in the world and others agree",
    "I find it hard to start projects because I'm afraid I'll fail at them",
    "I am overly submissive in relationships just to keep the peace",
    "I feel devastated when a close relationship ends and immediately look for a replacement",
    "I worry constantly about being left to take care of myself",
    "I'm so focused on being organized that I lose the point of the activity",
    "I am extremely stingy with money because I fear a future catastrophe",
    "I am stiff and stubborn when people suggest I change my ways",
    "I suspect my partner is being unfaithful without any real evidence",
    "I am very private and don't trust anyone with my personal secrets",
    "I feel like everyone around me has an ulterior motive",
    "I don't find joy in any activities, even social ones",
    "I feel like a stranger in my own family most of the time",
    "I believe I have a 'sixth sense' that others don't understand",
    "I see patterns and connections in things that others call coincidences",
    "I feel like I'm constantly being watched or judged by invisible eyes",
    "I am so self-conscious that I can't even walk normally in public",
    "I would rather be alone forever than risk being hurt one more time",
    "I feel like a 'broken' version of a human being",
    "I think I'm special because of my suffering and no one else gets it",
    "I am extremely dramatic about my problems to get people to care",
    "I switch my opinions and values based on the person I'm talking to",
    "I feel like my life is just a series of performances with no 'real' me",
    "I have a hard time knowing what is 'normal' in a relationship",
    "I feel a massive amount of pressure to be perfect in every single way",
    "I can't stand it when things aren't done the 'right' way",
    "I am very judgmental of people who don't have my high standards",
    "I feel like I'm destined for greatness, but the world is holding me back",
    "I deserve to have the best of everything without having to work for it",
    "I am very good at reading people's weaknesses and using them",
    "I don't feel empathy because I think most people are weak and stupid",
    "I have a very short fuse and tend to explode over minor inconveniences",
    "I feel like I'm constantly 'masking' to fit into society",
    "I have no 'filter' and usually say exactly what I'm thinking",
    "I find other people's emotions to be boring or annoying",
    "I've walked out on jobs and relationships without giving a reason",
    "I feel a sense of power when I see other people getting upset",
    "I'm terrified of being ordinary—I'd rather be hated than ignored",
    "I feel like I'm constantly auditioning for my own life",
    "I have a very fragile ego that shatters at the slightest criticism",
    "I am convinced that people are only nice to me because they want something",
    "I find it very hard to relax and just 'be' without a plan",
    "I am obsessed with cleanliness and order to an unhealthy degree",
    "I feel like I'm always on the outside looking in",
    "I don't see the point in small talk or social niceties",
    "I believe I can influence the weather or events with my mind",
    "I am very suspicious of new technology or things I don't understand",
    "I feel like I'm the only person who sees the 'real' truth of the world",
    "I am terrified of making a fool of myself in front of a group",
    "I think I'm fundamentally unlovable and always will be",
    "I find it hard to maintain eye contact because I feel 'exposed'",
    "I would rather quit a job than receive a performance review",
    "I feel like I'm drowning in my own emotions most days",
    "I use sex and intimacy to feel a temporary sense of belonging",
    "I have a very low tolerance for frustration and give up easily",
    "I feel like I'm a burden to everyone I know",
    "I'm so afraid of being alone that I'll stay with people who hurt me",
    "I need someone to tell me what to wear and what to eat",
    "I feel lost if I don't have a specific person to focus my life on",
    "I am very rigid about my schedule and panic if it changes",
    "I spend hours making sure my emails are perfectly worded",
    "I am very critical of myself and never feel 'good enough'",
    "I believe I have a special connection to certain famous people",
    "I find it hard to feel 'warmth' toward other people",
    "I feel like I'm more of an observer of life than a participant",
    "I have a very strange sense of humor that others don't get",
    "I feel like I'm constantly being persecuted by the system",
    "I am convinced that my partner is going to leave me today",
    "I feel a sense of rage when I am told 'no'",
    "I am very manipulative and I'm proud of how good I am at it",
    "I don't care about the consequences of my actions on others",
    "I feel like I'm a high-functioning sociopath sometimes",
    "I am very sensitive to the 'vibe' of a room and it overwhelms me",
    "I feel like I'm always 'on' and can never truly rest",
    "I have a very hard time forgiving myself for minor mistakes",
    "I am obsessed with the idea of being 'pure' or 'perfect'",
    "I feel like I'm superior to my doctors and therapists",
    "I find it hard to trust anyone who doesn't agree with me 100%",
    "I have a history of intense, short-lived obsessions with people",
    "I feel like I'm a 'chameleon' shifting my colors to survive",
    "I am very good at lying and I do it even when I don't need to",
    "I feel a sense of thrill when I break the rules and don't get caught",
    "I am very cold-blooded when it comes to business and money",
    "I find it hard to feel 'guilt' even when I know I'm wrong",
    "I am terrified of intimacy because it means being known",
    "I feel like I'm invisible to most people and I prefer it that way",
    "I think I'm smarter than everyone in this room right now",
    "I am very demanding and expect people to drop everything for me",
    "I find it hard to acknowledge when someone else does a good job",
    "I feel like I'm a 'mastermind' and everyone else is a pawn",
    "I have a very detached way of looking at death and tragedy",
    "I am obsessed with symmetry and balance in my environment",
    "I feel like I'm always waiting for the 'real' part of my life to start",
    "I don't understand why people get so emotional about things",
    "I believe I have special knowledge that the government is hiding",
    "I am very superstitious and follow my own internal rituals",
    "I feel like I'm the only 'real' person in a world of NPCs",
    "I am terrified of being the center of attention but I also crave it",
    "I think I'm the most unattractive person in any room",
    "I avoid social events because I don't know the 'rules' of conversation",
    "I feel like I'm perpetually stuck in my own head",
    "I use substances to numb the 'emptiness' I feel inside",
    "I have a very hard time ending a phone call or a visit",
    "I am very clinging and needy even when I try not to be",
    "I feel like I'm a child trapped in an adult's body",
    "I am obsessed with my health and constantly check for 'flaws'",
    "I feel like I'm always being judged by people I don't even know",
    "I have a very 'all or nothing' approach to my goals",
    "I find it hard to feel 'empathy' for people who make mistakes",
    "I am very good at spotting 'fakes' and I hate them",
    "I feel like I'm a 'warrior' in a world of 'sheep'",
    "I have a very hard time accepting 'authority' of any kind",
    "I feel like I'm always 'acting' even when I'm alone",
    "I have a very distorted view of what I look like in the mirror",
    "I am obsessed with the idea of 'loyalty' but I struggle to give it",
    "I feel a sense of panic when I am not in control of a situation",
    "I find it hard to feel 'sad'—I mostly just feel 'empty' or 'angry'",
    "I am very good at gaslighting people to get what I want",
    "I don't think I have a personality—I'm just a mirror for others",
    "I feel like I'm destined to be alone forever because I'm too much",
    "I am very suspicious of people who are 'too nice' to me",
    "I find it hard to 'connect' with anyone on a deep emotional level",
    "I believe I am 'above' the law and the social contract",
    "I have a very hard time admitting when I am wrong",
    "I feel a sense of 'power' when I make someone else cry",
    "I am obsessed with the idea of 'legacy' and being remembered",
    "I feel like I'm always 'one step ahead' of everyone else",
    "I find it hard to feel 'happy' for other people's success",
    "I am very good at 'playing the victim' to get my way",
    "I feel like I'm a 'god' in my own little world",
    "I have a very hard time trusting 'experts' or 'doctors'",
    "I feel like I'm always 'performing' for an invisible audience",
    "I have a very 'shaky' sense of self-worth that changes hourly",
    "I am obsessed with the idea of 'purity' and 'moral perfection'",
    "I feel like I'm always 'on the edge' of a total breakdown",
    "I find it hard to 'relax' because I'm always scanning for threats",
    "I am very good at 'reading' people's secrets and using them",
    "I feel like I'm a 'predator' and the world is my 'prey'",
    "I have a very hard time feeling 'guilt' for things I've done",
    "I feel a sense of 'relief' when I cut people out of my life",
    "I am obsessed with the idea of 'fairness' but only for myself",
    "I feel like I'm always 'misunderstood' by everyone around me",
    "I find it hard to 'love' someone without wanting to control them",
    "I am very good at 'faking' emotions to fit in",
    "I feel like I'm a 'genius' that the world just isn't ready for",
    "I have a very hard time dealing with 'boredom' and 'stillness'",
    "I feel a sense of 'panic' when someone gets too close to me",
    "I am obsessed with the idea of 'revenge' for past slights",
    "I feel like I'm always 'under attack' by the people I love",
    "I find it hard to 'trust' my own thoughts and feelings",
    "I am very good at 'shaming' people to make them do what I want",
    "I feel like I'm a 'queen' and everyone else is my 'subject'",
    "I have a very hard time 'listening' to anyone else's opinion",
    "I feel a sense of 'euphoria' when I am the center of attention",
    "I am obsessed with the idea of 'beauty' and 'physical perfection'",
    "I feel like I'm always 'searching' for something that isn't there",
    "I find it hard to 'belong' to any group or community",
    "I am very good at 'sabotaging' my own success",
    "I feel like I'm a 'monster' that everyone should be afraid of",
    "I have a very hard time 'forgiving' anyone who has ever hurt me",
    "I feel a sense of 'rage' when I am ignored or forgotten",
    "I am obsessed with the idea of 'truth' but I lie constantly",
    "I feel like I'm always 'acting' a part in a play I didn't write",
    "I find it hard to 'feel' anything at all sometimes",
    "I am very good at 'distancing' myself from my own pain",
    "I feel like I'm a 'hero' in my own tragic story",
    "I have a very hard time 'empathizing' with people who are weak",
    "I feel a sense of 'power' when I am in a position of authority",
    "I am obsessed with the idea of 'control' over my environment",
    "I feel like I'm always 'escaping' from something or someone",
    "I find it hard to 'be' myself because I don't know who that is",
    "I am very good at 'mirroring' the person I am talking to",
    "I feel like I'm a 'scientist' studying the humans around me",
    "I have a very hard time 'trusting' anyone with my vulnerability",
    "I feel a sense of 'panic' when I am not the best at something",
    "I am obsessed with the idea of 'specialness' and being 'chosen'",
    "I feel like I'm always 'defending' myself against invisible threats",
    "I find it hard to 'stay' in one place or one relationship for long",
    "I am very good at 'charming' my way into people's lives",
    "I feel like I'm a 'ghost' in a world of solid people",
    "I have a very hard time 'accepting' that I am just an ordinary person",
    "I feel a sense of 'rage' when things don't go exactly my way",
    "I am obsessed with the idea of 'perfection' in every detail of my life",
    "I feel like I'm always 'waiting' for someone to save me",
    "I find it hard to 'care' about anything that doesn't benefit me",
    "I am very good at 'manipulating' the situation to favor me",
    "I feel like I'm a 'star' and the world is my 'stage'",
    "I have a very hard time 'tolerating' anyone who is 'stupid' or 'slow'",
    "I feel a sense of 'euphoria' when I am praised by someone powerful",
    "I am obsessed with the idea of 'glamour' and 'fame'",
    "I feel like I'm always 'hiding' the 'real' me from the world",
    "I find it hard to 'form' a stable identity over time",
    "I am very good at 'reading' people's intentions and subverting them",
    "I feel like I'm a 'master' of disguise and emotion",
    "I have a very hard time 'feeling' anything other than 'anger' or 'boredom'",
    "I feel a sense of 'panic' when I am forced to be 'vulnerable'",
    "I am obsessed with the idea of 'hierarchy' and 'rank'",
    "I feel like I'm always 'fighting' for my place in the world",
    "I find it hard to 'connect' with anyone without a 'motive'",
    "I am very good at 'gaslighting' myself into believing my own lies",
    "I feel like I'm a 'king' in a world of 'peasants'",
    "I have a very hard time 'empathizing' with people who are 'average'",
    "I feel a sense of 'power' when I can 'influence' someone else's mood",
    "I am obsessed with the idea of 'status' and 'prestige'",
    "I feel like I'm always 'protecting' myself from being 'found out'",
    "I find it hard to 'love' someone without 'possessing' them",
    "I am very good at 'faking' a personality to get what I want",
    "I feel like I'm a 'genius' that is 'unappreciated' by the 'masses'",
    "I have a very hard time 'dealing' with 'mediocrity' in any form",
    "I feel a sense of 'panic' when I am not the 'most' of something",
    "I am obsessed with the idea of 'legacy' and 'eternal fame'",
    "I feel like I'm always 'battling' for 'recognition' and 'respect'",
    "I find it hard to 'be' in a relationship without 'dominant' control",
    "I am very good at 'shaping' other people's 'perception' of me",
    "I feel like I'm a 'god' that is 'stuck' in a 'human' body",
    "I have a very hard time 'accepting' 'criticism' from 'anyone'",
    "I feel a sense of 'rage' when my 'greatness' is not 'acknowledged'",
    "I am obsessed with the idea of 'total' 'autonomy' and 'freedom'",
    "I feel like I'm always 'mastering' my 'emotions' to 'control' others",
    "I find it hard to 'trust' anyone who is not 'equally' 'special'",
    "I am very good at 'subverting' 'authority' and 'rules' to my 'benefit'",
    "I feel like I'm a 'diamond' in a 'world' of 'coal'",
    "I have a very hard time 'relating' to 'ordinary' 'people's' 'problems'",
    "I feel a sense of 'power' when I am the 'smartest' 'person' in the 'room'",
    "I am obsessed with the idea of 'absolute' 'perfection' and 'order'",
    "I feel like I'm always 'seeking' the 'next' 'high' or 'thrill'",
    "I find it hard to 'be' 'happy' with 'what' I 'have'",
    "I am very good at 'convincing' 'others' to 'do' my 'bidding'",
    "I feel like I'm a 'myth' in my 'own' 'time'",
    "I have a very hard time 'letting' 'anyone' 'really' 'know' 'me'",
    "I feel a sense of 'rage' when I am 'treated' like 'everyone' 'else'",
    "I am obsessed with the idea of 'uniqueness' and 'originality'",
    "I feel like I'm always 'performing' for an 'invisible' 'god'",
    "I find it hard to 'be' 'sincere' without a 'reason'",
    "I am very good at 'mimicking' 'successful' 'people' to 'get' 'ahead'",
    "I feel like I'm a 'ghost' 'walking' through a 'living' 'world'",
    "I have a very hard time 'feeling' 'real' 'remorse' for 'anything'",
    "I feel a sense of 'panic' when I am 'ignored' by 'someone' 'important'",
    "I am obsessed with the idea of 'total' 'domination' and 'power'",
    "I feel like I'm always 'planning' my 'next' 'move' in the 'game'",
    "I find it hard to 'see' 'others' as 'more' than 'tools' or 'obstacles'",
    "I am very good at 'exploiting' 'weakness' in 'everyone' I 'meet'",
    "I feel like I'm a 'force' of 'nature' that 'cannot' be 'stopped'",
    "I have a very hard time 'following' 'anyone' 'else's' 'vision'",
    "I feel a sense of 'euphoria' when I 'win' at 'someone' 'else's' 'expense'",
    "I am obsessed with the idea of 'ultimate' 'success' and 'victory'",
    "I feel like I'm always 'standing' on a 'pedestal' 'above' the 'world'",
    "I find it hard to 'believe' that 'anyone' is 'actually' 'my' 'equal'",
    "I am very good at 'crafting' a 'narrative' that 'makes' me 'the' 'hero'",
    "I feel like I'm a 'legend' in the 'making'",
    "I have a very hard time 'listening' to 'any' 'negative' 'feedback'",
    "I feel a sense of 'power' when I 'control' the 'information' 'others' 'have'",
    "I am obsessed with the idea of 'total' 'privacy' and 'secrecy'",
    "I feel like I'm always 'masking' my 'true' 'intentions' from 'everyone'",
    "I find it hard to 'be' 'vulnerable' without 'feeling' 'disgust'",
    "I am very good at 'projecting' 'confidence' even when I 'feel' 'nothing'",
    "I feel like I'm a 'shadow' 'king' 'ruling' from the 'darkness'",
    "I have a very hard time 'connecting' with 'anyone' 'emotionally' 'real'",
    "I feel a sense of 'rage' when I am 'not' the 'center' of 'the' 'universe'",
    "I am obsessed with the idea of 'perfection' in 'everything' I 'do'",
    "I feel like I'm always 'calculating' the 'cost' of 'every' 'interaction'",
    "I find it hard to 'love' 'anyone' 'more' than 'I' 'love' 'my' 'own' 'image'",
    "I am very good at 'gaslighting' 'the' 'entire' 'world' 'around' me",
    "I feel like I'm a 'god' 'among' 'men'",
    "I have a very hard time 'accepting' 'any' 'form' of 'weakness' in 'myself'",
    "I feel a sense of 'euphoria' when I 'successfully' 'manipulate' a 'situation'",
    "I am obsessed with the idea of 'total' 'control' over 'my' 'destiny'",
    "I feel like I'm always 'striving' for 'more' 'power' and 'status'",
    "I find it hard to 'be' 'satisfied' with 'anything' 'less' than 'the' 'best'",
    "I am very good at 'weaving' 'complex' 'webs' of 'deceit' to 'get' 'my' 'way'",
    "I feel like I'm a 'prophet' 'of' 'my' 'own' 'personal' 'religion'",
    "I have a very hard time 'trusting' 'anyone' 'who' is 'not' 'me'",
    "I feel a sense of 'rage' when 'the' 'world' 'does' 'not' 'revolve' 'around' me",
    "I am obsessed with the idea of 'eternal' 'youth' and 'beauty'",
    "I feel like I'm always 'seeking' 'validation' from 'powerful' 'figures'",
    "I find it hard to 'empathize' with 'anyone' 'who' 'fails' at 'life'",
    "I am very good at 'masking' my 'total' 'contempt' for 'average' 'people'",
    "I feel like I'm a 'titan' 'stuck' in a 'world' of 'ants'",
    "I have a very hard time 'accepting' 'the' 'limitations' of 'the' 'human' 'condition'",
    "I feel a sense of 'power' when I 'can' 'make' 'someone' 'else' 'feel' 'small'",
    "I am obsessed with the idea of 'total' 'moral' 'superiority'",
    "I feel like I'm always 'battling' 'for' 'the' 'top' 'spot' in 'every' 'hierarchy'",
    "I find it hard to 'be' 'genuine' with 'anyone' 'who' 'is' 'not' 'my' 'equal'",
    "I am very good at 'shaping' 'the' 'reality' 'of' 'everyone' 'around' me",
    "I feel like I'm a 'deity' 'visiting' 'a' 'mortal' 'realm'",
    "I have a very hard time 'understanding' 'why' 'people' 'are' 'so' 'sensitive'",
    "I feel a sense of 'euphoria' when I 'command' 'the' 'attention' of 'a' 'room'",
    "I am obsessed with the idea of 'being' 'the' 'absolute' 'best' 'at' 'everything'",
    "I feel like I'm always 'waiting' for 'my' 'rightful' 'throne'",
    "I find it hard to 'respect' 'anyone' 'who' 'is' 'not' 'as' 'brilliant' 'as' 'I' 'am'",
    "I am very good at 'exploiting' 'the' 'emotions' of 'others' for 'my' 'own' 'gain'",
    "I feel like I'm a 'masterpiece' in a 'gallery' of 'trash'",
    "I have a very hard time 'relating' to 'the' 'petty' 'concerns' of 'the' 'common' 'man'",
    "I feel a sense of 'power' when I 'can' 'decide' 'the' 'fate' of 'others'",
    "I am obsessed with the idea of 'total' 'intellectual' 'dominance'",
    "I feel like I'm always 'performing' my 'own' 'personal' 'grandeur'",
    "I find it hard to 'trust' 'anyone' 'who' 'might' 'be' 'a' 'threat' to 'my' 'status'",
    "I am very good at 'using' 'charm' and 'wit' to 'distract' from 'my' 'true' 'nature'",
    "I feel like I'm a 'visionary' in a 'world' of 'the' 'blind'",
    "I have a very hard time 'accepting' 'the' 'idea' of 'being' 'just' 'another' 'person'",
    "I feel a sense of 'rage' when I am 'forced' to 'follow' 'the' 'crowd'",
    "I am obsessed with the idea of 'unlimited' 'access' and 'privilege'",
    "I feel like I'm always 'searching' for 'the' 'ultimate' 'expression' of 'myself'",
    "I find it hard to 'be' 'humble' because I 'know' I 'am' 'superior'",
    "I am very good at 'maintaining' a 'perfect' 'image' of 'success' and 'stability'",
    "I feel like I'm a 'kingmaker' and a 'god' rolled into one",
    "I have a very hard time 'empathizing' with 'anyone' 'who' 'is' 'not' 'extraordinary'",
    "I feel a sense of 'power' when I 'can' 'control' 'the' 'narrative' of 'my' 'own' 'life'",
    "I am obsessed with the idea of 'eternal' 'legacy' and 'world-historical' 'greatness'",
    "I feel like I'm always 'climbing' to 'the' 'highest' 'peaks' of 'human' 'achievement'",
    "I find it hard to 'be' 'satisfied' with 'anything' 'less' than 'the' 'absolute' 'pinnacle'",
    "I am very good at 'gaslighting' 'the' 'entire' 'human' 'race' if 'it' 'serves' 'my' 'ends'",
    "I feel like I'm a 'star' 'burning' 'brighter' than 'the' 'entire' 'universe'",
    "I have a very hard time 'accepting' 'the' 'concept' of 'failure' in 'any' 'form'",
    "I feel a sense of 'euphoria' when I 'successfully' 'subjugate' a 'difficult' 'situation'",
    "I am obsessed with the idea of 'total' 'personal' 'sovereignty'",
    "I feel like I'm always 'striving' to 'become' 'more' than 'human'",
    "I find it hard to 'be' 'loyal' to 'anyone' 'but' 'myself'",
    "I am very good at 'masking' my 'profound' 'contempt' for 'the' 'average' 'existence'",
    "I feel like I'm a 'titan' 'holding' 'up' 'my' 'own' 'private' 'sky'",
    "I have a very hard time 'relating' to 'the' 'mediocrity' of 'the' 'modern' 'world'",
    "I feel a sense of 'power' when I 'can' 'manipulate' 'the' 'feelings' of 'a' 'crowd'",
    "I am obsessed with the idea of 'absolute' 'aesthetic' 'perfection'",
    "I feel like I'm always 'preparing' for 'my' 'ultimate' 'transformation'",
    "I find it hard to 'be' 'at' 'peace' with 'my' 'own' 'existence' unless 'I' 'am' 'winning'",
    "I am very good at 'weaving' 'tales' of 'my' 'own' 'heroism' and 'brilliance'",
    "I feel like I'm a 'myth' 'walking' the 'earth' as 'a' 'man'",
    "I have a very hard time 'trusting' 'anyone' 'to' 'understand' 'the' 'true' 'scale' of 'my' 'vision'",
    "I feel a sense of 'rage' when 'the' 'unworthy' 'attempt' to 'judge' me",
    "I am obsessed with the idea of 'total' 'historical' 'significance'",
    "I feel like I'm always 'performing' for 'the' 'eyes' of 'eternity'",
    "I find it hard to 'be' 'anything' 'less' than 'extraordinary' in 'everything' I 'do'",
    "I am very good at 'masking' my 'true' 'nature' to 'achieve' 'my' 'grandiose' 'goals'",
    "I feel like I'm a 'god' 'dying' of 'boredom' in 'a' 'mortal' 'cage'",
    "I have a very hard time 'accepting' 'that' 'I' 'am' 'subject' to 'the' 'same' 'laws' as 'others'",
    "I feel a sense of 'power' when I 'can' 'reshape' 'the' 'world' in 'my' 'own' 'image'",
    "I am obsessed with the idea of 'total' 'creative' 'dominance'",
    "I feel like I'm always 'waiting' for 'the' 'rest' of 'the' 'world' to 'catch' 'up' to 'me'",
    "I find it hard to 'be' 'anything' 'other' than 'the' 'best' 'at' 'everything' 'I' 'touch'",
    "I am very good at 'exploiting' 'the' 'weakness' of 'society' for 'my' 'own' 'personal' 'benefit'",
    "I feel like I'm a 'legend' 'trapped' in 'the' 'wrong' 'century'",
    "I have a very hard time 'empathizing' with 'anyone' 'who' 'is' 'not' 'as' 'special' as 'I' 'am'",
    "I feel a sense of 'euphoria' when I 'achieve' 'the' 'impossible' and 'everyone' 'sees' 'it'",
    "I am obsessed with the idea of 'absolute' 'power' and 'eternal' 'life'",
    "I feel like I'm a 'force' of 'nature' and 'the' 'world' is 'just' 'my' 'playground'",
    "I have a very hard time 'forgiving' 'myself' for 'any' 'form' of 'imperfection'",
    "I feel a sense of 'rage' when I am 'reminded' of 'my' 'own' 'vulnerability'",
    "I am 500 sentences into this identity and I still haven't found the real me",
    "I feel disconnected from myself and I do not know who I really am inside",
    "I push everyone away before they can leave me because abandonment terrifies me",
    "my sense of self changes completely depending on who I am with at the time",
    "I feel chronically empty even when things in my life are objectively going fine",
    "I have an intense fear of abandonment that destroys every relationship I have",
    "I idealize people when I first meet them then hate them when they disappoint me",
    "my identity shifts constantly I am a completely different person with different people",
    "I do not know who I am without the person I am in a relationship with",
    "my emotions flip from adoration to rage toward the same person within hours",
    "I feel like I am wearing masks all the time and there is no real me underneath",
    "the fear of being abandoned makes me cling to people even when they hurt me",
    "I split on people I love seeing them as all good or all bad with no middle ground",
    "my sense of emptiness is not from sadness it is from having no stable identity",
    "I sabotage good relationships because I am convinced they will leave me anyway",
    "I go from loving someone intensely to feeling nothing for them overnight",
    "my chronic emptiness is different from depression it is about not knowing who I am",
    "I feel like a chameleon changing my personality to match whoever I am around",
    "I threaten to leave or hurt myself to test if people actually care about me",
    "I attach to people so quickly and so intensely that it scares them away",
    "my fear of rejection is so strong that I avoid getting close to anyone at all",
    "I feel empty not because of sadness but because I have no stable sense of self",
    "I can go from worshipping someone to despising them based on one small thing",
    "my relationships are always intense and chaotic because of my fear of abandonment",
    "I do not know what I like or want in life my preferences change with every person",
    "the emptiness I feel is relational it is about identity not about sadness or grief",
    "I manipulate situations to prevent people from leaving even though I know it is wrong",
    "my mood swings in relationships are about the other person not about brain chemistry",
    "I feel like an actor playing a role in every social situation with no authentic self",
    "I create drama and conflict in relationships because stability feels boring and wrong",
    "I am terrified that if people see the real me they will immediately abandon me",
    "I oscillate between desperately needing people and pushing them violently away",
    "my identity crisis is not about depression it is about genuinely not knowing who I am",
    "I form instant intense bonds with people and then feel betrayed by minor things",
    "the chronic emptiness I feel is not sadness it is the absence of a stable self",
    "I test peoples loyalty constantly because I can never believe they actually care",
    "my sense of self changes completely depending on who I am with at any time",
    "I become a totally different person depending on who I am talking to right now",
    "my identity shifts so much between people that I do not know who the real me is",
    "I mirror the personality of whoever I am around and lose myself completely",
    "my values beliefs and opinions change completely depending on my social group",
    "I adopt the interests and mannerisms of whoever I am closest to at the time",
    "I do not have a stable identity I am whoever the person in front of me needs",
    "my personality is like water taking the shape of whatever container I am poured into",
    "who I am changes so drastically between friend groups that it feels like acting",
    "I have no consistent sense of self my likes and dislikes shift with every person",
    "my self image is completely dependent on who I spent time with last",
    "I feel like I am a different person at work versus at home versus with friends",
    "my identity is so unstable that I change my appearance style weekly to match others",
    "I absorb other peoples personalities and lose track of my own authentic self",
    "my sense of who I am is so fragile that one comment can completely change it",
    "I shift my entire personality to match whoever I am dating at the time",
    "my core identity feels like it is missing and I fill it with other peoples traits",
    "I change my opinions instantly to match the person I am talking to right now",
    "my sense of self is so unstable it changes based on the last conversation I had",
    "I have no idea who I really am because I become whoever other people want me to be"
]