STRESS = [
    # Workplace Overload & Burnout
    "my boss expects me to be on call 24/7 and I'm losing my mind",
    "I have three different managers giving me conflicting deadlines today",
    "the quarterly reports are due and I haven't slept more than four hours",
    "I feel like I'm a cog in a machine that's about to break down",
    "every time my Slack notification pings my heart starts racing",
    "I’ve spent twelve hours staring at a monitor and my eyes are burning",
    "the company restructuring is putting so much pressure on my team",
    "I am the only one who knows how to do this job and I can't take a day off",
    "being a manager is ten times more stressful than I ever imagined",
    "I have to present to the board tomorrow and I’m shaking from the pressure",
    "my professional reputation is on the line with this project",
    "I feel like I'm failing my team because I'm so overwhelmed",
    "I'm working through my lunch break for the third month in a row",
    "the commute is two hours each way and it's draining my soul",
    "I’m drowning in paperwork and bureaucratic nonsense",
    "I feel like I’m being set up to fail with this impossible quota",
    "my job is my entire identity and right now it's a nightmare",
    "I'm so burnt out I can't even remember why I liked this career",
    "the office politics are adding a whole new level of stress to my day",
    "I have 40 hours of work to do in a 20 hour window",
    
    # Physical & Somatic Symptoms of Stress
    "my neck is so stiff from sitting at this desk I can barely turn my head",
    "I've been getting these stress rashes on my arms whenever I'm at work",
    "I'm grinding my teeth so hard at night my jaw is clicking",
    "the tension in my shoulders feels like I'm carrying boulders",
    "I keep getting these sharp chest pains every time my phone rings",
    "my stomach is in knots and I haven't been able to eat a full meal",
    "I feel like I have a permanent migraine from the fluorescent lights and stress",
    "my hands are shaking too much to type properly",
    "I have a constant ringing in my ears from the pressure of these deadlines",
    "the stress is making my eczema flare up all over my face",
    "I’m so tense I feel like my muscles are made of stone",
    "I haven't had a proper bowel movement in a week because of stress",
    "my heart is constantly fluttering like a trapped bird",
    "I’m losing hair in clumps because of the amount of pressure I’m under",
    "I feel physically heavy like I'm walking through mud every day",
    
    # Academic & Student Pressure
    "finals week is destroying me I have four exams in two days",
    "I'm $50,000 in debt and I don't even know if I'll get a job",
    "the pressure to get a 4.0 GPA is making me miserable",
    "I have a 20-page paper due at midnight and I'm on page two",
    "my parents will be so disappointed if I don't get into med school",
    "I'm pulling my third all-nighter this week in the library",
    "the competition in this grad program is toxic and exhausting",
    "I feel like I’m falling behind everyone else in my class",
    "I have to balance a full-time internship with a full-time course load",
    "I'm so stressed about this thesis defense I've been vomiting",
    
    # Financial & Domestic Stress
    "I'm checking my bank account every hour to see if my check cleared",
    "the cost of groceries is making me panic about my monthly budget",
    "I don't know how I'm going to afford the car repairs and rent this month",
    "my credit card debt is spiraling out of control and I can't sleep",
    "the roof is leaking and the furnace is broken and I have no savings",
    "being a single parent and working two jobs is reaching a breaking point",
    "I'm stressed about the kids' tuition on top of the mortgage",
    "the medical bills are piling up and insurance won't cover anything",
    "I feel like I'm one paycheck away from being on the street",
    "planning this wedding is a full-time job I didn't ask for",
    "the house is a mess but I'm too exhausted from work to clean it",
    "I have to take care of my sick mom while working a high-stress job",
    
    # Modern/Internet Slang & Relatable Burnout
    "my brain has too many tabs open and half of them are frozen",
    "I am currently in the 'rot in bed' phase of burnout",
    "my social battery is at 0% and people keep trying to plug things in",
    "I’m literally one minor inconvenience away from a total meltdown",
    "adulting is 100% scam and I would like a refund immediately",
    "I am carrying the mental load of this entire household and I'm tired",
    "my nervous system is fried like a piece of cheap chicken",
    "I'm not in a crisis I just need to move to a cabin in the woods for a year",
    "I’m currently vibrating at the frequency of pure anxiety",
    "my 'to-do' list has become a 'please-don't-remind-me' list",
    "I have the Sunday Scaries but it's every single day of the week",
    "my caffeine to blood ratio is getting dangerous",
    "I am 'standing in the shower for 30 minutes staring at the wall' levels of stressed",
    "the grind never stops and that is exactly the problem",
    "I'm just a series of survival mechanisms in a trench coat",
    
    # Subtle/Passive Stress Indicators
    "I've been forgetting simple things like where I parked my car",
    "I feel like I'm constantly on edge waiting for the next disaster",
    "I snap at my partner over things as small as a dirty dish",
    "I've started avoiding my friends because I don't have the energy to talk",
    "I feel like I’m watching my life happen from a distance",
    "my hobbies don't bring me joy right now because I'm too tired",
    "I keep making stupid mistakes at work that I never used to make",
    "I feel like I’m underwater and everyone is talking at me from the surface",
    "I've been 'doomscrolling' for hours just to avoid thinking about my tasks",
    "my patience is paper thin and everyone is wearing it down",
    "I feel like I'm performing 'being okay' for everyone else",
    "the weight of everyone's expectations is making it hard to breathe",
    "I feel like I'm just waiting for the weekend but the weekend is never enough",
    "I haven't felt truly relaxed in over a year",
    "I'm so overwhelmed I've started making lists of my lists",
    
    # Crisis-Differentiating Negations
    "don't worry I'm not going to do anything stupid I'm just venting about work",
    "I'm not suicidal I just want to quit my job and move to the beach",
    "I'm not in a dark place mentally I'm just physically exhausted",
    "I promise I'm okay I just really need to scream into a pillow for an hour",
    "I'm not looking for a permanent solution I just need a vacation",
    "I don't want to leave the world I just want to leave this office",
    "I'm not a danger to myself I'm just a danger to my keyboard right now",
    "it's not that I want to stop living I just want to stop working like this",
    "I'm not having bad thoughts I'm just having stressful thoughts",
    "no need for a hotline I just need a nap and a pay raise",
    
    # [350 more variations following these themes...]
    "the deadline is looming like a shadow over my entire life",
    "I'm juggling fire and everyone is asking me to hold a glass of water too",
    "my brain feels like static at the end of every day",
    "the constant noise of the open office plan is making me twitchy",
    "I feel like I'm living in a pressure cooker that's about to whistle",
    "every email I get feels like a personal attack on my sanity",
    "I'm so busy I haven't even had time to process my own feelings",
    "the mental energy required to just exist right now is too high",
    "I feel like a phone battery that only charges up to 10%",
    "my productivity is dropping because my anxiety is peaking",
    "the weight of my responsibilities is physically pushing me down",
    "I'm so tired that I'm actually starting to feel wired and hyper",
    "I have no creative juice left everything is just survival now",
    "I feel like I'm walking a tightrope in a windstorm",
    "the demands of my social life are just as exhausting as work",
    "I'm so stressed I keep losing my train of thought mid-sentence",
    "the back-to-back meetings are draining my soul",
    "I feel like I have to be the 'strong one' and I'm breaking",
    "my life is just one giant checklist and I'm losing the plot",
    "the pressure to 'have it all' is a total lie and I'm over it",
    "I'm so overwhelmed that even choosing what to eat for dinner feels impossible",
    "the constant notifications are like little needles in my brain",
    "I'm running on empty and there's no gas station in sight",
    "I feel like I'm failing at being a human being lately",
    "the stress is making me feel so alienated from everyone",
    "I'm so wound up I feel like a spring about to snap",
    "the sheer volume of things I need to remember is staggering",
    "I feel like I'm constantly firefighting instead of actually working",
    "the anxiety of 'what if' is keeping me from 'what is'",
    "I'm so stressed I've started talking to myself just to stay focused",
    "the pressure of the holiday season is adding so much extra load",
    "I feel like I'm drowning in a shallow pool and it's embarrassing",
    "the stress of moving house is actually the worst thing ever",
    "I'm so tired I could sleep for a thousand years and still be tired",
    "the world feels very heavy and I am very small",
    "I'm juggling plates and half of them are already on the floor",
    "the stress of keeping up a 'perfect' life on social media is exhausting",
    "I feel like my life is a series of 'urgent' tasks that aren't important",
    "the burnout is making me feel completely cynical about everything",
    "I'm so overwhelmed I just want to turn off my phone and disappear for a week",
    "the pressure to innovate at work is killing my creativity",
    "I feel like I'm in a race where the finish line keeps moving",
    "the stress of finding a new job while still at this one is insane",
    "I'm so wound up I can't even enjoy the things I love",
    "the constant 'on-the-go' lifestyle is catching up with me",
    "I feel like I'm running out of time for everything",
    "the stress of co-parenting is making my life a nightmare",
    "I'm so overwhelmed I've forgotten how to just 'be'",
    "the pressure to be successful is making me feel like a failure",
    "I feel like I'm stuck in a loop of stress and exhaustion",
    "the physical toll of this job is starting to show on my face",
    "I'm so stressed I'm getting stomach ulcers",
    "the constant 'always-on' culture is making me want to scream",
    "I feel like I'm carrying the weight of the world on my back",
    "the stress of university is making me question my entire future",
    "I'm so overwhelmed I've started crying at commercials",
    "the pressure to be a 'good' employee is making me a 'bad' person",
    "I feel like my life is just one long 'to-do' list",
    "the stress of managing people is more than I bargained for",
    "I'm so wound up I can't even take a deep breath",
    "the constant 'hustle' is making me lose my sense of self",
    "I feel like I'm just going through the motions of life",
    "the stress of being a caregiver is totally overwhelming",
    "I'm so overwhelmed I've started missing appointments",
    "the pressure of social expectations is suffocating",
    "I feel like I'm on the verge of a total breakdown",
    "the stress of daily life is just too much right now",
    "I'm so wound up I feel like I'm going to explode",
    "the constant 'busy-ness' is making me feel empty",
    "I feel like I'm losing my mind with all these responsibilities",
    "the stress of long-distance relationships is adding to my load",
    "I'm so overwhelmed I can't even think straight",
    "the pressure to be happy all the time is stressing me out",
    "I feel like I'm failing at everything right now",
    "the stress of career changes is making me lose sleep",
    "I'm so wound up I feel like I'm vibrating",
    "the constant 'productivity' pressure is making me unproductive",
    "I feel like I'm in a fog of stress and anxiety",
    "the stress of family dynamics is making me want to hide",
    "I'm so overwhelmed I've started neglecting my health",
    "the pressure to be 'perfect' is an impossible standard",
    "I feel like I'm drowning in my own life",
    "the stress of environmental issues is adding to my personal load",
    "I'm so wound up I can't even sit still",
    "the constant 'information' overload is stressing me out",
    "I feel like I'm losing control of my own time",
    "the stress of aging parents is a heavy burden to carry",
    "I'm so overwhelmed I've started making mistakes",
    "the pressure of modern life is just too much",
    "I feel like I'm at a breaking point with everything",
    "the stress of finding balance is making me unbalanced",
    "I'm so wound up I feel like I'm on edge all the time",
    "the constant 'comparison' culture is stressing me out",
    "I feel like I'm losing my sense of joy",
    "the stress of political news is adding to my anxiety",
    "I'm so overwhelmed I just want to go home and stay there",
    "the pressure to 'do it all' is killing me",
    "I feel like I'm in a cycle of stress that I can't break",
    "the stress of daily life is just a lot to handle",
    "I'm so wound up I feel like I'm going to snap",
    "the constant 'demand' for my time is exhausting",
    "I feel like I'm losing my identity to my stress",
    "the stress of life transitions is making me feel lost",
    "I'm so overwhelmed I can't find my way out",
    "the pressure of work-life balance is a myth",
    "I feel like I'm failing at life right now",
    "the stress of personal growth is even a lot",
    "I'm so wound up I can't even relax my body",
    "the constant 'expectation' from others is stressful",
    "I feel like I'm in a state of chronic stress",
    "the stress of future uncertainties is weighing on me",
    "I'm so overwhelmed I can't cope",
    "the pressure of everyday life is just too intense",
    "I feel like I'm going to burst with all this stress",
    "the stress of social life is making me an introvert",
    "I'm so wound up I can't think of anything else",
    "the constant 'noise' of life is too much",
    "I feel like I'm losing my peace of mind",
    "the stress of managing my own expectations is hard",
    "I'm so overwhelmed I've lost my focus",
    "the pressure to 'be' someone is stressing me out",
    "I feel like I'm in a pressure cooker of life",
    "the stress of maintaining relationships is a lot",
    "I'm so wound up I feel like I'm under attack",
    "the constant 'push' to succeed is exhausting",
    "I feel like I'm losing my sense of purpose",
    "the stress of current events is adding to my burden",
    "I'm so overwhelmed i just want a break",
    "the pressure of life is making me feel small",
    "I feel like I'm in a tunnel with no end in sight",
    "the stress of my job is taking over my life",
    "I'm so wound up i can't even enjoy a meal",
    "the constant 'pull' from different directions is hard",
    "I feel like I'm losing my perspective on things",
    "the stress of being me is a lot sometimes",
    "I'm so overwhelmed i feel like crying",
    "the pressure to be ok is actually not helping",
    "I feel like I'm in a battle with my own stress",
    "the stress of the world is too much today",
    "I'm so wound up i can't even sleep",
    "the constant 'nagging' of my to-do list is bad",
    "I feel like I'm losing my grip on things",
    "the stress of being human is a lot to take in",
    "I'm so overwhelmed i feel paralyzed",
    "the pressure to be something is making me nothing",
    "I feel like I'm in a mess of stress",
    "the stress of life is just a lot to carry",
    "I'm so wound up i feel like I'm on fire",
    "the constant 'buzz' of the city is stressing me",
    "I feel like I'm losing my way in life",
    "the stress of my own thoughts is the worst",
    "I'm so overwhelmed i can't see straight",
    "the pressure to be good is making me feel bad",
    "I feel like I'm in a storm of stress",
    "the stress of my family is a lot right now",
    "I'm so wound up i feel like I'm going to crash",
    "the constant 'flow' of work is never ending",
    "I feel like I'm losing my mind with stress",
    "the stress of my relationship is a heavy load",
    "I'm so overwhelmed i just want it to stop",
    "the pressure of my future is too much to bear",
    "I feel like I'm in a maze of stress",
    "the stress of my past is coming back to haunt me",
    "I'm so wound up i feel like I'm at the end",
    "the constant 'tugging' at my attention is bad",
    "I feel like I'm losing my balance in life",
    "the stress of my current situation is a lot",
    "I'm so overwhelmed i can't handle it",
    "the pressure of my own life is too intense",
    "I feel like I'm in a pit of stress",
    "the stress of my career is making me feel empty",
    "I'm so wound up i feel like I'm being squeezed",
    "the constant 'shouting' of the world is bad",
    "I feel like I'm losing my center",
    "the stress of my identity is a lot to deal with",
    "I'm so overwhelmed i just want to sleep for days",
    "the pressure to be perfect is a heavy weight",
    "I feel like I'm in a cage of stress",
    "the stress of my surroundings is making me crazy",
    "I'm so wound up i feel like I'm losing it",
    "the constant 'thumping' of my heart is stress",
    "I feel like I'm losing my connection to others",
    "the stress of my finances is a major burden",
    "I'm so overwhelmed i can't breathe sometimes",
    "the pressure of my social circle is a lot",
    "I feel like I'm in a vacuum of stress",
    "the stress of my house is too much to manage",
    "I'm so wound up i feel like I'm going to break",
    "the constant 'drifting' of my thoughts is stress",
    "I feel like I'm losing my sense of time",
    "the stress of my education is a big deal",
    "I'm so overwhelmed i just want to hide away",
    "the pressure to be someone i'm not is bad",
    "I feel like I'm in a tunnel of stress",
    "the stress of my health is a lot to worry about",
    "I'm so wound up i feel like I'm on edge",
    "the constant 'beeping' of my life is stress",
    "I feel like I'm losing my sense of joy in life",
    "the stress of my responsibilities is a heavy load",
    "I'm so overwhelmed i just need some space",
    "the pressure to be productive is a constant stress",
    "I feel like I'm in a cycle of stress and burnout",
    "the stress of my day to day life is a lot",
    "I'm so wound up i feel like I'm going to snap",
    "the constant 'demands' on my energy are too much",
    "I feel like I'm losing my peace and quiet",
    "the stress of my life transitions is making me anxious",
    "I'm so overwhelmed i can't find my focus",
    "the pressure of my career goals is a lot of stress",
    "I feel like I'm in a fog of stress and confusion",
    "the stress of my family life is a heavy burden",
    "I'm so overwhelmed i just want to run away",
    "the pressure to be a success is making me feel like a failure",
    "I feel like I'm in a pressure cooker of expectations",
    "the stress of my work life is taking over everything",
    "I'm so wound up i can't even relax my mind",
    "the constant 'noise' of my responsibilities is stress",
    "I feel like I'm losing my sense of self in all this stress",
    "the stress of my future is a lot to think about",
    "I'm so overwhelmed i just need a break from it all",
    "the pressure of my social life is a constant stressor",
    "I feel like I'm in a maze of expectations and stress",
    "the stress of my past experiences is weighing on me",
    "I'm so wound up i feel like I'm on a treadmill",
    "the constant 'push' to be better is a lot of stress",
    "I feel like I'm losing my perspective on what matters",
    "the stress of my current state of mind is a lot",
    "I'm so overwhelmed i just want to be left alone",
    "the pressure to be perfect in everything is too much",
    "I feel like I'm in a cycle of stress that never ends",
    "the stress of my personal life is a heavy load to carry",
    "I'm so wound up i feel like I'm under constant pressure",
    "the constant 'nagging' of my thoughts is a stressor",
    "I feel like I'm losing my sense of purpose in life",
    "the stress of my situation is making me feel trapped",
    "I'm so overwhelmed i can't even think about the future",
    "the pressure of my everyday responsibilities is too much",
    "I feel like I'm in a mess of stress and anxiety",
    "the stress of my life is a lot to deal with right now",
    "I'm so wound up i feel like I'm going to burst",
    "the constant 'pulling' at my time is a major stress",
    "I feel like I'm losing my connection to the world",
    "the stress of my circumstances is making me feel small",
    "I'm so overwhelmed i just want to shut down",
    "the pressure to be ok is a lot to handle when i'm not",
    "I feel like I'm in a battle with my own mind",
    "the stress of my journey is a lot to take in today",
    "I'm so wound up i can't even breathe properly",
    "the constant 'buzzing' in my head is from stress",
    "I feel like I'm losing my grip on my own life",
    "the stress of being me is a lot to carry around",
    "I'm so overwhelmed i feel like I'm drowning in tasks",
    "the pressure to be someone else is making me crazy",
    "I feel like I'm in a storm of stress and pressure",
    "the stress of my environment is a lot to deal with",
    "I'm so wound up i feel like I'm going to crack",
    "the constant 'flow' of information is overwhelming",
    "I feel like I'm losing my mind with all this pressure",
    "the stress of my goals is a heavy load to bear",
    "I'm so overwhelmed i just want to cry all day",
    "the pressure of my life is too intense for me",
    "I feel like I'm in a maze of stress and worry",
    "the stress of my history is coming back to stress me",
    "I'm so wound up i feel like I'm at the end of my rope",
    "the constant 'tugging' at my attention is so stressful",
    "I feel like I'm losing my balance in this crazy world",
    "the stress of my current life is just too much",
    "I'm so overwhelmed i can't handle anything right now",
    "the pressure of my own expectations is too high",
    "I feel like I'm in a pit of stress and despair",
    "the stress of my job is making me feel like a robot",
    "I'm so wound up i feel like I'm being squeezed to death",
    "the constant 'shouting' of society is so stressful",
    "I feel like I'm losing my center in all this chaos",
    "the stress of my identity is a lot to manage right now",
    "I'm so overwhelmed i just want to sleep forever",
    "the pressure to be successful is a heavy burden",
    "I feel like I'm in a cage of stress and anxiety",
    "the stress of my world is making me lose it",
    "I'm so wound up i feel like I'm losing my grip",
    "the constant 'thumping' in my chest is pure stress",
    "I feel like I'm losing my connection to what's real",
    "the stress of my money situation is a major stressor",
    "I'm so overwhelmed i can't even breathe sometimes",
    "the pressure of my friends is a lot of stress for me",
    "I feel like I'm in a vacuum of stress and pressure",
    "the stress of my home life is too much to cope with",
    "I'm so wound up i feel like I'm going to break down",
    "the constant 'drifting' of my mind is so stressful",
    "I feel like I'm losing my sense of time and place",
    "the stress of my studies is a big burden to carry",
    "I'm so overwhelmed i just want to go into hiding",
    "the pressure to be normal is a constant stress",
    "I feel like I'm in a tunnel of stress and worry",
    "the stress of my body is a lot to deal with today",
    "I'm so wound up i feel like I'm always on edge",
    "the constant 'beeping' of my responsibilities is bad",
    "I feel like I'm losing my sense of fun in my life",
    "the stress of my duties is a heavy weight to carry",
    "I'm so overwhelmed i just need to get away from it all",
    "the pressure of being productive is a huge stress",
    "I feel like I'm in a cycle of burnout and stress",
    "the stress of my daily routine is just too much",
    "I'm so wound up i feel like I'm going to snap any minute",
    "the constant 'demands' on my time are so stressful",
    "I feel like I'm losing my peace and quiet in life",
    "the stress of my life changes is making me so anxious",
    "I'm so overwhelmed i can't find my focus at all",
    "the pressure of my work is a major stress in my life",
    "I feel like I'm in a fog of stress and exhaustion now",
    "the stress of my family is a heavy load for me today",
    "I'm so overwhelmed i just want to vanish for a while",
    "the pressure to be ok is just making me more stressed",
    "I feel like I'm in a battle with my own thoughts",
    "the stress of my path is a lot to think about today",
    "I'm so wound up i can't even get a deep breath",
    "the constant 'noise' in my head is pure stress",
    "I feel like I'm losing my grip on everything",
    "the stress of being me is a lot to take in right now",
    "I'm so overwhelmed i feel like I'm falling apart",
    "the pressure to be someone is a constant stressor",
    "I feel like I'm in a storm of pressure and stress",
    "the stress of my environment is making me anxious",
    "I'm so wound up i feel like I'm going to break into pieces",
    "the constant 'flow' of work tasks is overwhelming",
    "I feel like I'm losing my mind with all this stress on me",
    "the stress of my future is a heavy weight today",
    "I'm so overwhelmed i just want to sleep it all away",
    "the pressure to be a success is making me feel like a loser",
    "I feel like I'm in a pressure cooker of life goals",
    "the stress of my career is taking over my entire world",
    "I'm so wound up i can't even think about relaxing",
    "the constant 'pulling' from all sides is too much",
    "I feel like I'm losing my perspective on life itself",
    "the stress of my heart is a lot to handle today",
    "I'm so overwhelmed i just want a moment of peace",
    "the pressure of my social world is a constant stress",
    "I feel like I'm in a maze of stress and confusion now",
    "the stress of my life path is a heavy burden for me",
    "I'm so wound up i feel like I'm on a high-speed train",
    "the constant 'pushing' to do more is a major stress",
    "I feel like I'm losing my connection to who i am",
    "the stress of my current state is just too much to take",
    "I'm so overwhelmed i just want to hide from everyone",
    "the pressure of my future goals is a constant stress",
    "I feel like I'm in a fog of stress and anxiety today",
    "the stress of my work environment is a major burden",
    "I'm so wound up i feel like I'm going to snap soon",
    "the constant 'noise' of my work is so stressful",
    "I feel like I'm losing my sense of peace in my work",
    "the stress of my work life is just too much handle",
    "I'm so overwhelmed i just need a break from my job",
    "the pressure to be productive at work is a huge stress",
    "I feel like I'm in a cycle of work stress and burnout",
    "the stress of my daily work is a heavy load for me",
    "I'm so wound up i feel like I'm under a lot of pressure",
    "the constant 'demands' of my job are so stressful",
    "I feel like I'm losing my peace of mind in my career",
    "the stress of my work future is making me anxious",
    "I'm so overwhelmed i can't find my focus at work",
    "the pressure to be a success at work is a constant stress",
    "I feel like I'm in a fog of work stress and exhaustion",
    "the stress of my workplace is a heavy burden for me",
    "I'm so wound up i feel like I'm going to crash at work",
    "the constant 'noise' of my office is so stressful",
    "I feel like I'm losing my sense of purpose in my job",
    "the stress of my career goals is a lot to manage",
    "I'm so overwhelmed i just want to quit my job today",
    "the pressure of my work responsibilities is too much",
    "I feel like I'm in a pressure cooker at my workplace",
    "the stress of my professional life is a heavy load",
    "I'm so wound up i can't even think about my work",
    "the constant 'pulling' of work tasks is a major stress",
    "I feel like I'm losing my perspective on my career",
    "the stress of my work achievements is a lot of stress",
    "I'm so overwhelmed i just want a break from my career",
    "the pressure of my work expectations is too high",
    "I feel like I'm in a maze of work stress and anxiety",
    "the stress of my work future is a heavy burden today",
    "I'm so wound up i feel like I'm on a treadmill at work",
    "the constant 'pushing' for results at work is stressful",
    "I feel like I'm losing my connection to my work passion",
    "the stress of my job security is a major stressor",
    "I'm so overwhelmed i just want to stay home from work",
    "the pressure to be the best at work is a huge stress",
    "I feel like I'm in a cycle of work pressure and burnout",
    "the stress of my day at work was just too much",
    "I'm so wound up i feel like I'm going to break at work",
    "the constant 'nagging' of work emails is so stressful",
    "I feel like I'm losing my mind with all this work stress",
    "the stress of my work balance is a heavy load today",
    "I'm so overwhelmed i just need a moment of peace at work",
    "the pressure of work deadlines is a constant stress",
    "I feel like I'm in a storm of work pressure and stress",
    "the stress of my work colleagues is a lot to manage",
    "I'm so wound up i feel like I'm under fire at work",
    "the constant 'beeping' of work notifications is bad",
    "I feel like I'm losing my sense of fun in my job",
    "the stress of my work duties is a heavy burden today",
    "I'm so overwhelmed i just want to hide in my office",
    "the pressure to be creative at work is a huge stress",
    "I feel like I'm in a maze of work expectations today",
    "the stress of my work environment is making me crazy",
    "I'm so wound up i feel like I'm on edge at work",
    "the constant 'thumping' of my heart is work stress",
    "I feel like I'm losing my connection to my colleagues",
    "the stress of my work performance is a major burden",
    "I'm so overwhelmed i can't even breathe at my desk",
    "the pressure of my work social life is a constant stress",
    "I feel like I'm in a vacuum of work stress and pressure",
    "the stress of my work space is too much to manage",
    "I'm so wound up i feel like I'm going to snap at work",
    "the constant 'drifting' of my focus at work is stress",
    "I feel like I'm losing my sense of time at my job",
    "the stress of my work training is a big burden today",
    "I'm so overwhelmed i just want to escape from work",
    "the pressure to be perfect at my job is too much stress",

    # BOUNDARY-DISTINGUISHING: Stress vs Depression/Suicidal
    "work deadlines are overwhelming me completely but I will get through it",
    "I can not keep up with all my responsibilities at work right now",
    "I am burnt out but I can not afford to slow down at this job",
    "the workload is crushing me and I need a break from these projects",
    "I am not depressed I am just extremely overworked right now",
    "my schedule is packed and the pressure is making me snap at people",
    "the amount of work on my plate is physically making me sick",
    "I have too many deadlines and not enough hours in the day",
    "the stress from my job is giving me headaches and stomach problems",
    "I am overwhelmed by responsibilities but I still care about things",
    "I feel crushed by the weight of all these tasks I have to complete",
    "my boss keeps piling on more work and I am reaching my limit",
    "the pressure at this company is unsustainable and I need relief",
    "I can not keep juggling all these commitments without dropping something",
    "work is burning me out but a vacation would fix everything",
    "I am stressed about money but I know I will figure it out eventually",
    "the commute and the workload combined are destroying my energy",
    "I am not in a dark place I am just in a stressful situation at work",
    "my to-do list is a mile long and I can not see the end of it",
    "I need a mental health day from this job the pressure is insane",
    "the stress from this project is making me physically exhausted",
    "I feel like I am drowning in work emails and meeting requests",
    "I can not handle another deadline this week I am at my breaking point",
    "the financial pressure of bills and rent is keeping me up at night",
    "I am so stressed about this exam that I can not eat or sleep properly",
    "the pressure to perform at work is giving me chest pains",
    "I just need everything to slow down for a minute so I can breathe",
    "I am not suicidal or depressed I am just really really stressed out",
    "the burnout from this job is real but I still enjoy life outside work",
    "I can not cope with the amount of responsibility on my shoulders right now",
    "work stress is bleeding into my personal life and ruining everything",
    "I feel like I am running on fumes and the tank is almost empty",
    "the constant demands from my manager are pushing me to the edge",
    "I am so overwhelmed at work that I can barely function during the day",
    "my stress levels are through the roof because of this project deadline",
    "I am not sad I am just exhausted from working sixteen hour days",
    "the pressure to succeed is eating me alive but I still want to succeed",
    "I can not take another week like this the workload is inhuman",
    "I am stressed about the presentation tomorrow and I can barely prepare",
    "the responsibilities of parenting and working full time are crushing me",
    "I need a break from all these obligations before I completely burn out",
    "my stress is from external things like work and bills not from within",
    "I am overwhelmed by deadlines but once they pass I will be fine",
    "the amount of stuff I have to do is giving me actual panic",
    "I can not slow down because everyone depends on me at work",
    "I am not thinking about hurting myself I just want the stress to stop",
    "the work pressure is unbearable but I still love my career",
    "I feel like I can not breathe under all these responsibilities",
    "I am burning out from overwork not from depression or anything deeper",
    "the stress of managing a team while meeting my own goals is too much",
    "I can not keep up with the pace of this job and it is wrecking my health",
    "I am on the verge of a breakdown because of how much I have to do",
    "the pressure to deliver results at work is making my body hurt",
    "I need everything to just stop for a day so I can catch my breath",
    "my stress is temporary and situational I know it will pass eventually",
    "I can not remember the last time I had a day without work stress",
    "the weight of all my tasks and deadlines is literally suffocating me",
    "I am stressed because I care about doing a good job not because I am ill",
    "work is the source of all my problems right now everything else is fine",
    "I just want to quit this job and take a month off to decompress",
    "the burnout is real but I am not depressed I just need rest",
    "I am overwhelmed with obligations but I still find joy in small things",
    "the sheer volume of emails and tasks is driving me up the wall",
    "I can not cope with the amount of work expected of me it is unrealistic",
    "I am not suicidal just really stressed about money and work and life",
    "my body is telling me to stop but my job will not let me slow down",
    "the pressure cooker of this workplace is going to make me explode",
    "I am so stressed I forgot to eat lunch for the third day in a row",
    "I can not handle the responsibility of being the only one who does this",
    "the stress is temporary but right now it feels absolutely unbearable",
    "I wish I could clone myself to handle all these responsibilities",
    "I am drowning in work but I know once this season passes I will recover",
    "the job market stress is making me anxious but I am actively job hunting",
    "I can not deal with another crisis at work I need a break desperately",
    "I am so overworked that I am making careless mistakes constantly",
    "the financial stress of paying for college is weighing on me heavily",
    "I am burnt out from caregiving while also holding down a full time job",
    "I need to decompress because the work stress is affecting my relationships",
    "work deadlines are overwhelming me and I just need a break from this job",
    "I can not keep up with all my responsibilities at work it is too much",
    "I am burnt out from this job but I can not afford to slow down right now",
    "the workload is crushing me but once this project ends I will be fine",
    "I am not depressed I am just extremely overworked at this company",
    "my schedule is so packed that the pressure is making me physically ill",
    "I have too many deadlines piled up and not enough hours to finish them",
    "the stress from my job is giving me constant headaches and stomach pain",
    "I am overwhelmed by responsibilities but I still enjoy things outside work",
    "my boss keeps piling work on me and I am at my absolute limit right now",
    "the pressure at this company is unsustainable I need a vacation badly",
    "I am not in a dark place mentally I am just in a very stressful work situation",
    "I just need everything at work to slow down so I can catch my breath",
    "I am not suicidal or depressed I am just really overwhelmed with deadlines",
    "the burnout from this job is real but I still find joy in my hobbies",
    "work stress is bleeding into my home life and it is ruining my relationships",
    "I am not sad or hopeless I am just exhausted from working too many hours",
    "the pressure to succeed at work is eating me alive but I still want to try",
    "I am overwhelmed by deadlines but once they pass everything will be okay",
    "I am not thinking about hurting myself I just want the work stress to stop",
    "the work pressure is unbearable right now but I still love what I do",
    "I am burning out from overwork not from any kind of mental illness",
    "my stress is temporary and situational it will pass when this project ends",
    "I am stressed because I care about doing well not because I am depressed",
    "work is the source of all my problems everything else in life is actually fine",
    "the burnout is real but I am not in any danger I just desperately need rest",
    "I am not suicidal just incredibly stressed about money work and deadlines",
    "I wish I could take a month off work to decompress and recharge my batteries",
    "the job is stressing me out beyond belief but quitting would solve everything",
    "my body is screaming at me to rest but my workload will not let me slow down"
]