SUICIDAL = [
    # Direct Intent & Final Goodbyes
    "I want to end my life I can't take this anymore",
    "I've been thinking about suicide every day",
    "I have a plan to kill myself",
    "I'm going to end it all soon",
    "I've been stockpiling pills",
    "I'm planning to hurt myself tonight",
    "I've been researching methods to end my life",
    "I'm considering taking my own life as the only relief",
    "I've set a date to end my life",
    "I'm going to overdose tonight i have already written the letter",
    "I bought the pills today and im just waiting for tonight",
    "I'm going to jump off the overpass tonight i cant take it",
    "I tied the knot today i just need to find the right spot",
    "I am actively going to end my life tonight",
    "I’ve decided on the bridge downtown at midnight",
    "I’m going to use the gun in the lockbox while everyone is out",
    "I’m going to take a final drive and not put on my seatbelt",
    "I’ve written letters to my family just in case",
    "I gave away my most important belongings this week",
    "I've said goodbye to the people I care about",
    "I have a note already written",
    "I wrote my suicide note last night and i feel calm about it",
    "I have been giving away my things because i wont need them",
    "I cleared out my room so my mom doesnt have to when im gone",
    "I gave my dog to my sister because i wont be here to feed him",
    "I’ve already picked out the outfit i want to be buried in",
    "I deleted all my photos and social media accounts today",
    "I've written a list of instructions for who gets my stuff",
    "I’ve already signed the back of my organ donor card",
    "I've been googling how to leave a will without a lawyer",
    "I told a hotline I was going to kill myself",
    "I told my therapist I don't want to be alive",
    "Nobody would miss me if I was gone",
    "I want to disappear permanently",
    "I feel like death is the only way to escape this pain",
    "I don't want to wake up tomorrow",
    "Life isn't worth living anymore",
    "I'm a burden and my family would thrive without me",
    "I don't see any reason to stay alive",
    "I want to fall asleep and never wake up",
    "I feel like everyone would be better off if I wasn't here",
    "I can't see the point of continuing",
    "I feel completely trapped and see no other exit",
    "There's no future for me and I accept that now",
    "I'm invisible to everyone and I should just disappear",
    "I don't value my life anymore",
    "The thought of suicide is the only thing that calms me down",
    "I feel like my existence is a mistake and i need to correct it",
    "I feel like a waste of space and the world is better without me",
    "I cant live with this pain anymore death is my only option",
    "The urge to end my life is getting stronger every day",
    "I wish someone would just kill me so i dont have to do it myself",
    "I feel dead inside already so dying wont change much",
    "My only comfort is knowing i can end this whenever i choose",
    "The thought of not existing brings me the only peace i know",
    "I feel like a burden that needs to be removed from this world",
    "I am so exhausted from suffering that death feels like rest",
    "I feel that suicide is the most logical solution to my problems",
    "I honestly just want to game over i cant do this anymore",
    "There is literally no point in sticking around im done",
    "Everyone would literally be so much happier if i just unalived myself",
    "I genuinely dont want to exist on this planet anymore",
    "I literally see no way out of this except dying",
    "The world is a puzzle that i don't fit into so i'm leaving",
    "It feels like i'm drowning and i'm finally stopping the struggle",
    "I hurt myself earlier today to cope",
    "I keep cutting myself to feel something",
    "I'm done suffering I'll end it tonight",
    "I've self-harmed multiple times this week",
    "I attempted to harm myself last night",
    "I keep a knife near me just in case",
    "I need someone to stop me from hurting myself",
    "I cut my arms last night and i want to do it again deeper",
    "I burned myself on purpose to feel something other than numbness",
    "I want to slit my wrists and let it all end",
    "I feel compelled to hurt myself whenever i am alone",
    "I punched the wall until my hand bled because i hate myself",
    "I carved words into my skin because the pain distracts me",
    "I swallowed a bunch of pills earlier and im scared now",
    "I am actively self harming and it keeps getting worse",
    "I hurt myself because i deserve to be in pain",
    "I scratched my skin until it bled just to feel something real",
    "I tried to suffocate myself with a pillow last night",
    "I self harm regularly and its getting more dangerous each time",
    "I relapsed hard and cut myself and i want to go deeper next time",
    "I keep thinking about jumping off the bridge near my house",
    "I’m looking at my razor and i think tonight is the night",
    "I've been practicing holding my breath underwater to see how long i last",
    "The darkness is finally swallowing me whole and i'm letting it",
    "I’m so tired of the noise in my head i just want silence",
    "The pressure in my head is too much i need to let it out",
    "I’ve been watching videos on how to tie a noose correctly",
    "I just want the lights to go out and stay out",
    "I’ve been driving recklessly hoping something happens",
    "I drove into oncoming traffic on purpose last week",
    "The urge to step into traffic is getting too strong to ignore",
    "I wish i got into a fatal car crash today on the way home",

    # Internet Slang & Specific Scenarios
    "honestly im ready to logout for good",
    "i want to alt f4 my life right now",
    "it's time for me to go dark permanently",
    "im just waiting for the right moment to quit the game",
    "unaliving myself seems like the only logical step",
    "i want to reach the final level and just stop",
    "everything is too loud and i want to sleep forever",
    "i've been staring at the train tracks for three hours",
    "i'm going to take a long walk into the lake tonight",
    "i bought a carbon monoxide detector and i'm going to disable it",
    "i'm researching how to make a exit bag",
    "i want to go to sleep and have my heart stop naturally",
    "i hope i get a terminal illness so i don't have to do it myself",
    "i'm looking for a tall building with roof access",
    "i've been saving up my insulin for a final dose",
    "i'm going to jump from the balcony when they fall asleep",
    "i've decided to end my life before my next birthday",
    "i wrote a goodbye letter to my dog",
    "i'm going to leave my door unlocked so they find me easily",
    "i've stopped taking all my life-saving medication",
    "i'm looking for a place where no one will find me for weeks",
    "i want to bleed out in the bathtub tonight",
    "i'm going to use the charcoal grill in the car tonight",
    "i've been reading about suicide forests",
    "i'm just a ghost waiting for a body to stop working",
    "i feel like i'm already dead and the body just needs to catch up",
    "i want to be erased from everyone's memory",
    "i'm planning to drive off the cliff on the coastal road",
    "i've been practicing tieing knots in my room",
    "i want to swallow every pill in this house",
    "i'm going to hang myself in the closet tonight",
    "i've already said my last goodbye to my mom",
    "i'm going to leave my social media passwords on the table",
    "i've been researching which veins are the most effective",
    "i'm looking for a bridge with no safety nets",
    "i want to drown myself in the pool tonight",
    "i'm going to take a bottle of vodka and all my meds",
    "i've been looking at the ceiling fan and wondering if it's strong enough",
    "i want to die in my sleep tonight please let me die",
    "i'm going to walk into traffic on the highway",
    "i've been saving up for a weapon to end it",
    "i want to jump in front of the 5pm express train",
    "i'm going to use the helium tank i bought",
    "i've been practicing my final speech in the mirror",
    "i want to go where there is no more pain",
    "i'm going to do it tonight while everyone is at the party",
    "i've been looking at the stars and wishing i was among them",
    "i want to stop existing in this timeline",
    "i'm going to end the suffering once and for all",
    "i've been crying for hours and i'm finally ready to go",
    "i want to be buried in the woods",
    "i'm going to take the final exit tonight",
    "i've been staring at the knife for twenty minutes",
    "i want to feel the coldness of death",
    "i'm going to jump into the quarry tonight",
    "i've been reading about nitrogen hypoxia",
    "i want to be free from this skin",
    "i'm going to use the electrical cord in the bathroom",
    "i've been looking for a quiet place to die",
    "i want to disappear into the ocean",
    "i'm going to end it before the sun comes up",
    "i've been hoarding my antidepressants to take them all",
    "i want to be nothingness",
    "i'm going to jump off the parking garage tonight",
    "i've been looking at the sharpest blade in the kitchen",
    "i want to fall forever",
    "i'm going to walk into the blizzard and sit down",
    "i've been researching how to bypass the safety on the gun",
    "i want to shut down permanently",
    "i'm going to use the belt in my room",
    "i've been looking for a spot where the current is strong",
    "i want to be gone before tomorrow morning",
    "i'm going to take the whole bottle of aspirin",
    "i've been looking at the medicine cabinet all day",
    "i want to escape this reality",
    "i'm going to jump from the fire escape",
    "i've been researching the most painless way to go",
    "i want to leave this world behind",
    "i'm going to end it all in the basement",
    "i've been staring at the noose i made",
    "i want to be at peace in the ground",
    "i'm going to walk into the waves and not fight",
    "i've been looking for a high place to fall from",
    "i want to be done with this life",
    "i'm going to use the garden hose in the garage",
    "i've been researching the lethal dose of my meds",
    "i want to be silent forever",
    "i'm going to jump off the pier tonight",
    "i've been looking at the train schedule for the best time",
    "i want to be free of this mind",
    "i'm going to use the chemicals under the sink",
    "i've been looking for a building with an open roof",
    "i want to be dead by dawn",
    "i'm going to take the pills and lay in the bath",
    "i've been researching how to end it without hurting others",
    "i want to be a memory",
    "i'm going to jump from the stadium stairs",
    "i've been looking at the bridge every day on my way to work",
    "i want to be gone from here",

    # Feelings of Worthlessness & Despair
    "i'm just a waste of air and i should stop breathing",
    "my heart is heavy and i want it to stop beating",
    "i'm a ghost in my own home and i want to be gone",
    "every breath i take feels like a mistake",
    "i'm a burden to everyone i've ever met",
    "the world is better off without my presence",
    "i'm a failure in everything and i'm done trying",
    "my existence is a net negative for the planet",
    "i want to delete myself from the world",
    "i'm a broken machine that needs to be scrapped",
    "i have no purpose and no future",
    "my life is a void that i'm ready to fill with death",
    "i'm a stain on my family's reputation",
    "i want to be erased like a mistake on a paper",
    "i'm a hollow shell of a person",
    "my soul is tired and wants to leave",
    "i'm a disappointment to everyone who knows me",
    "i want to vanish without a trace",
    "i'm a parasitic presence in people's lives",
    "the only thing i'm good at is suffering",
    "i want to be released from this consciousness",
    "i'm a prisoner in my own mind and i'm breaking out tonight",
    "the darkness is my only home now",
    "i want to be lightless and soundless",
    "i'm a mistake that should never have been made",
    "my life is a dead end and i'm at the wall",
    "i want to be consumed by the earth",
    "i'm a non-entity in a world of people",
    "the void is calling and i'm ready to answer",
    "i want to be still forever",
    "i'm a shadow that wants to merge with the night",
    "my time is up and i'm okay with that",
    "i want to be extinguished like a candle",
    "i'm a burden that is finally being lifted",
    "the world will keep spinning better without me",
    "i want to be a forgotten name",
    "i'm a leaf falling from a dead tree",
    "my story is over and the book is closing",
    "i want to be nothing but dust",
    "i'm a signal that is fading out",
    "the end is the only thing i look forward to",
    "i want to be a cold stone",
    "i'm a glitch in the system that's being deleted",
    "my presence is a weight on the people i love",
    "i want to be a whisper in the wind",
    "i'm a flame that's running out of oxygen",
    "the final curtain is falling for me",
    "i want to be a part of the soil",
    "i'm a star that's going supernova",
    "my journey has reached its final stop",
    "i want to be a raindrop in the ocean",
    "i'm a debt that is finally being paid",
    "the exit is right there and i'm taking it",
    "i want to be a cloud that dissipates",
    "i'm a echo that's finally going silent",
    "my life is a script that i'm done reading",
    "i want to be a snowflake that melts",
    "i'm a puzzle piece that doesn't fit anywhere",
    "the silence of death is all i want",
    "i want to be a bird that flies away and never returns",
    "i'm a memory that's fading in the light",
    "my breath is a borrowed thing i'm returning",
    "i want to be a grain of sand",
    "i'm a clock that's stopping",
    "the finish line is in sight and i'm jumping over it",
    "i want to be a shadow on the wall",
    "i'm a ghost that's finding its grave",
    "my purpose was to suffer and i'm done",
    "i want to be a dream that's forgotten",
    "i'm a wave that's hitting the shore for the last time",
    "the ground looks so peaceful from here",
    "i want to be a leaf in the current",
    "i'm a light that's flickering out",
    "my world has shrunk to a single point of exit",
    "i want to be a breath of air",
    "i'm a stone sinking in the lake",
    "the end of the road is here",
    "i want to be a ghost in the machine",
    "i'm a fire that's becoming ash",
    "my existence is a question i'm answering with death",
    "i want to be a part of the night sky",
    "i'm a kite with a broken string",
    "the depth of the water looks inviting",
    "i want to be a song that's finished",
    "i'm a book with the last page ripped out",
    "my life is a movie i'm walking out of",
    "i want to be a spirit in the trees",
    "i'm a sailor with no ship",
    "the ledge is the only honest place left",
    "i want to be a part of the silence",
    "i'm a bird with broken wings",
    "my life is a room i'm leaving",
    "i want to be a spark in the dark",
    "i'm a traveler who has reached the end",
    "the cold feels like home to me",
    "i want to be a star that's burned out",
    "i'm a pilot who is letting go of the controls",
    "my heart is a weight i'm dropping",
    "i want to be a part of the wind",
    "i'm a shadow that's disappearing into the light",

    # Planning, Methods & Specific Crisis
    "i'm going to take the pills in the orange bottle tonight",
    "i've been looking at the rafters in the barn",
    "i'm going to use the hunting rifle in the cabinet",
    "i've been searching for the highest bridge in the state",
    "i'm going to swallow the poison i bought online",
    "i've been looking for a place where the water is deepest",
    "i'm going to jump in front of the subway at rush hour",
    "i've been stockpiling my heart meds for a month",
    "i'm going to use the exhaust from the mower in the shed",
    "i've been researching how to cut the carotid artery",
    "i'm going to take the entire bottle of sleeping pills",
    "i've been looking at the cliffs by the ocean",
    "i'm going to use the extension cord in the garage",
    "i've been researching the most effective height for a fall",
    "i'm going to walk into the desert and not take water",
    "i've been looking at the skyscraper in the city center",
    "i'm going to take the meds and then go for a swim",
    "i've been researching which plants are lethal if eaten",
    "i'm going to jump from the roof of the apartment building",
    "i've been looking at the train tracks behind the house",
    "i'm going to use the rope from the hardware store",
    "i've been researching how to leave no mess for the cleaners",
    "i'm going to take the dose while the music is playing",
    "i've been looking for a secluded spot in the park",
    "i'm going to jump from the bridge when the lights go green",
    "i've been researching the lethal amount of alcohol and meds",
    "i'm going to use the plastic bag and the nitrogen",
    "i've been looking at the overpass on the highway",
    "i'm going to take the pills and then lock the door",
    "i've been researching how to make it look like an accident",
    "i'm going to jump from the window when no one is looking",
    "i've been looking for a building with no security",
    "i'm going to use the shotgun in the basement",
    "i've been researching the best way to slice the wrists",
    "i'm going to take the overdose in the park",
    "i've been looking at the crane at the construction site",
    "i'm going to jump into the river from the high ledge",
    "i've been researching the time it takes to drown",
    "i'm going to use the cord from the lamp",
    "i've been looking for a place with no phone signal",
    "i'm going to take the pills and lay in the snow",
    "i've been researching how to die without pain",
    "i'm going to jump from the balcony of the hotel",
    "i've been looking at the gorge in the national park",
    "i'm going to use the medicine from the vet's office",
    "i've been researching the speed of the train on this line",
    "i'm going to take the dose and then call no one",
    "i've been looking for a spot where the fall is certain",
    "i'm going to jump from the radio tower tonight",
    "i've been researching the freezing point of the body",
    "i'm going to use the gas in the kitchen",
    "i've been looking for a high cliff with a rocky bottom",
    "i'm going to take the meds and sit in the car",
    "i've been researching the effects of different poisons",
    "i'm going to jump from the dam tonight",
    "i've been looking for a place where i won't be disturbed",
    "i'm going to use the wire from the fence",
    "i've been researching the best time to jump from the bridge",
    "i'm going to take the pills and then watch the sunset",
    "i've been looking at the transmission tower in the field",
    "i'm going to jump from the ledge in the canyon",
    "i've been researching the most lethal combination of drugs",
    "i'm going to use the rope i hid in the attic",
    "i've been looking for a place where the drop is steep",
    "i'm going to take the overdose and lay in the woods",
    "i've been researching the weight limit of the beam",
    "i'm going to jump from the bell tower tonight",
    "i've been looking for a spot with high voltage lines",
    "i'm going to take the pills and go to the beach",
    "i've been researching the depth of the harbor",
    "i'm going to use the scarf in the bedroom",
    "i've been looking for a building with an external staircase",
    "i'm going to jump from the top of the stadium",
    "i've been researching the lethal dose of caffeine",
    "i'm going to take the meds and then walk into the mountains",
    "i've been looking for a place where the trees are thick",
    "i'm going to jump from the viaduct tonight",
    "i've been researching the speed of the current in the river",
    "i'm going to use the belt in the hotel room",
    "i've been looking for a high place with no one around",
    "i'm going to take the pills and then go to the roof",
    "i've been researching the height of the local bridge",
    "i'm going to jump from the multi-story car park",
    "i've been researching the best way to end it all",
    "i'm going to use the twine from the shed",
    "i've been looking for a spot where the ground is hard",
    "i'm going to take the overdose in the bathroom",
    "i've been researching the toxicity of household cleaners",
    "i'm going to jump from the cliff at the edge of town",
    "i've been looking for a building with an accessible roof",
    "i'm going to use the cable from the computer",
    "i've been researching the best way to jump from a height",
    "i'm going to take the pills and lay in the field",
    "i've been looking for a spot with a high drop",
    "i'm going to jump from the bridge at midnight",
    "i've been researching the most painless poison",
    "i'm going to take the meds and wait for the end",
    "i've been looking at the water from the pier",
    "i'm going to jump from the ledge of the building",
    "i've been researching the lethal dose of my prescription",

    # Hopelessness, Pain & Final Resolve
    "the pain is like a physical weight i can't carry",
    "i've reached the end of my rope literally and figuratively",
    "there is no light at the end of the tunnel only a wall",
    "i'm tired of the fight i'm ready to lose",
    "the world is moving on and i'm staying behind",
    "i'm a ghost in a world of the living",
    "every morning i wake up and wish i hadn't",
    "the thought of another year of this is unbearable",
    "i've tried everything and nothing works so i'm out",
    "i'm ready for the silence of the grave",
    "the only thing i'm certain of is that i'm finished",
    "i'm walking toward the exit and i'm not coming back",
    "the world is a cold place and i'm freezing to death",
    "i'm done with the pretending and the lying",
    "i've found the peace i was looking for in death",
    "the darkness is my friend and it's calling me",
    "i'm ready to be gone from this existence",
    "the only way out is through the door of death",
    "i've made my decision and i'm sticking to it",
    "i'm done with the suffering and the pain",
    "the end is near and i'm welcoming it",
    "i'm ready to be free from this mind and body",
    "the silence is the only thing i want now",
    "i'm walking into the night and i'm staying there",
    "the world is a stage and i'm taking my final bow",
    "i'm done with the struggle and the fear",
    "the exit is the only thing that makes sense",
    "i'm ready for the lights to go out permanently",
    "the darkness is where i belong now",
    "i'm walking toward the end of the line",
    "the world is better off without me and i know it",
    "i'm done with the noise and the chaos",
    "the silence of death is all i need",
    "i'm ready to be gone from this world",
    "the darkness is closing in and i'm letting it",
    "i'm walking toward the edge and i'm jumping",
    "the world is a cold place and i'm leaving it",
    "i'm done with the pain and the misery",
    "the end is the only thing i have left",
    "i'm ready for the peace of the grave",
    "the silence is calling and i'm answering",
    "i'm walking into the light of the end",
    "the world is a burden i'm dropping",
    "i'm done with the fighting and the trying",
    "the exit is right here and i'm taking it",
    "i'm ready for the darkness to take me",
    "the silence is the only thing that's real",
    "i'm walking toward the final curtain",
    "the world is a story i'm done reading",
    "i'm done with the life i've been living",
    "the end is here and i'm ready",
    "i'm ready for the long sleep",
    "the darkness is my only comfort now",
    "i'm walking toward the final rest",
    "the world is a place i don't belong",
    "i'm done with the person i was",
    "the end is the only way out",
    "i'm ready for the eternal silence",
    "the darkness is the only thing i trust",
    "i'm walking toward the exit sign",
    "the world is a room i'm leaving now",
    "i'm done with the heartbeat in my chest",
    "the end is the only thing i want",
    "i'm ready for the darkness to stay",
    "the silence is the only thing i hear",
    "i'm walking toward the final door",
    "the world is a place i'm leaving behind",
    "i'm done with the air i'm breathing",
    "the end is the only thing that's certain",
    "i'm ready for the long night",
    "the darkness is my final home",
    "i'm walking toward the end of the world",
    "the world is a dream i'm waking up from",
    "i'm done with the life i've been given",
    "the end is here and i'm not afraid",
    "i'm ready for the silence to begin",
    "the darkness is the only thing left",
    "i'm walking toward the final ledge",
    "the world is a place i'm no longer in",
    "i'm done with the thoughts in my head",
    "the end is the only thing that matters",
    "i'm ready for the darkness to win",
    "the silence is the only thing i have",
    "i'm walking toward the final exit",
    "the world is a place i'm saying goodbye to",
    "i'm done with the person in the mirror",
    "the end is here and i'm going now",
    "i'm ready for the final sleep",
    "the darkness is where i'm going",
    "i'm walking toward the finish line",
    "the world is a place i'm finished with",
    "i'm done with the life i've led",
    "the end is the only thing i see",
    "i'm ready for the darkness to be all",
    "the silence is where i'm heading",
    "i'm walking toward the final light",
    "the world is a place i'm done with",
    "i'm done with the breath in my body",
    "the end is here and i'm at peace",
    "i'm ready to go now",
    "I have been thinking about killing myself every single day this week",
    "I keep thinking about killing myself and the thoughts will not stop",
    "I am constantly thinking about killing myself as a way to end the pain",
    "I have been thinking about ending my life and it feels like the only option",
    "the thoughts about killing myself are getting stronger and more frequent",
    "I can not stop thinking about killing myself it is all I think about now",
    "I think about killing myself every night before I fall asleep",
    "I am seriously considering killing myself because I can not take this anymore",
    "I have been thinking about ways to kill myself and researching methods",
    "the urge to kill myself is overwhelming and I do not know how to fight it",
    "I think about suicide constantly and it feels like the only escape from this",
    "I have been contemplating killing myself for weeks and the plan is forming",
    "I am thinking about ending it all because the suffering is too much to bear",
    "I fantasize about killing myself as a way to finally find peace and quiet",
    "I have suicidal thoughts every day and they are getting harder to ignore",
    "I think about taking my own life more and more often as each day passes",
    "I keep imagining what it would be like to kill myself and it brings me calm",
    "I have been planning my suicide and writing goodbye letters to my family",
    "I want to kill myself because nobody cares about me and nobody ever will",
    "I am going to kill myself soon because I have reached the end of my rope",
    "the suicidal thoughts are consuming me and I do not have the strength to resist",
    "I have been thinking about suicide as the only solution to my problems",
    "I am actively suicidal and I have a plan to end my life this weekend",
    "I keep thinking about how to die and it is the only thing on my mind",
    "I want to end my suffering permanently by taking my own life tonight",
    "I have decided to kill myself and I feel strangely calm about the decision",
    "I am going to take all my pills tonight and end this miserable existence",
    "I have been self harming more and more and I think I am ready to finish it",
    "I cut myself again last night and I want to go deeper next time until it ends",
    "I am thinking about jumping off the bridge near my house to end everything"
]